### ISSUE TITLE
References

### ISSUE THREAD

**Issue by frederikcoppens** [galaxyproject/training-material#10]
I would also move the references to (a separate file) in each folder in stead of in the general readme. I saw for some material there is already a list of references.

Splitting the markdown files will aid the maintainability IMO but will require merging them to generate the pdf.

**Comment by bgruening** [comment]
Would a list of doi or a bibtex be better, from which we generate references?

**Comment by friedue** [comment]
for markdown, it's probably easier to link using a doi, but I have no idea what the best practice for markdown bibliographies looks like

**Comment by frederikcoppens** [comment]
doi or PMID would be elegant
if as a first pass just hardcoded listing them simplifies things, also good
