### ISSUE TITLE
Instructors on the training website

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#1055]
As discussed during the instructor meeting #1009, it would be nice to display the instructors (from the GTN trainer directory: https://galaxyproject.org/teach/trainers/) on the training website

Ideas
- Move the directory of instructors here within a `INSTRUCTORS.yaml` file for people who want to register with some infos (name, location, institution, area of expertise, etc)
- Add a page (similar to Hall of Fame?) to display
    - instructors
    - organizations
    - map (from https://github.com/bgruening/galaxy-maps ?)

**Comment by tnabtaf** [comment]
Um, but I could use some help....

**Comment by hexylena** [comment]
@tnabtaf turfed this to me and we (and @shiltemann) had some discussion over it.

- Instructors would be a great field to have! we could potentially just expand the contributors with this information, and anyone who fills that, we know are willing instructors.
- We can definitely add a separate view with only the instructors
- In /teach/trainers it's mostly organisations, and after some discussion we'll just delete this completely as it is supplanted by use + events on the hub, and now this directory.

So given this, I think we'll just expand the CONTRIBUTORS.yaml to include some fields for trainer details.

**Comment by tnabtaf** [comment]
By the way, all of the outdated material on hub about GTN has been dropped, and replaced with redirects to pages in the GTN website.

**Comment by lldelisle** [comment]
See #3957
