### ISSUE TITLE
GTN meeting (15th of November)

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#1088]
The next meeting of the GTN will take place during the next CoFest (#1082), on Thursday, the **15th of November**

To accommodate different time zones and schedules, we will have 2 calls (with similar discussions) at [**7am** (UTC + 1)](http://arewemeetingyet.com/Berlin/2018-11-15/07:00/GTN%20meeting) and [**4pm** (UTC + 1)](http://arewemeetingyet.com/Berlin/2018-11-15/16:00/GTN%20meeting) via [Hangout](https://hangouts.google.com/hangouts/_/calendar/Z2FsYXh5dW5pZnJlaWJ1cmdAZ21haWwuY29t.459bpoqjjo780nm56q267ba7i8).

If there are any topics you wish to discuss, please comment here 😄

**Comment by bebatut** [comment]
@Slugger70 raised this issue in #1103, talking about the tool screenshots: "Maybe we need a system where we can automatically produce them from a workflow? Naming them sensibly and so including them still? Probably a conversation for our next meeting/hackathon?"

**Comment by nsoranzo** [comment]
> @Slugger70 raised this issue in #1103, talking about the tool screenshots: "Maybe we need a system where we can automatically produce them from a workflow?

Just a note that with the UI refresh in Galaxy 19.01, we will have to redo *all* the screenshots on tutorials that have them.

**Comment by erasche** [comment]
@jmchilton attempted this already for the rule builder: https://github.com/galaxyproject/training-material/blob/master/topics/galaxy-data-manipulation/tutorials/upload-rules/gen_images.sh

**Comment by bebatut** [comment]
The meeting is next week.

**Proposed Agenda**
- Training material
  - What happen during the last months?
    - Bunch of new tutorials and some hidden
    - planemo for training
    - Embedded feedback forms
  - Ongoing
    - Biohackathon
    - Training Handbook
    - Workflow testing
  - Future direction
    - More visibility of the training material
    - Localization
    - Tags and curriculum
- Community
  - What happen during the last months?
    - GOBLET
    - Instructor meeting
    - Tutorial of the Month
    - TIaaS
    - Advertisement card
  - Ongoing
    - Instructor community
  - Future direction
    - Next CoFest and meeting: 21st of February, 2019

**Comment by erasche** [comment]
# GTN meeting

## attendees

Morning Session

- Bérénice @bebatut BB
- Saskia @shiltemann SH
- Helena @erasche HR
- Simon @slugger70 SG
- Anna @annasyme AS
- Björn @bgruening BG
- Peter @pvanheus PvH

Afternoon Session

- Bérénice @bebatut BB
- Helena @erasche HR
- Saskia @shiltemann SH 
- Nicola @nsoranzo
- John @jmchilton
- Fotis  @fpsom FP
- Gildas @lecorguille 
- Delphine @Delphine-L
- Peter @pvanheus
- Subina @subinamehta SM
- Dan @blankenberg
- Pratik
- Frederik @frederikcoppens

# Training material

## Introduction

- SG/AS present their training that they've been doing, "hybrid training session", anna sits in a room and talks to a camera, everyone else spreads across the country. did RNA seq, genome assembly, spades, variant calling, metagenomics with GTN tutorial with soil metagenomics. It all went well! At one stage, 80 jobs running, 16 in queue. Across Aus + Malaysia.
- AS: if on larger scale could work as a "webinar", realtime? Roughly 100 people for each one.
- SG: to begin with they asked people to be local facilitators for things. trained them all how it works /  how it'll be run. flew them all to melbourne, even malaysian coordinator. Explained how it'll all work, train the trainer kind of thing. Everyone signed up for event brite thing, listed all of the local places they could do training,local facilitator handles computer/wifi issues and any issues. Simon watched the monitoring. There was a google doc where anyone could ask questions. No one need to sign up. AS: google doc can come back to questions and write something nice after the fact. People could ask loads of questions and everyone could respond inline, separate threads where people could respond and discuss.

## In the past months

- We've begun to write a training handbook to help people start to give training s and use the materials, we wrote checklists and recommendations. What simon did would fit really well there and we'd love to have their trainer story/philosphies. How they give their training. So many differences in the way of giving trainings, soit's great that we document this and help each other/insturctors think critically about how they give trainings and what is a good fit for them/their material/their style. @slugger70 @AnnaSyme
  - SM: We use jetstream for this, is it possible to use usegalaxy.eu for this in a similar way with their own accounts? Our jetstream instance occasionally crashes with >100 participants
  - BB: We have TIaaS
  - HR: EU is happy to support this, if you have extra space on jetstream you can just attach compute resources there to usegalaxy.eu and help process training jobs.
  - SM: Can we write a tour for a workflow?
  - HR/JC/BB: Bjoern will support this, we can find someone to help. HR: @polkhe can maybe test this?
  - Pratik: We need to get all workflows onto EU and working.
- @pvanheus shared https://twitter.com/H3ABioNet/status/1060484271863988224 so EU has a goal for their next training
- SG: Enis/Nuwan finishing work on Pulsar stuff, we can leverage this + possibly also prevention of re-running old jobs, especially for a training of this scale.
- Will SG/AS migrate their training materials? SG/AS: will take some time. SH: We can organise a cofest around this? Can get some help to migrate materials?
- How can we aggregate the feedback and maybe address some of it? Maybe some statistics over it, summarize this in a nice way for people. Do y'all think this is useful?
    - SG; we've discussed adding the form in melbourne, getting people to do it after isn't great. Comms people still love paper so it's an issue.
- We now have automatic translation.
    - There are some words which should never be translated such as "reads" and "mapping".
    - We're testing that now but it's available, you should try it if you speak another language.
    - SG: DaveC's comments from GOBLET, next one will be in Indonesia with Malaysians/Japanese groups, automatic translation would be incredibly helpful for them.
    - PvH: would be interesting for his context to do Arabic.
    - BB: A couple of japanese colleagues here at BioHackathon checked some, the translations were a bit rough. So we need to ensure that there is really good english and simplified sentences. Just take some tutorials and go through and see if we can improve the english at all. If there are terms, we should start a dictionary that should never be translated.
    - HR: We have google analytics data since a month thanks to @martenson, maybe this could let us prioritize.
    - BB: Japanese group will maintain some manually, they have a couple they want a HQ translation, so we can let them be manually curated if up to date. If they become three months out of date we will go back to automatic translations for those tutorials.


## Ongoing

- In Biohackathon
    - BB: Writing a proposal with Carpentries people to combine our trainings and do the EU wide training.
- Workflow testing
    - BB: Testing abunch on EU, to guaruntee that things are rnuning.
    - HR: 13/16 are passing, AU can just use our jenkins if they like
    - HR: hopefully have some planemo improvements soon that will make this more reliable
- Fairness assessment of training materials:
    - BB: Group in BH that's analysing "how can you assess fairness of materials". Some things are outside our control, (HR: or are possibly misassesed)
- We've implemented a Search via TeSS (for a part of the fairness assessment)
    - PvH: How does TeSS parse it? HR: json-ld schema.

## Future Directions

- More visibility of the training material
    - BB: Webhook to display training materials
- Tags and Curriculum
    - BB: What are best next steps. In the metadata could have next steps.
    - SG: Filter by tag, maybe could see trainings across categories, maybe from start to finish of analysis.
    - BB: If you want to import things, then we can import + hide them. If tools aren't on TS, we hide by default.
- More instructor visibility
  -  Training events will be shown on both hub + training materials (+EU)
  - GTN is more at level of institution, we want to show a more personal directory and give more visibility to the awesome instructors that make up our community
  - We’re doing a TOTM now which will be highlighted on EU + Org
- More instructor support (blog post framework, events feed on home page)
    - BB: Office hours program where experienced trainers help new people who show up/ask questions.
    - FP: In the carpentries it’s a good time to exchange ideas over best practices, things we encounter.
    - FP: In carpentries, we ask every single break “what did you like in the past hours / what didn’t you like”, asking for feedback. Helps identify weaknesses in either myself or in the material, maybe didn’t teach something well, or the material is lacking in that point. If the training ends on a high note, additionally biases the feedback.
    - SG: Train the trainers at GCC?
    - BB: Give more visibility like having instructor directory, but GTN is more for institutions but not individuals. With Dave we'll work on having a real list of instructors and thanking them and highlighting them.
    - BB: Also will embed an event list (@erasche/@tnabtaf)
    - PvH: can help with onboarding / growing the GTN community
    - SG: Repeat what SH/HR did in Melbourne, here's how to write materials/develop tools/etc, helped people get over the energy of activatiomn boundary.
    - BB: Idea of discussion meeting somewhat, to help new people answer some questions.
    - PvH: Carpentries has a mentoring programme.
    - BB: This takes quite some time committment, ours hopefully is less work for the trainers. BB meets with her mentees every two weeks regarding mentoring. For us, maybe we don't have enough time on our side and cannot ask GTN members for this. Maybe in the future if our community continues to grow

# Misc

- Gildas: Any recommendation to split the wf / multiple tours for different parts of workflow?
- BB: one tour : one workflow
- DL: I have been ask in conferences if there were any places were people could find or share workflows for specific subject, maybe we could link a repo of workflows linked to a specific subject, without having the whole tutorial for each of them ?
    - BG: our idea was to use this repo and similar once for this: https://github.com/galaxyproject/iwc

# Community

## Last Months

- GOBLET
    - BB: Not much feedback on GOBLET yet, hopefully we'll hear at next meeting. Maybe @tnabtaf can write a nice report from GOBLET.
- TIaaS
    - BB: it's working well
    - SG: We want to build a community of trainers, it could be good to leverage this, it would be nice to be informed of trainings run on our server.
- Advertisment Card:
    - BB: We made a nice card! No stickers yet.
- Next CoFest:
    - Thursday, 21st of Febuary

# Closing Notes

- We will move this slot to at least 1 hour later (could move 2)
- DB: Everything is great

**Comment by hrhotz** [comment]
@erasche Thank you very much for taking the notes/minutes yesterday

**Comment by bebatut** [comment]
Thanks @erasche for the notes and for everyone for their participation!
