### ISSUE TITLE
make pdf broken for slides

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/training-material#1095]
Today I tried generating pdf for some tutorial slides, and it failed.
It seems like [this line](https://github.com/galaxyproject/training-material/blob/master/Makefile#L179) removed the decktape binary before trying to use it to [call it later](https://github.com/galaxyproject/training-material/blob/master/Makefile#L160).
I'm not sure which way is the best to solve it: not removing `node_modules` or maybe reinstalling deps before pdf?

**Comment by nsoranzo** [comment]
Maybe `detached-serve` should depend on `install` instead of `clean`?
