### ISSUE TITLE
Solution boxes: only toggle on click on the plus/minus icon

### ISSUE THREAD

**Issue by shiltemann** [galaxyproject/training-material#1121]
Some tutorials require copy-pasting from the collapsible solution boxes, but the box automatically collapses again when you finish selecting text, would be nice if the collapse/expand action only happened when the plus/minus icon is clicked specifically, instead of a click anywhere in the box.

**Comment by erasche** [comment]
YES! I had multiple people unable to copy+paste text today, especially from admin tutorials where I've written the "final configuration", it's important.

**Comment by nsoranzo** [comment]
I also ran into this myself, but forgot to open the ticket, thanks @shiltemann.
