### ISSUE TITLE
List of the terms that should not be translated by Google translate

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#1141]
Now that we enable the automatic translation with Google Translate, we can work to improve it. We can say to Google Translate to not translate some terms. But we need a list of these terms. 

I started a list here

- bed
- DNA
- expression
- downstream
- Galaxy
- history
- mapping
- reads
- RNA
- single cell
- tool
- toolshed
- upstream
- wiggle
- workflow

If you have other ones, please comment here and I will add them to the list above.

Thanks a lot

**Comment by hrhotz** [comment]
RNA
upstream
downstream
tool
toolshed
wiggle 
bed
expression
single cell

**Comment by erasche** [comment]
Mapping

**Comment by abretaud** [comment]
For the Maker genome annotation tutorial, there is "Maker" which shouldn't be translated. (Actually Google is smart enough to leave it untranslated, but not everytime, depending on the context.)
I wonder if "maker" could be used in other tutorials, without referring to the software.

**Comment by bebatut** [comment]
We could also have a list at the level of the tutorial, in the metadata

**Comment by erasche** [comment]
Done!
