### ISSUE TITLE
Update training material metadata to "latest" bioschemas.org standards 

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/training-material#1147]
We spent a full day at the November 2018 GOBLET meeting discussing and amending the training related types in Bioschemas.  @njall guided the discussion and (I believe) would present the suggested revisions to the Bioschemas group at the 2018 Paris Biohackathon.

Once those types settle (which I expect to be shortly), we should update the current metadata for our training materials to conform to Bioschemas.

There is a similar issue ([#252](https://github.com/galaxyproject/galaxy-hub/issues/252)) in the Hub repo to bring the hub events listing up to date as well.

**Comment by njall** [comment]
We had a full day review of the Training Materials spec from GOBLET AGM at the Biohackathon this week. The review has made quite a few changes which need to be verified with the GOBLET gang; so it may be a month or so before we find a stable consensus. When we do I will a) notify and b) help with GTN material adoption. 
Here's the latest standard https://docs.google.com/spreadsheets/d/1h7S2ljMzbnNyLUmOnkRqDtB2CQ7yrTTUdNZt-d_Ez-o/edit#gid=1261485211

**Comment by tnabtaf** [comment]
Thanks @njall, for everything. I swear I may name a child after you yet. (I wonder which of my daughters would agree?)

**Comment by njall** [comment]
😆😆😆 

A beer next time I see you would be more than sufficient :P

**Comment by erasche** [comment]
We updated the the schema in #1264
