### ISSUE TITLE
GTN CoFest (21st of February)

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#1152]
![cofests](https://user-images.githubusercontent.com/1842467/46872640-fe9b1e00-ce34-11e8-8e4e-15d4a9a3cf9a.png)

We are organizing regular online CoFests (Collaboration/Contribution Fests) every 3 months on the 3rd Thursday for a day of the collaborative work on the training content.

**The next one will be on the 21st of February.**

We will coordinate via [Hangout](https://hangouts.google.com/hangouts/_/calendar/Z2FsYXh5dW5pZnJlaWJ1cmdAZ21haWwuY29t.7q82sbcupg0j59li0fqo9pots6) (drop-in channel we will keep open the whole day) and the [GTN Gitter channel](https://gitter.im/Galaxy-Training-Network/Lobby).

During the day, we will also have a call meeting with the GTN to discuss the recent changes and future directions (#1151)

---

*@bebatut, @shiltemann, and @erasche will be online between 9am and 6pm (CEST) but people from other time zones should feel welcome to continue even before/after. We will keep an eye on Gitter and GitHub*

**Comment by bebatut** [comment]
The next CoFest is in one month :smile:

**Comment by tnabtaf** [comment]
The next CoFest is in .... 2 days.  Please help get the word out.

**Comment by bebatut** [comment]
Thanks for all the participants!
The next CoFest will be in 3 months 😄
