### ISSUE TITLE
something (google form?) prevents closing training tabs

### ISSUE THREAD

**Issue by martenson** [galaxyproject/training-material#1197]
If I just open a page, scroll a bit and then try to close it, I get an alert. This can become very intrusive very quickly I fear.

![connecting_galaxy_to_a_compute_cluster](https://user-images.githubusercontent.com/1814954/51569558-ad0a2280-1e6a-11e9-8015-cab4f3c24cbe.png)

edit: this is from https://galaxyproject.github.io/training-material/topics/admin/tutorials/connect-to-compute-cluster/tutorial.html but it happens on other pages with the form too

**Comment by erasche** [comment]
Yeah, we have not yet found any solution for this. I guess it probably is "wait until form has scrolled into view" or "click to activate form" or something like that to prevent it from showing this dialog occasionally

**Comment by martenson** [comment]
It actually closes fine until I focus the form. Then it will always ask.

**Comment by erasche** [comment]
Then that sounds like it's behaving as well as it could? Or, any suggestions there?

**Comment by martenson** [comment]
I would like it to not do that until I actually change something in the form. The fact I pagedown'd there and it got focus shouldn't be enough. But I understand it is tricky.

**Comment by erasche** [comment]
> until you actually change something

yeah, that may be outside of our control, google is pretty aggressive.

> pagedown'd there

no, that shouldn't give it focus, hmm.

**Comment by hexylena** [comment]
Reopening this so I can close it finally :)
