### ISSUE TITLE
A tutorial explaining how to move from a basic installation to a production instance

### ISSUE THREAD

**Issue by oinizan** [galaxyproject/training-material#123]
In the admin corner, the next step after the introduction and before "Setting galaxy as a service" could be a tutorial explaining how to move from a dev-instance to a production instance.

**Comment by ValentinMarcon** [comment]
So we take it (Olivier & me)

**Comment by bgruening** [comment]
:)

**Comment by vdda** [comment]
a galaxy tours divided (at least 3 or 4 steps)

**Comment by erasche** [comment]
We now have a production galaxy installation with ansible which is the usegalaxy.* recommended way, and the way we do it ourselves.
