### ISSUE TITLE
Installing Jekyll: compatibility with Windows machines

### ISSUE THREAD

**Issue by Dries-B** [galaxyproject/training-material#1252]
While using a Windows computer, I have not been able to install Jekyll in the relevant section of [its tutorial](https://github.com/galaxyproject/training-material/blob/master/topics/contributing/tutorials/running-jekyll/tutorial.md#installation-of-the-requirements). Installing conda was possible, but GNU make is not available on Windows. Also, [Anaconda's make package](https://anaconda.org/anaconda/make) did not work for me.

Alternatives exist, such as those described in [this thread from StackOverflow](https://stackoverflow.com/questions/2532234/how-to-run-a-makefile-in-windows). Perhaps these extra steps for Windows users could be added to the tutorial?

In general, I would like to raise the question if training material primarily supports Linux operating systems or if others are also supported?

**Comment by bgruening** [comment]
@Dries-B thanks for reporting this! Indeed we have not tested this on Windows. We have tested it on Linux and OSX, this is what we all use. It's interesting to know that there is a need to run this training-material webserver on Windows. I would like to know more about this use-case. Is it for developing purpose or deploying the website locally?

Either way, if there are use-cases and a community that wants to use it under Windows we will try to get a Windows computer and write some documentation about it.

Sorry for the problems!

**Comment by Dries-B** [comment]
Thank you for your reply @bgruening! In this case, it was for a developing purpose. But besides my own user case, I wanted to know if Linux is generally required for developing Galaxy.

I understand it if this is the case; supporting Windows as well requires a whole extra set of tools being documented.

**Comment by bgruening** [comment]
Most of the Galaxy developers are on Linux and OSX. So both at very well supported. Windows is not supported as most of the tools that people use in Galaxy do also not run under Windows.
Thinks are getting better with the new developer mode in Windows-10 and we know a few reported cases that were able to get Galaxy running under Windows. But I would not recommend is at this time.

**Comment by erasche** [comment]
We have a report that one user got this working under windows 10?

I am not sure we can provide support for this, since none of the core contributors own a windows machine, and it will not be well tested going forward.

Sorry you had issues with it @Dries-B
