### ISSUE TITLE
Zipped files in example datasets

### ISSUE THREAD

**Issue by bedroesb** [galaxyproject/training-material#1260]
Following datasets are zipped: 
[https://zenodo.org/record/1184682#.XGFLn7r0lph](https://zenodo.org/record/1184682#.XGFLn7r0lph)
-> used in topics/statistics/tutorials/iwtomics/data-library.yaml
[https://zenodo.org/record/1255038#.XGFA9Lr0lpg](https://zenodo.org/record/1255038#.XGFA9Lr0lpg)
-> used in topics/transcriptomics/tutorials/goenrichment/data-library.yaml

A reupload was suggested by @bgruening  to use single files #1255

**Comment by dsobral** [comment]
Just submitted a pull request for goenrichment to use single files.

**Comment by bedroesb** [comment]
the iwtomics tutorial has a version with the unzipped files, I will do a PR soon with the new DOI
