### ISSUE TITLE
BWA version for HiCExplorer training

### ISSUE THREAD

**Issue by hrhotz** [galaxyproject/training-material#1284]
Hi

I am trying to run the HiCExplorer training on our local server, and I got confused about the version for BWA to be used. It says: "Map with BWA-MEM 0.8.0". Checking on usegalaxy.eu, this version points to a deprecated repository: https://toolshed.g2.bx.psu.edu/repository?repository_id=2ced7a5ecef47a27 (which I cannot install) 

Instead, I installed a newer (?) version:
https://toolshed.g2.bx.psu.edu/repository?repository_id=9ff2d127cd7ed6bc

but this one doesn't generate sam files and need some guessing how to set the options as written in the training material

Any help appreciated\
Thank you very much
Hans-Rudolf

**Comment by nsoranzo** [comment]
I think you installed the right tool and that the tutorial needs to be updated, the crs4 tool is definitely deprecated in favour of the devteam (actually iuc) one.

**Comment by hrhotz** [comment]
Thanks! I will try,and if successful, will update the training material

**Comment by hrhotz** [comment]
looks like this is a bigger issue: As far as I understand the new bwa wrapper always produces 'sorted' alignments, which cannot be used for HiCExplorer, can-they?

**Comment by bgruening** [comment]
The reason was and maybe still is, I'm unsure that we need to have unsorted BAM files or SAM files as output. The sorting of both BAM files needs to be exactly the same. One tool did not support it back then ...

**Comment by bgruening** [comment]
@joachimwolff ping.

@hrhotz I hesitated to ask which Galaxy version you are using ;) But a few versions back Galaxy gained support for a lot more BAM derivatives: https://github.com/galaxyproject/galaxy/blob/dev/config/datatypes_conf.xml.sample#L40

**Comment by bgruening** [comment]
This one: https://github.com/galaxyproject/tools-iuc/pull/1732/files

We migrated bowtie to use the --reorder option. BWA still does not support that, that's probably the reason we still use the SAM output.

You should be fine using bowtie or the older BWA-mem version with SAM output.

**Comment by hrhotz** [comment]
@bgruening it's Galaxy  18.05   I am not that far behind, at least for now... :(

**Comment by bgruening** [comment]
That should be enough I think, you should have the datatypes imho :)

**Comment by joachimwolff** [comment]
@hrhotz Using Bowtie version 2.3.4.2 as it is on our Galaxy server is alright too. Important is that the option `Reorder output to reflect order of the input file` which is hidden in the advanced options (`Do you want to tweak SAM/BAM Options?`) is set to `Yes`. 
I will update the training material soon.

**Comment by joachimwolff** [comment]
It is updated, closing this issue.
