### ISSUE TITLE
Add level  in tutorial

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#1289]
We could add an extra metadata to the tutorial: level, with 1 of the 3 terms: "Introductory" / "Intermediate" / "Advanced"

As suggested by @njall, it could map then to the bioschema property "skillLevel"

What do you think about it?

**Comment by foellmelanie** [comment]
I like the idea a lot as the only alternative I could imagine is that this information is added to the tutorial name (probably with not standardized wording) and then things get unclear and chaotic...

**Comment by erasche** [comment]
Done in #1298! :tada:
