### ISSUE TITLE
text in mothur-miseq-sop

### ISSUE THREAD

**Issue by pschloss** [galaxyproject/training-material#1293]
Hi there - I'm pretty uncomfortable with the amount of text you all took from my [MiSeq SOP](https://mothur.org/wiki/MiSeq_SOP) to generate your [mothur-miseq-sop training materials](https://galaxyproject.github.io/training-material/topics/metagenomics/tutorials/mothur-miseq-sop/tutorial.html). There are many examples throughout, but here is the first...

From yours...
> To that end, fresh feces from mice were collected on a daily basis for 365 days post weaning. During the first 150 days post weaning (dpw), nothing was done to our mice except allow them to eat, get fat, and be merry. We were curious whether the rapid change in weight observed during the first 10 dpw affected the stability microbiome compared to the microbiome observed between days 140 and 150. We will address this question in this tutorial using a combination of OTU, phylotype, and phylogenetic methods.

From mine...
> To that end we collected fresh feces from mice on a daily basis for 365 days post weaning (we're accepting applications). During the first 150 days post weaning (dpw), nothing was done to our mice except allow them to eat, get fat, and be merry. We were curious whether the rapid change in weight observed during the first 10 dpw affected the stability microbiome compared to the microbiome observed between days 140 and 150. We will address this question in this tutorial using a combination of OTU, phylotype, and phylogenetic methods.

Again, this is just one of many examples throughout your tutorial. Although I'm impressed with what you've done to add information, you either need to do a better job of indicating that the text is taken from my SOP (perhaps put it in callout boxes indicating it's a quote) or find your own words.

**Comment by shiltemann** [comment]
hi @pschloss I am so sorry! this was definitely meant as the Galaxy version of your SOP and I did copy your SOP as a starting point, but I guess it has evolved over time and diverged a bit and now is less clear that it is the same SOP. 

I tried to indicate this in the intro with the text "In this tutorial we will perform the Standard Operating Procedure (SOP) for MiSeq data, developed by the creators of the Mothur software package, the Schloss lab, within Galaxy" and link to your original version. I am more than happy to make this more clear by a different phrasing, or in any other way, please let me know your preferences.

apologies again, and thanks for a great tool and tutorial.

**Comment by pschloss** [comment]
Thanks for your attention to this. I think it would be best for you to delete the text and rewrite it using your own words.

**Comment by bgruening** [comment]
Hi @pschloss! Thanks for reaching out.
Just to make clear I understand your inquiry the very first sentence in this tutorial is not clear enough `In this tutorial we will perform the Standard Operating Procedure (SOP) for MiSeq data, developed by the creators of the Mothur software package, the Schloss lab, within Galaxy.`? Would it be enough to reformulate this sentence to make it more clear. In this case do you have any recommendation for us? Or do you want to have every single sentence acknowledged? 

There is also a contributors section for every single training and we would be happy to add you and your collegues to this.

**Comment by bgruening** [comment]
@pschloss please see https://github.com/galaxyproject/training-material/pull/1294. We should have included you at first hand, sorry for the oversight :(

**Comment by bgruening** [comment]
In #1294 we have hidden this tutorial from the index until we rewrite it.

We are sorry if that was interpreted as plagiarism, I'm sure that was no-one's intention. Thanks for contacting us, we will do better in the future.

**Comment by pschloss** [comment]
Thanks, @bgruening and @shiltemann and I understand that things happen. I'm thrilled to see other people take up mothur and develop their own tooling and instructional materials around the program. There's no real need to list me as a contributor since I haven't done anything for these particular materials once they've been edited.
