### ISSUE TITLE
Galaxy visualizations

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/training-material#13]
@carlfeberhard was so kind and contributed a list of visualization resources from the Galaxy wiki which are now stored here:

https://github.com/bgruening/training-material/tree/master/Dev-Corner/visualisations
- It would be nice to create a step-by-step tutorial, something like the planemo docs for visualisations here in this repo.
- We should write something about the BioJS cooperation and how we can include BioJS components into Galaxy

**Comment by lecorguille** [comment]
@shiltemann @yhoogstrate Maybe we should close this issue too 👍

**Comment by bgruening** [comment]
You guys rock!
