### ISSUE TITLE
Proposition: markdown tutorial files as unified tutorial/slides file - automatic slide generation

### ISSUE THREAD

**Issue by jibe-b** [galaxyproject/training-material#132]
# Context

Tutorials and slides **might** be redundant.

Markdown files can be converted to html+revealjs slides.

Markdown syntax is easier to modify than html+revealjs.
# Proposition

using [markdown_to_reveal](https://github.com/jibe-b/training-material/markdown_to_reveal) with a [template corresponding to the current tutorials](https://github.com/jibe-b/markdown_to_reveal/blob/5008c64624fe1daad65822e2c6034e7c5334332e/template.revealjs),  slides can be automatically generated from the tutorials in markdown, at the cost of adding some indication in the text.

First proposition is to keep only titles and any content highlighted with ** content **.
# Expected outcome

Tutorials will be easier to maintain (only one source file).

Features such as the possiblity to add logos, modify templates, print to pdf can be achieved easily.
# Limitations

For the moment, the template does not display the slides exactly as the hand edited files.
# Still under discussion

Better syntax than ** could be used, in particular choosing a template engine (such as [jinja](http://jinja.pocoo.org)). This would enable to standardise the implemented features and avoid having to develop and maintain our own parser. Pandoc filters could be nice too (in Haskel or _Python_).

The javascript slides library could be something other than revealjs (remark, spiffy, slidy, whatever).

The script used to automatically generate the slides could be a Makefile (for the simplicity of the command) or any other language.

Please give your idea, this is a proposition that would benefit from discussion.

**Comment by shiltemann** [comment]
Interesting, though for me usually presentation and hands-on tutorials are so separate I wouldn't generate the former from the latter, so that might be needlessly complex. To me it feels it would be harder to maintain two intertwined things in a single file than just two separate files, and it may not be that much to ask to create a separate markdown specifically meant for slide generation (but I'm curious how others feel about this)

I definitely like the idea of auto-generating slides from pure markdown files though. Trainers just worry about content, we can switch libraries in backend easily at any time. And template engine would be great, definitely.

** creates bold text in markdow right? that might be confusing, you couldn't use bold in parts not to be included in slides? (if I understand you correctly?) but this could be changed to something else you say? but if this something else is not valid markdown it might look weird in the regular markdown view (i.e. tutorial view) right? 

your first two links don't seem to be working, could you edit the comment so I can have a look?  :)

**Comment by friedue** [comment]
* I agree with Saskia that hands-out stuff and presentation are often only loosely connected - that being said, I also asked myself whether slides AND tutorials aren't a bit redundant. We could focus on providing markdown-based tutorials here and trainers will assemble the slides they need (I, personally, have some sort of deficiency that does not allow me to confidently present a presentation that I haven't created myself. It's not in the WHO catalogue of congenital disorders yet, but it should be.)
* auto-generating slides from simple markdown would be fantastic (two underscores also create bold in markdown), so then people that do not suffer from the same condition as myself can happily create presentations straight from the tutorials or, if we find that some topics indeed deserve more than just a tutorial, we could easily create the basis for slides without having to learn yet another language/tool

**Comment by shiltemann** [comment]
but ** still creates bold in the mardown view, so you would have certain paragraphs entirely in bold in the tutorial view? :P (or maybe I am not understanding correctly)

I would vote for a separate file for slides, but definitely go with the auto-generation from pure markdown and templating. Separate files also makes it easier to adapt the slides for people who want to give it their own spin (you are not alone in this ;P)

**Comment by jmchilton** [comment]
I'd prefer not to be too dogmatic about separate versus merged Markdown files. I see both sides and I don't think we need to pick one per se. If we develop a standard way to build two things from one piece of documentation - it doesn't prevent people from having separate pieces. I'd like to be able to generate both slides and longer form developer documentation (admittedly this isn't training material per se) from the slides. I was imaging sort of using something like speaker notes to expand on each topic for the documentation/tutorial variant of the Markdown. If some other sections don't make sense this way - then we can just have two files - there is still a lot to be gained from:
 - Having everything in one spot.
 - Having everything in Markdown.
 - Having a template set of slides that individual presenters can customize.
 - Having everything with licensing that allows for re-mixing.

**Comment by shiltemann** [comment]
sounds good. And true, useful just for just straight-up speaker notes in markdown slides as well, even if separate from tutorial.

**Comment by jibe-b** [comment]
Thanks for your answers.

I get the point that these are two different features.

Markdown to slides is the easiest and is already usable (though not yet user-friendly, i'll do it).

Then, having tutorial markdown files and markdown slides files separated or in one piece is more abstract. That would be beautiful @jmchilton if we do it this way. Having a script that takes either one slides+text file or two files (text and tutorial separated) would be simple.

Anyway, let's say that using ** was an attempt that will not be kept for the next step. A template engine would be more efficient and have less flaws.

**Comment by Slugger70** [comment]
Hackathon Group 2 - 

- We support the automatic generation of slides, but - the slides should be for context and the theory side of things. This requires a lot of manual time but is completely worth it.

- Much nicer to scroll through a continuous tutorial document than have it in slide form. So, automatic slide generation would be redundant.

**Comment by erasche** [comment]
Hi all, this has been done for some time so I'm closing it. Slides are done in one file, it is the markdown file that's converted to reveal.

**Comment by erasche** [comment]
Sorry, misread all of the description, and didn't fully address that in my closing comment.

In the intervening years it seems the community is quite happy with a split tutorial + slides setup.
