### ISSUE TITLE
Galaxy Admin Training long term plan?

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/training-material#135]
This repo includes an admin-corner for training material about administering Galaxy.  I'm wondering about the contents of this nd how it relates to the Galaxy Administrator Training being done (for the first time) in [Salt Lake in November 2016](https://wiki.galaxyproject.org/Events/AdminTraining2016), and in [Melbourne in February 2017](http://www.embl-abr.org.au/game2017/training-for-admin-workshop/).  These are multi-day events and aim to give participants a thorough understanding of how to run Galaxy servers.  

Salt Lake will be taught by @natefoo, @martenson, and @slugger70, and Melbourne by @natefoo, @slugger70, @afgane, and @fubar2.  (And there may be others as well.)

I'm not willing to tell them that they need to create training materials within this framework, but my hope is that once the dust settles, we (meaning possibly @tnabtaf) will import the training materials into this framework, and then use that in coming years.

Right now a primary concern is that we avoid creating tutorials with significant overlap with the material from these workshops.  On the plus side, anything created now, could be useful during those workshops.

Thoughts?

**Comment by martenson** [comment]
I agree that the most important thing now is to avoid overlap and prevent people from re-inventing wheel.

In **short-term** _ANY_ contribution to the training resources is very welcomed.

Currently, to my understanding, the best **long-term** approach is represented by https://github.com/galaxyproject/galaxy/pull/2283 (@remimarenco and @jmchilton) - i.e. docs and trainings living versioned with Galaxy in the same repo and being generated from ~same slides. 

Besides small differences (e.g. remark vs reveal) this approach is very similar to what is being done in this repo and should be compatible without much effort. 

The paragraphs above are only aimed at admins documentation that is heavy galaxy-version-specific. Scientific tutorials are a different beast I believe, and can be happily hosted separately.

**Comment by jmchilton** [comment]
I have nothing to add but I love the sound of my voice so I'll just say I agree completely with @martenson. The admin documentation on the wiki was admirable at times - but it staled quickly and proved to be too dependent on Galaxy version. Putting it with Galaxy means we will have documentation for the correct version - and it will also allow us to insist that updates (pull requests to Galaxy) that change admin-facing functionality also update the documentation at the same time. No more making a change mid development cycle and promising to go back and update the wiki just after the release.

As for https://github.com/galaxyproject/galaxy/pull/2283 - if this project here adopts markdown_to_reveal or a similar template for producing slides from Markdown - then I will happily adopt it for my contributions to Galaxy core and Planemo in these realms.

**Comment by jennaj** [comment]
@martenson I agree about scientific tutorials but is there a place for UI tutorials/extra help in this project? The same would apply - if something in the UI changes or is added, it would be added to the usage docs, all integrated. 

Maybe is a second-stage project?

**Comment by martenson** [comment]
@jennaj for UI tutorials we should heavily leverage https://github.com/galaxyproject/galaxy-tours

And yes, the tours should also change when Galaxy's features or DOM change.

**Comment by jennaj** [comment]
I guess I mean a smaller resolution from tours. Actual embedded help for functions/features. We have this content from prior Q&A, wiki, etc. Be easy to make a list of places to put the help and write up the text in a standardized way that is easy to edit. (?) Plus move the content is wiki-linked out directly into the UI. Goal - keep the user in Galaxy, no need to search wikis, immediate self-help.

**Comment by martenson** [comment]
@jennaj The idea is interesting but fairly unexplored - all projects has some sort of help resources available outside. It is also off-topic in this issue I think. Would you mind creating a separate issue for it?

**Comment by jennaj** [comment]
@martenson I'll just sit on it for now. Thanks!

**Comment by bgruening** [comment]
Just to add my few cents to this discussion. I also think that the primary Admin __documentation__ should be near to the code. I'm not sure about training material, aka slides and containers. I see this repo as collection and standardizing these material and linking out as many as you can to primary documentation if needed.

There is a small line between documentation and training, currently I'm also not able to draw this line.

More in general I think it involves motivational slides, small exercises, gamification which goes far beyond documentation - that one reason we pushed for tours so heavily.

Not sure if this post was helpful at all :(

**Comment by hrhotz** [comment]
I consider _admin training_ as a special case. Unlike other training, it is not about "how you do something". This should be covered by the _documentation_.
_Admin training_ is about "why you do it". It should motivate you to install and offer Galaxy, and it should help you make the right decisions. As a random example: the _documentation_ should explain how to set up a galaxy server with external authentication. The _admin training_ should talk about the advantages and disadvantages of external authentication.

**Comment by nsoranzo** [comment]
xref. #300

**Comment by nsoranzo** [comment]
Tutorials still to migrate:

- [ ] 00-intro
- [ ] 02-basic-server
- [ ] 03-production-basics
- [ ] 04-tool-shed
- [ ] 05-reference-genomes
- [ ] 06-extending-installation
- [ ] 08-upgrading-release
- [ ] 09-tool-versions
- [ ] 10-uwsgi
- [ ] 11-systemd-supervisor
- [ ] 13-external-auth
- [ ] 14-ansible
- [ ] 15-job-conf
- [ ] 17-heterogenous
- [ ] 18-clouds
- [ ] 19-storage
- [ ] 20-containerize
- [ ] 21-gie
- [ ] 22-troubleshooting
- [ ] 23-architecture

**Comment by martenson** [comment]
@afgane I think the answer is yes (plus you are in training-material repo now). For the gcc we will go with dagobah though (the last time?) I think.

**Comment by Slugger70** [comment]
Ok. Do we have a plan yet? Same as last year?

**Comment by martenson** [comment]
@Slugger70 similar I believe, I will go through and think about it in a few days and then call for discussion (unless it happens sooner), once we get the 18.05 Galaxy release out of the way.

**Comment by martenson** [comment]
The vast majority of admin topics have bene moved to the canonical training repo. https://training.galaxyproject.org/training-material/topics/admin/ Closing.
