### ISSUE TITLE
Incorrect alignment (left-shifted) of figure caption 

### ISSUE THREAD

**Issue by anuprulez** [galaxyproject/training-material#1384]
![tm_issue](https://user-images.githubusercontent.com/3022518/57857014-88a5cd80-77ee-11e9-9790-ef255b47a8a2.png)

The caption below (`Figure 4: The visualisation ...`) the figure is left-shifted. It should be in the middle. This issue is probably in all of the training materials which use captions for figures.

Example training materials:
https://training.galaxyproject.org/training-material/topics/statistics/tutorials/age-prediction-with-ml/tutorial.html

https://training.galaxyproject.org/training-material/topics/variant-analysis/tutorials/mapping-by-sequencing/tutorial.html

**Comment by erasche** [comment]
I justified the captions in a previous commit which looks better for longer captions and is more normal for papers/reports. Lines are left justified if they are not long enough to cover a full line, in this case the short caption causes this.

**Comment by erasche** [comment]
If there is no further discussion, maybe we close this?
