### ISSUE TITLE
Include search more prominently

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/training-material#1389]
@wm75 suggested in chat that we should show the search more prominently, maybe with a search icon or box in the header.

- We can collapse the training logo to just the icon, and not with the title, like GitHub does
- We can have a search icon that expands into a search box

**Comment by nsoranzo** [comment]
- Move "Input Datasets" to the Overview

**Comment by erasche** [comment]
Ooh yea, nice suggestion!

**Comment by erasche** [comment]
Could probably move galaxy instances and associated slides there too?

**Comment by jennaj** [comment]
all good ideas. searching these is a bit difficult -- I end up using just regular google, seems the fastest way right now (but doesn't find galaxy instances -- isn't exposed text). thanks for thinking about options!

**Comment by hexylena** [comment]
Fixed in #1943
