### ISSUE TITLE
fail CI on PRs that are over certain size

### ISSUE THREAD

**Issue by martenson** [galaxyproject/training-material#1432]
this could help to prevent this repository from rampant growth

**Comment by erasche** [comment]
Any reason this came up?

**Comment by martenson** [comment]
Nothing particular, just an idea we had when discussing long cloning and
pulling times.

**Comment by hexylena** [comment]
Doing a shallow clone has helped *immensely* during GHA. People should do this by default, unless they have some reason not to.

**Comment by martenson** [comment]
thanks @hexylena !
