### ISSUE TITLE
Pulsar tutorial issues

### ISSUE THREAD

**Issue by erasche** [galaxyproject/training-material#1458]
- [x] systemd is missing, requires https://github.com/galaxyproject/ansible-pulsar/issues/5
- [x] In the "Starting Pulsar" and "Daemonizing" we are starting Pulsar by hand, why is that not done as part of the Ansible role (or playbook)? Then trainees can log in on the Pulsar machine just to look at the logs
- [x] In the "Configure Galaxy" hands-on, it is not specified which `job_conf.xml` file should be modified, the one in `/srv/galaxy/config/` or the one in `~/ansible/files/galaxy/config/` ? The second looks a better choice, but in any case we need to specify how to restart Galaxy (point 3), i.e. with supervisor or with `ansible-playbook -i hosts galaxy.yml` respectively.

**Comment by nsoranzo** [comment]
I've hijacked this issue to report other 2 possible problems in the Pulsar tutorial.

**Comment by erasche** [comment]
Sounds good

**Comment by nsoranzo** [comment]
Addressed in https://github.com/galaxyproject/training-material/pull/1445
