### ISSUE TITLE
Generic introduction to Galaxy

### ISSUE THREAD

**Issue by chrisbarnettster** [galaxyproject/training-material#1465]
A GTN intro that showcases Galaxy and is not bio-specific. Should work for climate, compchem and all other communities. 

Specifically avoid too specific tools. 

@yvanlebras @annefou

**Comment by annefou** [comment]
And showing what is the Galaxy ecosystem rather than presenting Galaxy as a GUI only.

**Comment by nagoue** [comment]
Should consider what is Galaxy from user, developer and admin point of views

**Comment by yvanlebras** [comment]
All right! Let's rock guys! I am thinking about using the [https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101/tutorial.html](Galaxy 101 tutorial) as a basis, and instead of using bed files, genomic oriented things, using only generic text tools, notably for the join step

**Comment by yvanlebras** [comment]
> 
> 
> Should consider what is Galaxy from user, developer and admin point of views

In a forst approach, I think we can focus on user

**Comment by annefou** [comment]
I would really like to have a short into (a few slides) on what is Galaxy (from a general point of view), explaining Galaxy ecosystem.

**Comment by nsoranzo** [comment]
@annefou You can add them to https://training.galaxyproject.org/training-material/topics/introduction/slides/introduction.html or in a separate slide deck.

**Comment by yvanlebras** [comment]
> 
> 
> I would really like to have a short into (a few slides) on what is Galaxy (from a general point of view), explaining Galaxy ecosystem.

it already exists ;) https://training.galaxyproject.org/training-material/topics/introduction/slides/introduction.html

**Comment by annefou** [comment]
Ok but if this is what is Galaxy then we can forget the climate community. From my point of view these slides are not showing what is the Galaxy ecosystem.

**Comment by yvanlebras** [comment]
It's quite agnostic no ? What do you mean ?

**Comment by tnabtaf** [comment]
Some links:

* [Community Statistics Page](https://galaxyproject.org/galaxy-project/statistics/)
* [Backing stats in Google Spreadsheets](https://drive.google.com/drive/folders/1wMGpCDlIn43eV6wn_NBRENXDODojgE3Z)
  * This is a work in process.  Readable by all; for Write access, please send your Google ID to @tnabtaf.
* [GalaxyProject.eu's Stats page](https://stats.galaxyproject.eu/)
* [OpenHUB's project stats page](https://www.openhub.net/p/galaxybx/) - focuses on code.

**Comment by olanag1** [comment]
Some ideas from CoFest, that may pass to the final presentation :

There is a place for everyone to join the galaxy community

1. End-User
benefits :
- a user interface to execute the analysis
- support from the community
- history of complex multi-staged analysis
contributions : 
- training support
- providing your methods and tools to the community
2. Admin
benefits :
- help others to execute tasks
contributions : 
- support users to install particular tools 
-maintain the infrastructure
3. Developers  
benefits :
- active community exchange 
- visibility (quoting & citations): you will be better cited
- as it's opensource, enhance collaborative work 
- more powerful results
contributions : 
- make a more robust code in collaboration with others
- maintenance power 
- the usefulness of your work: has users behind
- get feedback 
- with git it is easy to improve the code and add more advanced features

There is a place for everyone. You can easily use galaxy and contribute to the growing galaxy community.

**Comment by chrisbarnettster** [comment]
WIP PR #1473

**Comment by chrisbarnettster** [comment]
Great idea from @MoHeydarian - use a well known dataset such as mtcars.

**Comment by yvanlebras** [comment]
I like it! But ITM I was thinking about proposing 2 possibilities:
- "classical":  using a defined dataset, and using a well known one is a great idea
- "new way": using a BYOD concept, asking to trainees to come with there own data BUT with a particular "content", something matching a Galaxy workflow... For example, asking to trainees to come with 2 tabular files with a common id column so we can work on joining these 2 files and applying text manipulation  / filter operation on it...

**Comment by nagoue** [comment]
Iris dataset can be used in training:
http://archive.ics.uci.edu/ml/datasets/Iris => we have to make a copy to zenodo (no in it yet)
it may be better than mtcars as it is a bit bigger. We can use it for text manipulation and data vizualisation.

**Comment by yvanlebras** [comment]
Ecology compatible and the name of my boat, I like it like it ;)

**Comment by annefou** [comment]
@nagoue @yvanlebras @chrisbarnettster anyone interested in working on this issue for the next Galaxy Training Network day? (12th September 2019, see https://galaxyproject.org/events/2019-09-gtn/)

**Comment by nagoue** [comment]
Yeap, good for me

**Comment by erasche** [comment]
Done! :tada: thanks everyone!
