### ISSUE TITLE
Automate generation of screenshots

### ISSUE THREAD

**Issue by MoHeydarian** [galaxyproject/training-material#1469]
Screenshots are great for teaching GTN tutorials. I have noticed users struggle to populate accurate parameters on tool forms when only text descriptions of parameters are available. 

Proposing an automated pipeline that is triggered to generate screenshots of the UI/tool forms in regular intervals or with each release. Interactive tours can be used to generate the "script" but will need to be coupled with the capability to capture the screenshot. 

An alternative idea from @bebatut is to render an image of a correctly populated tool form.

**Comment by MoHeydarian** [comment]
ping @guerler @dannon @astrovsky01

**Comment by jxtx** [comment]
@astrovsky01 was just looking at https://html2canvas.hertzen.com/ which could be used to do this entirely in the browser -- from the tour code we could trigger taking a snapshot of the browser and dump to a png.

**Comment by dannon** [comment]
Another option might be to use the testing framework w/ selenium's screenshot stuff that's already being used there.  We have tests that run tours; we'd just need to snapshot each one and then push those out.

**Comment by erasche** [comment]
Hi all. I'm afraid this is not so interesting to us because it is an accessibility issue. The training website is currently relatively accessible and this would be a regression for us. Maybe once there are re-usable vue components we can just embed those if you *really* need it :)

**Comment by hexylena** [comment]
Fixed in #2271, we will keep the textual descriptions but for selected screenshots deemed important, we have something to automate it. it's finally happening!
