### ISSUE TITLE
Some problems with Annotation tutorial: details and status here

### ISSUE THREAD

**Issue by AnnaSyme** [galaxyproject/training-material#1470]
Tutorial:
https://training.galaxyproject.org/training-material/topics/genome-annotation/tutorials/genome-annotation/tutorial.html

Issue 1/ Interproscan does not work (using in usegalaxy.eu). Issue submitted to tools-iuc:
https://github.com/galaxyproject/tools-iuc/issues/2482

**Comment by AnnaSyme** [comment]
Issue 2/ On opening the published worfklow in usegalaxy.eu, in the workflow grid view, the message pops up with: Step 9: NCBI BLAST+ blastp
An invalid option was selected for database, u'swissprot_28-09-2014', please verify. Using default: 'swissprot_2018-01-22'.

**Comment by AnnaSyme** [comment]
Issue 4/ Also relating to the published workflow: 

I'm a bit confused about where we are sending files. We have an original protein fasta (440 seqs). We also have lists of which of these proteins match to swissprot (89 seqs) and which don't (351 seqs). After finding these unannotated sequences, the tutorial says "This file will be the input for more detailed analysis", and then lists interproscan, wolfpsort, tmhmm and blast2go.  I thought this would mean the unannotated protein fasta file (351 seqs) would go to all these tools. However, is it the annotated seqs that we use for the next steps? The published workflow shows that interproscan takes in the entire protein file (440 seqs), wolfpsort and tmhmm take in the matched seqs (89 seqs), and blast2go also takes in the entire protein set (440 sequs in its blast xml format). 


 I thought we would send the unmatched seqs to all of interproscan, wolfpsort, and tmhmm

I'm assuming that means we use these unannotated proteins (351 seqs) for further analysis (interproscan etc.) which are listed next. However the published workflow shows the entire original protein file (440 sequences) is used. Should we use the smaller file (the 351 seqs) ?

**Comment by AnnaSyme** [comment]
Issue 5/ WoLP Psort

In the workflow, I think we need to change "organism" from Animal to Fungi.

**Comment by AnnaSyme** [comment]
Issue 6/ TMHMM 2.0

- current version is 0.0.16 -- this does not work. error is:  Failed to activate conda environment! Error was:
Not a conda environment: /usr/local/tools/_conda/envs/__tmhmm2@_uv_

However: 
- workflow version is 0.0.13 -- this works. 

This issue also added to tools-iuc: galaxyproject/tools-iuc#2482

**Comment by AnnaSyme** [comment]
Issue 7/ Additional data file: genbank file of Streptomyces. 

This file is here:

Does it need to be added to zenodo, and then a zenodo link added to the data-library.yaml.

**Comment by AnnaSyme** [comment]
Issue 7/ Additional data file: genbank file of Streptomyces. 

This file is here: https://github.com/galaxyproject/training-material/tree/master/topics/genome-annotation/input_data

Does it need to be added to zenodo, and then a zenodo link added to the data-library.yaml.

**Comment by hexylena** [comment]
These are all very valid issues. We've disabled the tutorial and will close this now as it is unlikely they get solved within this tutorial. We (Anthony, myself) will hopefully work on similar in the coming years and rewrite completely new tutorials following current best practices, while still using some of these annotation standards like interpro/tmhmm/etc.
