### ISSUE TITLE
Analyze unaligned ncRNAs

### ISSUE THREAD

**Issue by eggzilla** [galaxyproject/training-material#1471]
We will add a new training based on the 'Analyze unaligned ncRNAs' workflow.
Anyone is welcome to join :-)
See here for the workflow:
https://github.com/bgruening/galaxy-rna-workbench/blob/master/rna-workbench-workflow/rnateam.workflow.analyse_unaligned_ncrnas.ga

**Comment by eggzilla** [comment]
Corresponding pull request can be found here:
https://github.com/galaxyproject/training-material/pull/1501

**Comment by erasche** [comment]
Will be solved in the linked PR
