### ISSUE TITLE
Discussion: Out of sync: tools, tutorials, workflows

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/training-material#1483]
https://github.com/galaxyproject/training-material/pull/1480 initiated some discussion between @shiltemann and myself. That PR updates for the newest version of the tool's interface, but:
- that assumes newest version in all servers. (UseGalaxy.* plans help with this a bit but not completely.)
- and the workflow isn't updated / often forgotten (and sometimes it is a big request for a small/helpful change.)

*If there is a nice way*, to me it maybe makes more sense to pin tutorials to specific versions of tools? Then we have a tutorial + wf (+server) all in sync for at least that version. And when we go to update, it's somehow more mandatory to update the workflow since we need to know it works on that version (with the testing.)

I proposed in the past that maybe we could offer a way to say "I'm running this on server X" and then just create links in the tutorial going to the right tool + version on this server. That was one idea. Alternatively maybe we also include version info straight in tuto and teach users how to switch to that version?

**Comment by erasche** [comment]
Some discussion with @jmchilton, @bebatut, @shiltemann during the BioHackathon about a theoretical future where the training is part of the workflow in a single document.
