### ISSUE TITLE
GTN CoFest (12th of September)

### ISSUE THREAD

**Issue by shiltemann** [galaxyproject/training-material#1491]
![cofests](https://user-images.githubusercontent.com/1842467/46872640-fe9b1e00-ce34-11e8-8e4e-15d4a9a3cf9a.png)

We are organizing every 3 months one day dedicated to the community: collaborative work on the training content but also calls.

**The next one will be on the 12th of September.**

Anyone who would like to contribute, learn how to contribute to the Galaxy Training Material or just catch up with the community is very welcome to join.

We will coordinate via [Hangout](https://hangouts.google.com/hangouts/_/calendar/Z2FsYXh5dW5pZnJlaWJ1cmdAZ21haWwuY29t.6nungcj20l9qh2uicb8h5ivpds) (drop-in channel we will keep open the whole day) and the [GTN Gitter channel](https://gitter.im/Galaxy-Training-Network/Lobby).

During the day, we will also have community call meeting with the GTN to share news about Galaxy and Training (https://github.com/galaxyproject/training-material/issues/1492). Everyone is very welcome to join these calls.

---

*@bebatut, @shiltemann, and @erasche will be online between 8am and 6pm (CEST) but people from other time zones should feel welcome to continue even before/after. We will keep an eye on Gitter and GitHub*

**Comment by bebatut** [comment]
Quick reminder. The CoFest is on Thursday!
