### ISSUE TITLE
GTN Meeting (12th of September)

### ISSUE THREAD

**Issue by shiltemann** [galaxyproject/training-material#1492]
The next meeting of the GTN will take place during the next CoFest (#1491), on Thursday, the 12th of September. The idea of these meeting is to share news about Galaxy and Training, but also just talk together.

To accommodate different time zones and schedules, there will be 2 calls (with similar discussions) at [8am (UTC + 2)](https://arewemeetingyet.com/Berlin/2019-09-12/08:00/GTN%20meeting) and [4pm (UTC + 2)](https://arewemeetingyet.com/Berlin/2019-09-12/16:00/GTN%20meeting) via [Hangout](https://hangouts.google.com/hangouts/_/calendar/Z2FsYXh5dW5pZnJlaWJ1cmdAZ21haWwuY29t.6nungcj20l9qh2uicb8h5ivpds).

Agenda and minutes document in [this Google Doc](https://docs.google.com/document/d/1BA4TYe5snFd5866ZeF3OtuV9quhpvvfrIMn6qD2qxl0/edit?usp=sharing), please feel free to suggest your agenda items here if there is anything you would like to discuss or learn about!

**Comment by bebatut** [comment]
Quick reminder. The meetings are on Thursday!

If you have time, it would be nice to see maintainers of the different topics (@galaxyproject/training). We would like at the end of the calls to go through open PR and issues
