### ISSUE TITLE
Moving tutorials in galaxyproject

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/training-material#150]
I would like to start moving tutorials into a dedicated repo within galaxyproject. I was thinking of proceeding in the following sequence:

- [ ] Galaxy 101
- [ ] NGS-QC and mapping
- [ ] Variant analysis
- [ ] RNA seq
- [ ] ChIP-seq
- [ ] Methyl-Seq

I will also start making nicely styled webpages for these by placing content into /docs folder (to have something along these lines http://nekrut.github.io/BMMB554).

Objections? Ideas?

**Comment by nsoranzo** [comment]
I think that the idea was to move the whole `training-material` repository under galaxyproject at some point, @bgruening?

**Comment by martenson** [comment]
Adopting whole repo preserves all the links, that were created as it automatically and properly redirects and even keeps clones and forks working. I would recommend to use it.

**Comment by nekrut** [comment]
So what I'll do is create a fork, mess with it on my own so you will be able to see what is happening.

**Comment by bgruening** [comment]
Please fork and make your changes we will move this repo entirely to galaxyproject if we all feel confident about the guidelines and the content.

**Comment by martenson** [comment]
@bgruening I talked to @nekrut and it seems the goal is to have two categories on the 'published materials' site after we move the repo, roughly something like:
- vetted high quality finished materials that will be highly recommended by the project
- everything else

**Comment by bgruening** [comment]
Sounds good, let's schedule a small hangout on Friday when I'm back. I talked with Dannon a little bit and it would also nice to hook that up into the generated website from @dannon. We just need to figure out who is generating when the website from the markdown files here.

**Comment by bebatut** [comment]
I started to work on using Jekyll for the templating of the training and the use of variables. So webpages can be automatically generated.
A draft can be found here: http://bebatut.fr/training-material/ (only RNA seq is working in the draft...). 
I will soon open a PR about this to explain my ideas

**Comment by bgruening** [comment]
I will close this. Feel free to reopen if appropriate.
