### ISSUE TITLE
equation writing 

### ISSUE THREAD

**Issue by sbenateau** [galaxyproject/training-material#1517]
I would like to know if it is possible to write equations (for example like in latex).
I guess include an image would work but it requires to generate images of the right size and would be less general.
Thank you!

**Comment by nsoranzo** [comment]
We could use [MathJax](https://www.mathjax.org/).

**Comment by shiltemann** [comment]
we already support this (using MathJax), see [this tutorial](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/create-new-tutorial-content/tutorial.html#writing-mathematical-expressions) for more info :)

**Comment by sbenateau** [comment]
Thank you so much !
