### ISSUE TITLE
use of featureCounts in the scRNA tutorial

### ISSUE THREAD

**Issue by markdunning** [galaxyproject/training-material#1524]
Hi,

I am working through the single-cell tutorial, but am a bit confused by the featureCounts step

https://galaxyproject.github.io/training-material/topics/transcriptomics/tutorials/scrna_preprocessing/tutorial.html#quantification

It suggests that the featureCounts tool should produce a bam file, but yet every other time I have used featureCounts it gives a table of counts. Is there another featureCounts tool somewhere that I should be using? I am on usegalaxy.eu and this is the tool

https://usegalaxy.eu/tool_runner?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Ffeaturecounts%2Ffeaturecounts%2F1.6.4

![Screenshot from 2019-07-24 10-04-21](https://user-images.githubusercontent.com/3796277/61780455-76519c80-adfa-11e9-903a-6c94acfcabe0.png)

Regards,

**Comment by mtekman** [comment]
Hi Mark, thanks for checking out the tutorial

The BAM alignment file given by FeatureCounts is given under the *Advanced Options*. Please check  `Yes` for “Annotates the alignment file with ‘XS:Z:’-tags to described per read or read-pair the corresponding assigned feature(s).”

Please also make sure to tick the other options given in the last bulleted section of first step of the *Hands-On*

**Comment by markdunning** [comment]
Thanks for the quick response. Yes I must have missed that option :/

Thanks for a great tutorial!

Best wishes,
