### ISSUE TITLE
Assembly: feedback from the embedded feedback form

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#1577]
@galaxyproject/training-assembly 

Notes for all tutorials in this topic (16.09.2019):

![index](https://user-images.githubusercontent.com/1842467/64971036-46c58a80-d8a7-11e9-823c-f16e4cc4bf8f.png)

Details per tutorials:

- **De Bruijn Graph Assembly**
  - Pro:
    - Everything works with provided data and the scale is good for use in class (*19/09/2018*)
    - Easy to follow (*25/03/2019*)
  - Con:
    - Could you provide the fragment size separating the paired ends? It would also be nice to have more info for instructors about the genome for doing additional exercises based on the assemblies. (*19/09/2018*)

- **Introduction to Genome Assembly**
  - Pro:
    - This is a great tutorial. Saved me a lot of time. Well done and thank you. (*13/03/2019*)
    - the real data analysis (*03/06/2019*)
    - all in this tutorial are so usefull (*12/07/2019*)
    - on galaxy portal lot of assembler are available, but most of the scaffolders are not working or unavailable. (*13/09/2019*)
  - Con:
    - Similar tutorials for other bioinformatics exercise. If all tutorials on the web were this easy to follow everybody would know what they're doing. :) (*13/03/2019*)
    - provide links to the tool side by side (*03/06/2019*)
    - i dont know (*12/07/2019*)
    - need good genome ascaffolder or soapdenovo tool (*13/09/2019*)

- **Unicycler Assembly**
  - Pro:
    - THE INFO USED (*08/02/2019*)
    - easy to follow, step by step (*16/04/2019*)
  - Con:
    - THE WAY OF EXPLAINING (*08/02/2019*)

**Comment by hexylena** [comment]
Now moved here: https://training.galaxyproject.org/feedback
