### ISSUE TITLE
Contributing: feedback from the embedded feedback form

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#1578]
@galaxyproject/training-contributing 

Notes for all tutorials in this topic (16.09.2019):

![index](https://user-images.githubusercontent.com/1842467/64971329-d408df00-d8a7-11e9-87bd-ed284752009e.png)

Details per tutorials:

- **Contributing with GitHub via command-line**
  - Pro:
    - It's easy to understand (*26/08/2019*)
    - Every thing was great especially the graphics. Thanks for all the help!! (*30/08/2019*)
  - Con:
    - More diagrams (*26/08/2019*)
    - Every thing is fine and up to date though I am not an expert! (*30/08/2019*)

- **Creating a new tutorial**
  - Pro:
    - the option to automatically extract all steps of my workflow instead of typing them all is sooooo increadibly helpful!!! (*16/02/2019*)

- **Including a new topic**

- **Running the Galaxy Training material website locally**
  - Pro:
    - Very very straightforward ! (*22/10/2018*)
    - Clear wording. (*08/02/2019*)
    - Clearly explained.  (*19/06/2019*)
  - Con:
    - Nothing... (*22/10/2018*)
    - As a Windows user, I was not able to install requirements successfully. (*08/02/2019*)
    - In the first step (install requirements) - does there need to be an extra step before step 5, that says "conda activate galaxy_training_material" ?  (*19/06/2019*)

**Comment by hexylena** [comment]
Now moved here: https://training.galaxyproject.org/feedback
