### ISSUE TITLE
Data-manipulation: feedback from the embedded feedback form

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#1579]
@galaxyproject/training-galaxy-data-manipulation 

Notes for all tutorials in this topic (16.09.2019):

![index](https://user-images.githubusercontent.com/1842467/64971636-45e12880-d8a8-11e9-9d74-fd45fde53eec.png)

Details per tutorials:
- **Collections: Rule Based Uploader**

- **Collections: Using dataset collection**
  - Pro:
    - Facilitative (*09/08/2019*)

**Comment by jennaj** [comment]
cc @jmchilton
