### ISSUE TITLE
Metabolomics: feedback from the embedded feedback form

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#1585]
@galaxyproject/training-metabolomics 

Notes for all tutorials in this topic (16.09.2019):

![index](https://user-images.githubusercontent.com/1842467/64973394-3b745e00-d8ab-11e9-9782-1d5009a7b4ac.png)

Details per tutorials:
- **Mass spectrometry: LC-MS analysis**
  - Pro:
    - This format is much more approachable (esp. for hands-on) than the PDFs at W4M.org. I'm not saying that the PDFs are not helpful or informative (they are), but this is much more suitable for walking through the steps. Also, because it is a "living document", you can improve it in place, and we do not need to look for an updated document somewhere else.  We can always link to one URL when referencing the tutorial. (*06/07/2019*)
  - Con:
    - Document every axis of every panel of Quality_Metrics_figure.pdf, e.g., what are deciles and missing values in the bottom left panel? Put into the description the rationale behind the parameters chosen in Data Filtering (you presented it wonderfully verbally, but I don't find it written into the tutorial). (*06/07/2019*)

**Comment by lecorguille** [comment]
The graph doesn’t isn’t the metabolomics one :)

But thanks for this report and your amazing job around the GTN

Gildas

----------------------------------------------------------------------------------------------------------------------------
Gildas Le Corguillé - Bioinformatician/Bioanalyste

Plateform ABiMS (Analyses and Bioinformatics for Marine Science): http://abims.sb-roscoff.fr <http://abims.sb-roscoff.fr/>

Co-leader of the IFB Core Cluster: https://www.france-bioinformatique.fr/en/cluster <https://www.france-bioinformatique.fr/fr/cluster>

Member of the Workflow4Metabolomics project: http://workflow4metabolomics.org <http://workflow4metabolomics.org/>

Station Biologique de Roscoff
Sorbonne Université / CNRS
Place Georges Teissier 29680 Roscoff FRANCE
tel: +33 2 98 29 23 81
----------------------------------------------------------------------------------------------------------------------------

**Comment by melpetera** [comment]
Thank you for the feedback. Suggestions have been taken into account in the last update of this tutorial :)

**Comment by lecorguille** [comment]
xref: https://github.com/galaxyproject/training-material/pull/1855

Dear GTN mentors, should we close this issue or let it open?

**Comment by hexylena** [comment]
Now moved here. https://training.galaxyproject.org/feedback
