### ISSUE TITLE
Metagenomics: feedback from the embedded feedback form

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#1586]
@galaxyproject/training-metagenomics 

Notes for all tutorials in this topic (16.09.2019):

![index](https://user-images.githubusercontent.com/1842467/64973466-5c3cb380-d8ab-11e9-9494-82a2eed359a4.png)

Details per tutorials:
- **16S Microbial Analysis with Mothur**
  - Pro:
    - The data clean-up was thoroughly covered. Every step was well explained (*17/09/2018*)
    - Clarity and background details (*19/10/2018*)
    - How  simply and clearly the steps have been put (*21/02/2019*)
    - Clear explanations of the tools; helpful workflow; I think the Hand On opportunities and prompt questions are really beneficial. (*12/03/2019*)
  - Con:
    - Using the mock community. More light on rationale (*17/09/2018*)
    - Need a step on how to remove barcodes, adapters and primers from raw FASTAq sequences (*19/10/2018*)
    - Descriptions of which files to use were not always clear enough for me to determine which one to use. The justification of some selections for tool options could be expanded on, or additional links to papers noted where appropriate. (*12/03/2019*)

- **16S Microbial Analysis with mothur**
  - Pro:
    - Step-by-step guidance to complete tutorial, comprehensive and easy to understand and follow along (*09/03/2019*)
    - that it went right from the beginning (fastq) with explanations at each point of what I was looking at (*10/03/2019*)
    - Everything (*24/04/2019*)
    - easy step by step guide to analysing 16s rRNA data (*03/05/2019*)
  - Con:
    - the galaxy biom1 file output does not open successfully in Phinch, preventing the final visualisation (*10/03/2019*)
    - When you say skip mock test if time retrain, skip whole section to OTU step? More information of the choice of databases used and do we use all etc? (*03/05/2019*)

- **16S Microbial Analysis with mothur (extended)**
  - Pro:
    - Detail (*31/05/2019*)
    - easy reading (*31/05/2019*)
    - step-wise and very useful content to the beginners (*13/06/2019*)
    - Explainaton (*29/08/2019*)
    -   (*05/09/2019*)
  - Con:
    - Flexibility of the analysis depending on the type of samples, replicates, etc (*31/05/2019*)
    - troubleshooting  (*31/05/2019*)
    - Add one or two exercise to the learners by providing  few fasta sequences (10 or less) (*13/06/2019*)
    - The mouse.dpw.metadata is not in the downloads at start nor linked at bottom. Please add to tutorial. (*02/08/2019*)
    - Functional metagenomics (*29/08/2019*)

- **16S Microbial Analysis with mothur (short)**

  - Con:
    - At the Phinch step: “metadata”: the mouse.dpw.metadata file you uploaded at the start of this tutorial  I have looked up in the tutorial, but could not find a link to that metadata file. Could you provide a URL where to get it? (*08/07/2019*)
    - The Krona plot - this appears to be of all samples. Would be good to per sample. Might not be possible with Phinch. As for Phinch, that is no longer web accessible but standalone and has dropped functionality. (*02/08/2019*)

- **Analyses of metagenomics data - The global picture**
  - Pro:
    - Krona (*29/10/2018*)
    - Some instructions were not clear at all, please be more specific as i encounter errors very likely despite following the steps (*30/10/2018*)
    - The overview of all the tools available. (*14/11/2018*)
    - clear step by step module (*14/11/2018*)
    - step by step very well described (*13/04/2019*)
    - Taught me something new (*05/05/2019*)
    - veryl clear and easy to follow (*09/06/2019*)
    - Visualization Feature (*09/09/2019*)
  - Con:
    - It needs to be updated, some returns error and some is missing. Be more detail and specific (*29/10/2018*)
    - Please review the protocol and revise some segments  (*30/10/2018*)
    - The time for the processes on Galaxy. (*14/11/2018*)
    - data analysis with OTU / phylotype (*13/04/2019*)
    - On the version of Galaxy that I use (usegalaxy.com), MetaPhlAN2  is not available (*05/05/2019*)
    - more details about output files on each steps (*09/06/2019*)
    - 1) Hands-on: Visualization of the community structure with Phinch, this part is not clear. I cannot get the coectly find to use in Phinch2. Hoe i can get it? 2).Shotgun metagenomics data, I can not find any tools from galaxy for following this hand on. (*25/08/2019*)
    - Graph gallery visualization feature (*09/09/2019*)

- **Antibiotic resistance detection**

**Comment by hexylena** [comment]
Now moved here: https://training.galaxyproject.org/feedback
