### ISSUE TITLE
Sequence analysis: feedback from the embedded feedback form

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#1588]
@galaxyproject/training-sequence-analysis 

Notes for all tutorials in this topic (16.09.2019):

![index](https://user-images.githubusercontent.com/1842467/64973689-c190a480-d8ab-11e9-9772-2c6180d5da95.png)

Details per tutorials:
- **Mapping**
  - Pro:
    - Very detailed, thank you (*17/09/2018*)
    - Easy to follow, great questions, great explanations! (*18/12/2018*)
    - Very clear instructions  (*15/07/2019*)
    - Almost everything (*18/07/2019*)
  - Con:
    - More details on the Selection of analysis mode (non default option) (*15/07/2019*)
    - In step 1 of "Hands-on: Mapping with Bowtie2" your instructions mention that the paired-end input is the output of Trim Galore!. However, the previous tutorial on quality control uses MultiQC. As such, the reader of this tutorial will be confused.  In "Hands on-Inspect a BAM/SAM file" the 11 fields listed in the tutorial (QNAME, FLAG...) do not match with the 10 field names in the output produced (QNAME, FLAG, RNAME, POS, MAPQ, CIGAR, MRNM, MPOS, ISIZE, SEQ). The JBrowse viewer, doesn't work for me, get an error (*18/07/2019*)

- **Quality Control**
  - Pro:
    - very detailed, easy to follow, thank you (*17/09/2018*)
    - step by step guideline (*07/10/2018*)
    - Examples and questionaries with solutions :-) (*08/10/2018*)
    - all of it! (*31/10/2018*)
    - Relatively clear to work through (*28/11/2018*)
    - step-by-step (*01/12/2018*)
    - Nice explanation, really easy! (*10/12/2018*)
    - all tool available single platform   (*27/12/2018*)
    - The instructions were really clear (*25/01/2019*)
    - very clear (*20/03/2019*)
    - It's clear enough, and contain the basic but necessary information for RNA-seq raw data Quality Control analysis. (*24/04/2019*)
    - this is so clear !  (*13/05/2019*)
    - solid logic and small amount of valuable information (*14/05/2019*)
    - I liked the most the part in which you explained the algorithm for the cutadapt tool, the concrete example was fundamental to understand everything clearly! (*04/06/2019*)
    - step by step QC analysis (*11/06/2019*)
    - Very Clear and well-thought instructions. Appreciated effort  (*15/07/2019*)
    - Amost everything! (*17/07/2019*)
    - Step-by-step instructions and showing results. Questions to test understanding. (*18/07/2019*)
    - step by step instruction (*27/07/2019*)
    - Way of explanation. (*15/08/2019*)
    - Easy to follow steps (*21/08/2019*)
    - The material (*23/08/2019*)
    - Preciseness (*04/09/2019*)
    - really helpful for first timers using fastqc, thank you. (*14/09/2019*)
  - Con:
    - the answers that are given to questions could be a bit more elaborate and give a/or link to a more detailed explaination (*17/09/2018*)
    - Not clear that Trim Galore and FastQ are integrated into Galaxy. Uncertain how obtained 97,644 sequences after trim galore of bad data (I got 99,341). (*22/09/2018*)
    - the webpage output for MultiQC is not functioning (*07/10/2018*)
    - More details regarding others output sections of FastQC tool (*08/10/2018*)
    - how to rmemeber steps.... (*31/10/2018*)
    - Doesn't need to be (*28/11/2018*)
    - often ambiguous (*01/12/2018*)
    - what is the next step? (*10/12/2018*)
    - more precise knowledge like FASTQC is all data copy and paste from their original source need more easy way explain of documentation    (*27/12/2018*)
    - MultiQC didn't work (*25/01/2019*)
    - specificity of quality check regarding the type of data (16S, whole genome) (*20/03/2019*)
    - suggestion of several programs that can be used eg for trimming (Trim Galore...) (*08/04/2019*)
    - You could including how to do FastQC scripts (*24/04/2019*)
    - Probably as we are not trimming any adaptors in this tutorial, Trimmomatic can also be used on datasets provided. (*14/05/2019*)
    - quality of audio in presentation (*11/06/2019*)
    - In your tutorial, you state "In this training, no adapters were already removed". What does this mean? That adapters were not removed? Then why do we not remove them in the tutorial? From a grammatical point of view your sentence is confusing. Do you mean "In this training, adapters were not yet removed"? (*17/07/2019*)
    - don't know (*27/07/2019*)
    - Examples can be included.  (*15/08/2019*)
    - Considering SNP in the analysis, practice adapters removal ?  (*21/08/2019*)
    - Figuring out why the mapping tutorial directed me here to quality control fastq files then they will not work... (*23/08/2019*)
    - More examples (*04/09/2019*)
    - provide images of what the results should look like. Also, there are a few typos like 'how many basepairs has been removed' instead of 'how many base-pairs have been removed' (*14/09/2019*)

**Comment by hexylena** [comment]
Now moved here: https://training.galaxyproject.org/feedback
