### ISSUE TITLE
Statistics & Machine learning: feedback from the embedded feedback form

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#1589]
@galaxyproject/training-statistics 

Notes for all tutorials in this topic (16.09.2019):

![index](https://user-images.githubusercontent.com/1842467/64974072-6a3f0400-d8ac-11e9-9e41-c1c8cb6f5f10.png)

- **Age prediction using machine learning**

- **Basics of machine learning**
  - Pro:
    - very straightforward tutorial (*08/03/2019*)
    - This was a helpful example for how machine learning can be applied to a real-world dataset. (*18/03/2019*)
    - Easy way to use machine learning (*06/07/2019*)
  - Con:
    - Add more info on how to access the SVM Classifier tool. This tool does not seem to be available in the US Galaxy instance, but it is available in the EU Galaxy instance. (*18/03/2019*)
    - maybe more information or link for understand each advanced parameters (*06/07/2019*)

- **Machine learning: classification and regression**
  - Pro:
    - Short and efficient primer (*02/09/2019*)
  - Con:
    - The theory behind the method in this particular example could be more expanded (*02/09/2019*)

**Comment by hexylena** [comment]
Now moved here: https://training.galaxyproject.org/feedback
