### ISSUE TITLE
User interface: feedback from the embedded feedback form

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#1590]
@galaxyproject/training-galaxy-ui 

Notes for all tutorials in this topic (16.09.2019):
![index](https://user-images.githubusercontent.com/1842467/64974150-8e024a00-d8ac-11e9-852e-9c99d2b4e282.png)

Details per tutorials:

- **Jupyter: Use Jupyter notebooks in Galaxy**
  - Pro:
    - Nicely done with screenshots (*10/09/2019*)
  - Con:
    - Would love info about using R in this setting. (*10/09/2019*)

- **Workflows: Extracting Workflows from Histories**
  - Pro:
    - Thorough step by step directions. Does not assume you know stuff already. (*15/11/2018*)
  - Con:
    - Naming the output files was a little confusing, especially when I was left on my own to continue to name all the rest of them. Why doesn't the new name show up in the workflow boxes after you name them? (*15/11/2018*)
    - Galaxy does not run the last step of the workflow (concatenate forward and reverse overlaps) - does not even appear in the history at all  (*16/01/2019*)

- **Workflows: Using Workflow Parameters**

  - Con:
    - Too long and too much details with screenshots to be able to gasp the main thing just with quick browse through material. Short summary of key points would be very helpful. (*01/07/2019*)

**Comment by hexylena** [comment]
Now moved here: https://training.galaxyproject.org/feedback
