### ISSUE TITLE
add example about history sharing to the database schema training material

### ISSUE THREAD

**Issue by hrhotz** [galaxyproject/training-material#16]
we need a small example explaining what happened when you share a history, and later try to delete datasets from this history

I will take care about this...eventually in time for GCC2017

**Comment by bgruening** [comment]
Maybe a tour for this as well?

**Comment by hrhotz** [comment]
of course, as soon as my galaxy server is 'tour-capable'......though it might be difficult, since you wanna show the events from the views of two different users.

**Comment by erasche** [comment]
@hrhotz or maybe you have time for GCC2020? :P  But I guess this tutorial has not been taught in a few years.

**Comment by hrhotz** [comment]
well, the admin training is now given by more qualified people....   ;)

**Comment by erasche** [comment]
Ahh not sure about that :) But thanks for the response! I guess we've cut the sql/db investigation out mostly but I will leave this open
