### ISSUE TITLE
updating the package name in ChIP-seq tutorial

### ISSUE THREAD

**Issue by LeilyR** [galaxyproject/training-material#1606]
the tool `Concatenate two datasets into one dataset` has been renamed to `Concatenate two BEDfile` . However when one selects it, it shows `Concatenate two datasets into one dataset (Galaxy Version 1.0.1)` on top of the page. This tool has been used in chip-seq tutorial and needs to be renamed to `Concatenate two BED files` . And To be honest I would have preferred the `Concatenate two datasets into one dataset` . I found the new name confusing because I didnt know if it actually does `sort`ing and `merg`ing too or it only runs `cat` .

**Comment by nsoranzo** [comment]
The tool name was changed in https://github.com/galaxyproject/tools-devteam/pull/508 .

**Comment by bebatut** [comment]
But something is strange on usegalaxy.eu

The tool is named "Concatenate two BED files" in the tool panel, as it should be given the wrapper:
![Screenshot-2019-09-23-at-13 41 11](https://user-images.githubusercontent.com/1842467/65424377-b7225d80-de0b-11e9-9970-7f576b7f32e6.png)

but when opening it, it is named "Concatenate two datasets into one dataset (Galaxy Version 1.0.1)":

![Screenshot-2019-09-23-at-13 42 07](https://user-images.githubusercontent.com/1842467/65424410-cacdc400-de0b-11e9-815b-4eff07f50b3b.png)

@nsoranzo, any idea why?

**Comment by nsoranzo** [comment]
It's pretty weird, when clicking on the entry in the "Tools" menu I see the same as you, but if I copy/paste the URL https://usegalaxy.eu/tool_runner?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fdevteam%2Fconcat%2Fgops_concat_1%2F1.0.1 in the address bar, I see the new tool name.

**Comment by bgruening** [comment]
Ok, this should be `fixed` ....

**Comment by erasche** [comment]
> Ok, this should be fixed ....

ok cool! :)
