### ISSUE TITLE
dev-corner - feedbacks 20-10-2016

### ISSUE THREAD

**Issue by lecorguille** [galaxyproject/training-material#164]
20-10-2016 at Lyon - France
Trainers: @abretaud @loraine-gueguen (@lecorguille)

Copy/Paste from this closed thread: https://github.com/bgruening/training-material/pull/128

Feedbacks from @abretaud 
> Course (almost) finished, time for feedback!
> 
> It went quite well, people managed to begin writing their own tool and seemed to understand well > the process
> 
> A few things that could be improved:
- [x] most of the people didn't know git/github, so I had to to show them how to create a pull request. maybe this could be added?
- [x]  a heavy silence fell on the room during the conda packaging hands-on 😄 people were lost and didn't know how to start. So describing a little more the meta.yaml/build.sh would help I think
- [ ] after the course students had 1 day to wrap their own tool. We had the case of a R script that needed many R libs not yet available in conda, they had to switch to another tool otherwise they would have spend the whole day packaging R libs. No miracle solution for this I think...

Feedbacks from @abretaud 
> A few other things I found while reviewing #165:
- [x] I feel like the Advanced features section should come before the github/docker stuff
- [x] on the macros picture (9.6) the name of the left file is wrong -> macros.xml
- [x] in advanced section, "reserved variables" should probably come last, they are much less used than macros and data collection
- [x] in Advanced section "Some config" is a bit rough, it would deserve some more love

Feedbacks from @loraine-gueguen
> Yes, it went well!
> Stuffs that can be added to improve the slides, to my mind:
- [x] example for macros
- [ ] generate an html file as output (multiple output)
- [x] some pictures are too small

**Comment by lecorguille** [comment]
- [X]  most of the people didn't know git/github, so I had to to show them how to create a pull request. maybe this could be added?
Done by @cmonjeau

**Comment by lecorguille** [comment]
@shiltemann Do you have or plan to have something about html outputs in a visualization part for Strasbourg?
- [ ] generate an html file as output (multiple output)

We already have this:
https://www.dropbox.com/s/afoftkt2k103tdx/galaxy4bioinformatics-integration-partI-1.13.pdf?dl=0 pages 92-95

I can begin something in the visualization part if you want?

**Comment by abretaud** [comment]
A few other things I found while reviewing #165:
- [ ] I feel like the Advanced features section should come before the github/docker stuff
- [ ] on the macros picture (9.6) the name of the left file is wrong -> macros.xml
- [ ] in advanced section, "reserved variables" should probably come last, they are much less used than macros and data collection
- [ ] in Advanced section "Some config" is a bit rough, it would deserve some more love

I'll see if I can work on these things in the coming days

**Comment by lecorguille** [comment]
Welcome to

**Comment by lecorguille** [comment]
- [x] on the macros picture (9.6) the name of the left file is wrong -> macros.xml
https://github.com/galaxyproject/training-material/pull/429/commits/8eea823d6c266c43a93401441948cfbbf6a002bc
