### ISSUE TITLE
"Getting data into Galaxy" slides don't mention Fetch URL 

### ISSUE THREAD

**Issue by sneumann** [galaxyproject/training-material#1641]
Hi, the "Getting data into Galaxy" tutorial mentions Upload from local computer and Entering Text, 
but not fetching via URL:
https://galaxyproject.github.io/training-material/topics/galaxy-data-manipulation/tutorials/get-data/slides.html#7 
Yours, Steffen

**Comment by bebatut** [comment]
Fixed with #1642
