### ISSUE TITLE
Galaxy 101 glitch 

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/training-material#1653]
See https://github.com/galaxyproject/galaxy/issues/9002 .. users don't see a select and need to input integers. 

Either convert the output of join to tabular, fix the bug, or say that integers need to be entered.

**Comment by erasche** [comment]
Do you have time for fixing this in the training @bernt-matthias?

**Comment by bernt-matthias** [comment]
I guess this should be fixed in Galaxy :)

**Comment by erasche** [comment]
Ok, so not a training issue then, cool :+1:
