### ISSUE TITLE
understanding the "discordantly aligned" reads in ATAC-Seq tutorial 

### ISSUE THREAD

**Issue by hrhotz** [galaxyproject/training-material#1693]
Please excuse my ignorance about 'bowtie2' but I was struggling to explain the 'blue' (i.e.: "rf") pairs in the insert size histogram. 

My initial explanation, was: These are the 1792 pairs which align discordantly (according to the bowtie2 stats). 

However, if I run bowtie2 again with "Disable no-discordant behavior" set to "yes". Those pairs are no longer listed in the stats (as expected), but I still get the same number of "rf" reads in the insert size histogram. The number is actually much bigger than 1792. Where are they coming from?

Thank you very much for your help
Hans-Rudolf

**Comment by lldelisle** [comment]
Hi,
This is a bit tricky.
If you have read pairs which perfectly overlap:
```
  ------->
  <-------
```
When you put bowtie2  "Disable no-discordant behavior" set to "yes", it will not consider them as discordant. You were expecting fr: `-->  <--`, this is not wrong.
However, when you give your bam to picard, he cannot know what was the expectation. So it evaluates if it is FR or RF.
The way it evaluates it is:
https://github.com/samtools/htsjdk/blob/7ce36364f941adce2daf01d234202f004addbb15/src/main/java/htsjdk/samtools/SamPairUtil.java#L78-L88
I do not remember exactly how, I will to some test to reply you precisely but some reads will be considered RF and others FR.

**Comment by hrhotz** [comment]
Thanks for the pointer! It is starting to make sense to me. The inserts in question are all <= ~50bp (i.e. the read length).

**Comment by lldelisle** [comment]
I made a minimal example:
```
@HD	VN:1.0	SO:coordinate
@SQ	SN:chr1	LN:248956422
@PG	ID:bowtie2	PN:bowtie2	CL:"/usr/local/tools/_conda/envs/mulled-v1-5bee08a20f60a5597c4ecd54735d608dc6a44caf6f433cd52f23c80aa5a38d02/bin/bowtie2-align-s --wrapper basic-0 -p 8 -x /data/db/reference_genomes/hg38/hg38canon/bowtie2_index/hg38canon -I 0 -X 1000 --fr --dovetail --very-sensitive -1 input_f.fastq.gz -2 input_r.fastq.gz"	VN:2.3.4.1
HWI-ST281:266:C1LTTACXX:4:2104:11794:34596	147	chr1	629088	1	44M	=	629088	-44	GTCCGAACTAGTCTCAGGCTTCAACATCGAATACGCCGCAGGCC	GIJJIHHIGIIGIHIIIGIIGJIIIIGHGIHFCHGHFFFFFCC@	AS:i:0	XS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:44	YS:i:0	YT:Z:CP
HWI-ST281:266:C1LTTACXX:4:2116:15672:47273	163	chr1	629088	1	45M	=	629088	-45	GTCCGAACTAGTCTCAGGCTTCAACATCGAATACGCCGCAGGCCC	CCCFFFFFGHHHHIJJJJJJJJJJJIJJJIIJJJJJJJJJJJGII	AS:i:0	XS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:45	YS:i:0	YT:Z:CP
HWI-ST281:266:C1LTTACXX:4:2104:11794:34596	99	chr1	629088	1	44M	=	629088	-44	GTCCGAACTAGTCTCAGGCTTCAACATCGAATACGCCGCAGGCC	@BBFFFFFHHHHHJJJJJJJJJJJJJJJJJJJJJJJJIJIJJGJ	AS:i:0	XS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:44	YS:i:0	YT:Z:CP
HWI-ST281:266:C1LTTACXX:4:2116:15672:47273	83	chr1	629088	1	45M	=	629088	-45	GTCCGAACTAGTCTCAGGCTTCAACATCGAATACGCCGCAGGCCC	JJJJJIHHJJJJJJJIJJHJJIIHIJJJJJJIHHHHHFFFFFCBC	AS:i:0	XS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:45	YS:i:0	YT:Z:CP
```
This sam has 2 pairs:
The pair HWI-ST281:266:C1LTTACXX:4:2104:11794:34596, the first in pair is forward, it is FR, the second one (HWI-ST281:266:C1LTTACXX:4:2116:15672:47273), the first in pair is reverse it is RF.

**Comment by lldelisle** [comment]
[insert_size_histogram.pdf](https://github.com/galaxyproject/training-material/files/3956768/insert_size_histogram.pdf)

**Comment by hrhotz** [comment]
Thank You!
