### ISSUE TITLE
Circos tool error 'Failed to communicate with remote job server.'

### ISSUE THREAD

**Issue by nvannier-mpipz** [galaxyproject/training-material#1725]
Hi, 

I am trying to run Circos tutorial on usegalaxy.eu server. I can plot the Karyotype but when trying to add Highlights as in the tutorial i get this error message: 

> An error occurred while running the tool 
>  toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy3.

> Job Information
> Failed to communicate with remote job server.

I tried to run it again with both the tutorial dataset and a homemade one but i get the same error. 

Any idea what could cause this problem ?

**Comment by hexylena** [comment]
Hi @nvannier-mpipz this is a bug with usegalaxy.eu, pinging @gmauro @bgruening.

**Comment by gmauro** [comment]
Despite the message, it's not a communication error.
The job fails after a few seconds and never reach the filesystem.

If you remove completely the highlights section, it works.

On Galaxy log there is this error message:
Jan 22 16:29:25 sn04.bi.uni-freiburg.de python[386927]: TypeError: circosColorAlpha() takes exactly 3 arguments (2 given) 
that suggest me an issue in the wrapper.

**Comment by hexylena** [comment]
Ok, found & fixed. I wish these errors were communicated to the tool user, I could've fixed this without help a week ago.

**Comment by hexylena** [comment]
@nvannier-mpipz please retry on EU now.
