### ISSUE TITLE
JupyterLab in Galaxy

### ISSUE THREAD

**Issue by annefou** [galaxyproject/training-material#1730]
I don't think we have a tutorial on "JupyterLab in Galaxy" similar to what is available for [Rstudio](https://training.galaxyproject.org/topics/galaxy-ui/tutorials/rstudio/tutorial.html).

The idea would be to have:

#### Questions
- How can I manipulate data using JupyterLab and Python in Galaxy?

#### Objectives
- Launch/Stop JupyterLab in Galaxy
- Create a python Jupyter notebook in Galaxy
- Get/put data in a python jupyter notebook in Galaxy

Is it relevant?

**Comment by bgruening** [comment]
Yes! Very relevant! :+1:

**Comment by hexylena** [comment]
Done in #1735, thanks @annefou!
