### ISSUE TITLE
markdown formatting of individual topic page e.g. summary item

### ISSUE THREAD

**Issue by abotzki** [galaxyproject/training-material#1738]
for example: https://galaxyproject.github.io/training-material/topics/assembly/

on this topic overview, we would like to be able to use an image or make certain words bold.

**Comment by hexylena** [comment]
Hi @abotzki, if you were to change https://github.com/galaxyproject/training-material/blob/master/_layouts/topic.html#L25 to use the `| markdownify` filter, then you could do this in the summary, if you wanted. Or just use `<b>/<img>` or so?

**Comment by abotzki** [comment]
Thanks for the tip @hexylena - `markdownify` work fine.
