### ISSUE TITLE
hierarchical organisation of topics

### ISSUE THREAD

**Issue by abotzki** [galaxyproject/training-material#1740]
it would be nice to be able to have a directory structure such that sub-topics under `/topics/example-topics` 
for example `/topics/example-topics/example-sub-topic/`

potential example where this would be useful:
https://www.compomics.com/bioinformatics-for-proteomics/ with 4 sub-topics where each sub-topics comprises one or more tutorials https://www.compomics.com/bioinformatics-for-proteomics/identification/

**Comment by hexylena** [comment]
We currently have sub-topics within topics, which should meet your desire, e.g. in the admin section https://training.galaxyproject.org/training-material/topics/admin/ If those sections were given an ID you could link to them directly. Does that meet your idea? For us, it isn't strictly necessary for them to be directories or have the URLs arranged in this way, I don't think?

**Comment by abotzki** [comment]
Thanks a lot - this concept of sub-topics works out for the mentioned use case.
