### ISSUE TITLE
cannot use the workflow

### ISSUE THREAD

**Issue by miaomiaozhou88** [galaxyproject/training-material#1747]
dear author,
it seems galaxy doesn't like this workflow?
![image](https://user-images.githubusercontent.com/44294127/73941203-19788800-48ed-11ea-9701-203248225582.png)

with kind regards

**Comment by wm75** [comment]
@miaomiaozhou88 This is because that's the wrong way to import it!
The link you've used is to the html formatted github page. You would have to use the link to the **Raw** view page to make this work.

**Comment by miaomiaozhou88** [comment]
Thanks! totally shocked by my own mistake...:-)

**Comment by hexylena** [comment]
Should be fixed by #1664 if someone has time to review that

**Comment by miaomiaozhou88** [comment]
No it is not needed Helena, I made a false alarm by pasting the wrong link …. My bad :-)
