### ISSUE TITLE
Clustering 3K PBMCs with Scanpy

### ISSUE THREAD

**Issue by hrhotz** [galaxyproject/training-material#1748]
the “Variables index” should be set to gene_symbol in the 'Import AnnData' tool, shouldn't-it? see also my withdrawn pull request #1741

**Comment by bgruening** [comment]
ping @mtekman

**Comment by mtekman** [comment]
@hrhotz Yep, you're right -- I missed this the first time around.

I will go through the tutorial again today before submitting any fixes

**Comment by mtekman** [comment]
@hrhotz #1751 has been merged - do you see anything else that needs fixing?

**Comment by hrhotz** [comment]
@mtekman Thank you very much
I remember a few typos, but will first check what you have already fixed. I will go through the document again (at the end of this week - I hope I will find the time)
