### ISSUE TITLE
PF4 versus PPBP for PC3 in "Clustering 3K PBMCs with Scanpy"

### ISSUE THREAD

**Issue by hrhotz** [galaxyproject/training-material#1767]
At the 'Visualization of PCA', the gene PF4 (and not PPBP) is the gene the most associated with the 3rd PC, isn'-it? (https://training.galaxyproject.org/training-material/topics/transcriptomics/images/scrna-scanpy-pbmc3k/pca_loadings.png)

**Comment by hrhotz** [comment]
ping @mtekman ping @bgruening 
I know, fixing this is a lot of work - maybe we can add an explanation why  PPBP and not PF4 is used....

**Comment by mtekman** [comment]
Yeah I had similar grievances, but this is what the original tutorial this training is based on looks for:

* https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html
  * Which in turn is based on: https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html
      * Where PPBP is a high ranking gene

We could break protocol and choose PF4, or we could just write a small explanation for this discrepency

**Comment by hrhotz** [comment]
fair enough, but they don't show a plot similar to https://training.galaxyproject.org/training-material/topics/transcriptomics/images/scrna-scanpy-pbmc3k/pca_loadings.png , do they?

**Comment by mtekman** [comment]
![Screenshot_2020-07-10 Satija Lab](https://user-images.githubusercontent.com/20641402/87170405-94e1c980-c2d1-11ea-9732-30fcb4bf8a43.png)

I would say it's ranked up there with PF4

**Comment by hrhotz** [comment]
what about, if we write in the solution box: "CST3 is the gene the most associated with the 1st PC, NKG7 the one for the 2nd PC, and PF4 and PPBP for the 3rd PC (for consistency with the published scanpy [https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html] and Seurat [https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html] documentation, we will use PPBP)

**Comment by mtekman** [comment]
Sounds good to me!

**Comment by hrhotz** [comment]
I have added it to PR #1960
