### ISSUE TITLE
Move ansible-galaxy answers to a subfolder

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/training-material#1788]
So that they can be linked from the tutorial instead of pointing to the GitHub page (which may point to a newer version of the answers if running an archived tutorial).

A common solution for the `dev` tutorials should be found, which have answers or other files in `topics/dev/files/` . Ideally that would be something similar to what we have for workflows, e.g. https://training.galaxyproject.org/training-material/topics/transcriptomics/tutorials/ref-based/workflows/

**Comment by hexylena** [comment]
@nsoranzo what did you mean by "answers" here?

**Comment by nsoranzo** [comment]
This has been solved by using git-gat since commit 627b22721bc7946642c0509de0e980984e04d3d6 .
