### ISSUE TITLE
Overhaul storage tutorial

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/training-material#1798]
- The slides speak of purging datasets, that should be an exercise.
- Same for creating data libraries and importing data.
- Rename to 'Data Storage'

**Comment by martenson** [comment]
just stumbled over this missing training part in admin storage, xref the original materials: https://galaxyproject.github.io/admin-training/2019-gcc/19-storage/storage.html#19

**Comment by hexylena** [comment]
https://training.galaxyproject.org/training-material/topics/admin/tutorials/data-library/tutorial.html we've got this, which roughly covers slide 19, is that more or less what you're missing?

**Comment by martenson** [comment]
I should've said from slide 19 onwards. Sorry.

**Comment by hexylena** [comment]
Ahh gotcha! No worries. Yeah we're definitely missing that as a tutorial :(  It's covered in the maintenance slides a bit https://training.galaxyproject.org/training-material/topics/admin/tutorials/maintenance/slides.html#5 but it really should be a tutorial on doing it.

**Comment by martenson** [comment]
Oh, so that's where it went! I couldn't find it, thanks!

**Comment by hexylena** [comment]
If there's a better organisation that you think would make more sense or make it more findable, we can definitely re-organise.

It sucks that slides aren't searched currently, I'll try and fix that at some point.

**Comment by hexylena** [comment]
Cancelled, we won't fix this. It's a good material, but it won't ever fit in the golden path
