### ISSUE TITLE
tool development slides improvements

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/training-material#184]
* [x] repeat slides -> enumerate is not used
* [x] tests slide needs to use `sim_size` for pngs
* [ ] hands-on steps for planemo test, include planemo lint

**Comment by lecorguille** [comment]
- debug a wrapper with the good conda environment (without have to relaunch x time planemo) using 
```bash
planemo --no_cleanup
cd /tmp/tmpQ2UkMa/job_working_directory/000/9/working
../tool_script.sh
```

**Comment by nsoranzo** [comment]
> tests slide needs to use sim_size for pngs

For the test copy-pasted from `graphlan` wrapper:
```
<output name="png_output_image" file="png_image.png" />
```
actually works fine.

**Comment by bgruening** [comment]
What do you think about dropping the explanation of the parameters from the slides. It takes a long time and parts of it is explained in the planemo docs and are also easy to grasp. It took a long time during the training imho.

**Comment by lecorguille** [comment]
* [ ] hands-on steps for planemo test, include planemo lint
Done within the Planemo tutorial
