### ISSUE TITLE
Made a nice Circos plot?

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/training-material#1867]
We'd love to consider your Circos plots for inclusion in the [training materials](https://training.galaxyproject.org/training-material/topics/visualisation/tutorials/circos/tutorial.html) as examples of what it can do and the variety of outputs!

So please, comment share your plot here with your Galaxy history, or [send us an email](mailto:helena.rasche@gmail.com?subject=Circos%20Plot%20for%20Training%20Materials) if you don't have a github account.

**Comment by shiltemann** [comment]
moved this to discussion tab: https://github.com/galaxyproject/training-material/discussions/2197
