### ISSUE TITLE
Legend missing from regression plot

### ISSUE THREAD

**Issue by anuprulez** [galaxyproject/training-material#1911]
Legend text got clipped from Figure 5 in [Regression in machine learning](https://training.galaxyproject.org/training-material/topics/statistics/tutorials/regression_machinelearning/tutorial.html) tutorial

![legend_missing](https://user-images.githubusercontent.com/3022518/84131814-61e3b600-aa45-11ea-903f-c4d5defd89da.png)

ping @khanteymoori

**Comment by Leslie-C** [comment]
Tutorial looks okay to me in my browser (Chrom v86), and the image itself does not appear to have text clipping issue.

![True vs predicted values](https://training.galaxyproject.org/training-material/topics/statistics/tutorials/regression_machinelearning/images/true_pred_curves.png)

Could you provide more information to help re-create the issue?

**Comment by hexylena** [comment]
Closed pending updates from the author.
