### ISSUE TITLE
Docker build fail

### ISSUE THREAD

**Issue by xgaia** [galaxyproject/training-material#1949]
I'm trying to build the website with docker and it fail with

```
  Liquid Exception: Liquid syntax error (line 232): Unknown tag 'icon' in topics/introduction/slides/introduction.html
                    ------------------------------------------------
      Jekyll 4.1.1   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
make: *** [Makefile:70: build] Error 1
The command '/bin/sh -c make build' returned a non-zero code: 2
```

Here is the Dockerfile:

```Dockerfile
FROM ubuntu:20.04 AS builder

COPY . /training-material
WORKDIR /training-material

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y && apt-get install -y locales curl make gcc g++ build-essential patch ruby-dev libxml2-dev zlib1g-dev liblzma-dev

# Set the locales
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

ENV ICONV_LIBS="-L/root/miniconda3/envs/galaxy_training_material/lib/ -liconv"

RUN make install-conda
RUN make install
RUN make build

FROM nginx:1.18.0-alpine
COPY --from=builder /training-material/_site/training-material /usr/share/nginx/html
```

Any help is welcome :-)

**Comment by hexylena** [comment]
(misclick, sorry @dannon. Meant to ping @bedroesb)

**Comment by shiltemann** [comment]
Hi @xgaia :)

try adding `RUN make create-env` in between the `install-conda` and `install` commands

**Comment by xgaia** [comment]
> Hi @xgaia :)
> 
> try adding `RUN make create-env` in between the `make install-conda` and `make install` commands
`create-env` is launched before `install` on Makefile

https://github.com/galaxyproject/training-material/blob/5304f41276d137473f9a6950a2456f4bebc7176e/Makefile#L48

**Comment by shiltemann** [comment]
yeah good point, hmm. any other warnings or errors during the build?

**Comment by bedroesb** [comment]
I sadly do not have experience in building the website itself in a container, only with bringing its tutorial contents to a galaxy container :/

**Comment by shiltemann** [comment]
regarding the line:
```
COPY . /training-material
```

Could you try moving the `Dockerfile` out of the training directory (or changing the build context, depending on how you're running this)? for me locally it wasn't copying everything over (e.g. `_layouts` and other such directories were missing if I did a `RUN ls` after the copy), but it was fixed when I moved up a level relative to the training directory and did a `COPY ./training-material /training-material` instead

**Comment by xgaia** [comment]
> Could you try moving the `Dockerfile` out of the training directory (or changing the build context, depending on how you're running this)? for me locally it wasn't copying everything over (e.g. `_layouts` and other such directories were missing if I did a `RUN ls` after the copy), but it was fixed when I moved up a level relative to the training directory and did a `COPY ./training-material /training-material` instead

Thanks @shiltemann, the website build fine when I move the Dockerfile!

Here is the new dockerfile

```Dockerfile
FROM ubuntu:20.04 AS builder

COPY ./training-material /training-material/
WORKDIR /training-material

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y && apt-get install -y locales curl make gcc g++ build-essential patch ruby-dev libxml2-dev zlib1g-dev liblzma-dev

# Set the locales
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

ENV ICONV_LIBS="-L/root/miniconda3/envs/galaxy_training_material/lib/ -liconv"

RUN make install-conda install build

FROM nginx:1.18.0-alpine
COPY --from=builder /training-material/_site/ /usr/share/nginx/html/

```

:partying_face:
