### ISSUE TITLE
Moving feedback form before references on the tutorial pages

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#1952]
The feedback form is currently at the far end of the tutorial pages. If there are many references, learners may not see the form. E.g. in the [Reference-based RNA-seq tutorial](https://training.galaxyproject.org/training-material/topics/transcriptomics/tutorials/ref-based/tutorial.html#bibliography), we really need to scroll down to see it. We could maybe move the feedback form before the references

**Comment by hexylena** [comment]
I've got some ideas here, I'll have a go at it. It's a good point about it being too far down!
