### ISSUE TITLE
Local build problem related to night/midnight theme

### ISSUE THREAD

**Issue by wm75** [galaxyproject/training-material#1964]
When running make serve on the latest GTN version locally, I'm getting:

```
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    File to import not found or unreadable: syntax_highlighting-dark.scss. on line 101
jekyll 3.8.6 | Error:  File to import not found or unreadable: syntax_highlighting-dark.scss. on line 101
make: *** [Makefile:55: serve] Error 1
```

For sure the file is there and I failed to find the reason for the complaint. My current solution is to remove the problematic line and includes that depend on it.

**Comment by hexylena** [comment]
Hi @wm75, quite strange! I know you're on linux, so, extra odd :) It has worked everywhere else (travis, multiple other linux machines), but, if you find a way to cause it let us know?
