### ISSUE TITLE
De novo transcriptome reconstruction from RNA-seq data (WIP)

### ISSUE THREAD

**Issue by malloryfreeberg** [galaxyproject/training-material#197]
Hi all,

@MoHeydarian and I are working on a tutorial for de novo transcriptome reconstruction (reference gene annotation-free) from RNA-seq data. These data are from the same study as the ChIP-seq tutorial we prepared, so we are hoping in the future to have another tutorial on how to integrate the two analyses. We would like to note that this tutorial differs from the proposed #59 Trinity tutorial, so we feel both tutorials would be good to have.

@bebatut or @bgruening: would it be best to nest this tutorial under the RNA-seq tutorial repo?

**Comment by bgruening** [comment]
@malloryfreeberg I think nesting is completely fine, for example we have multiple introduciton: https://github.com/galaxyproject/training-material/tree/master/Introduction/slides

I would even think that complete sub-repos would make sense to have a tour and a Docker container for every single tutorial.

**Comment by malloryfreeberg** [comment]
Sounds great @bgruening!
