### ISSUE TITLE
Galaxy 101 for everyone image licensing issues

### ISSUE THREAD

**Issue by wm75** [galaxyproject/training-material#1972]
This is a follow-up from an earlier [comment](https://github.com/galaxyproject/training-material/pull/1963#issuecomment-657214840):
With help from @annefou I now tracked the origins of the unattributed images in the Galaxy 101 for everyone tutorial.
Turns out the *iris versicolor* and *virginica* photographs are from wikimedia with open licenses, but the *iris setosa* photograph originally came from a private website without explicit licensing.
I contacted the photographer and owner of the website, Sonja Keohane, and asked her for permission to keep using the image, and, luckily, this is her response:

> Thank you for your honesty and for asking for permission to use my iris photo.  You have my permission to use this photo for your website and statistics classes.

I've opened #1971 to add proper attributions to all three *iris* images.

The situation with the "4Cs of diamonds" image, unfortunately, is less easy to resolve. This image comes from https://4cs.gia.edu/en-us/blog/gia-diamond-grading-scales/ and GIA's copyright disclaimer rather explicitly forbids unauthorized use of their material so, again, I asked for permission and got this response:

> Thank you for your message. In order for you to continue using the image as part of your training materials, there are certain conditions.
>
> The original image may not be modified. We require that “GIA” be added back to the headings Clarity Scale, Color Scale and Cut Scale. A copyright notice must be added to the image to read: © Gemological Institute of America (GIA). All rights reserved.
> 
> In addition, there is a license agreement that we would need you, or someone who is authorized, to sign.
>
> If these conditions are acceptable, please let me know to whom I should address the license agreement and I will complete and send the form.

@annefou please decide how you want to proceed here! Given that you would need to use the image unmodified (i.e., without the numbering added), it may be simpler to just explain the grading in text form and link to the image on the GIA site for details, but I leave that decision up to you. If you would like to keep the image I can get you in contact with the responsible person at GIA. Just make sure we address this soon and don't forget about it.

A general suggestion from this experience:
should we add a PR template to the training material with a checkbox saying sth like: *I have checked that any images added by this PR can be used on the training website without licensing issues" or similar?

**Comment by annefou** [comment]
@wm75 I would remove the image (4Cs of diamonds). It is not very important for the purpose of the tutorial. 

Adding a tick box would be useful. Just to remoind ignorant people (like me...) that they need to be careful. 
I was not very aware at that time about licensing issues for images. I know it is silly but I may not be the only one to be ignorant on that topic!

Many thanks for raising this issue.
