### ISSUE TITLE
Workflow testing cofest discussion

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/training-material#2002]
I'm interested in checking that tests in the */workflows directories are working and writing some new ones for untested workflows.  If I am writing a test for one I'll write it down here as an effort not to double-up with other cofest contributors.  There are a lot to choose from that do not have tests.

Some tests already exist in https://github.com/usegalaxy-eu/workflow-testing but may be out of date.

This tutorial is a good for understanding the format of the tests: https://galaxyproject.github.io/training-material/topics/contributing/tutorials/create-new-tutorial-technical/tutorial.html#testing-the-workflow-recommended. 

An example of a workflow test in this repo: https://github.com/galaxyproject/training-material/blob/master/topics/statistics/tutorials/machinelearning/workflows/machine_learning-test.yml

**Comment by cat-bro** [comment]
I'm currently checking/updating tests for 
`topics/variant-analysis/tutorials/microbial-variants/workflows/microbial_variant_calling.ga` and
`topics/variant-analysis/tutorials/mapping-by-sequencing/workflows/workflow-arabidopsis.ga`

**Comment by bgruening** [comment]
@cat-bro sorry I missed that completely! But I think this is a great idea and fits nicely the push of workfow related work that @jmchilton and @mvdbeek have been doing recently.
