### ISSUE TITLE
Add quay.io credentials to github secrets

### ISSUE THREAD

**Issue by bedroesb** [galaxyproject/training-material#2046]
If we want to build and push the containers to quay.io automatically we will have to add credentials to this repo using secrets:

DOCKER_REGISTRY_PASSWORD and DOCKER_REGISTRY_USERNAME

**Comment by bedroesb** [comment]
will solve https://github.com/galaxyproject/training-material/actions/runs/281868100

**Comment by bgruening** [comment]
@bedroesb can we do this? Does it not time out?

**Comment by bedroesb** [comment]
the ones that time out are commented out ... :)

**Comment by shiltemann** [comment]
cool, can do :+1:

**Comment by shiltemann** [comment]
ok, set up the secrets and restarted the jobs, starting to see green check marks, thanks @bedroesb ! :+1:

**Comment by bedroesb** [comment]
thats great!
