### ISSUE TITLE
Library w/datasets for tutorial on dataset collections missing (blank page)

### ISSUE THREAD

**Issue by ic4f** [galaxyproject/training-material#2050]
Re: https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/collections/tutorial.html

Clicking the link to the library containing the datasets for the tutorial displays a blank page with the Galaxy masthead.
https://usegalaxy.org/library/list#folders/Fab5f788f07073c11

**Comment by bgruening** [comment]
@ic4f I think if you change it to https://usegalaxy.org/library/folders/Fab5f788f07073c11 it would work?

I'm worried that this broke with the recent library changes. Or was the old link never working?

**Comment by hexylena** [comment]
These URLs are only used in Anton tutorials, and they're used a lot. We should convert them to proper zenodo datasets where they aren't already. Easy to fix though!

**Comment by ic4f** [comment]
@bgruening apparently, yes, that fixes it! Should I make the change (I'll then search for similar issues  in other tuttorials)? Or are we converting the datasets to zenodo as per @hexylena? (although I don't know how to do that)

**Comment by bgruening** [comment]
@ic4f you can take the datasets from the library and upload them to zenodo. The zenodo ID can than be added to the trianing.

**Comment by ic4f** [comment]
@bgruening I'm afraid I don't have the information necessary to fill out the zenodo upload form - I'd be guessing most of the time. Maybe one of the authors could help with this? Ping @nekrut 
I'm referring to this: https://www.pnas.org/content/111/43/15474.abstract linked from this: https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/collections/tutorial.html
