### ISSUE TITLE
Update screenshots for Understanding Galaxy history system tutorial

### ISSUE THREAD

**Issue by ic4f** [galaxyproject/training-material#2074]
1. 17 screenshots have the "Create New History" button missing (icon group in the top right corner).
2. Most have outdated colors.
3. All that display the search box have the search tips icon missing
4. Figure 13: "For all selected" dropdown menu missing options:  
-- permanently delete datasets
-- build collection from rules
5. Figure 8: "Tool help" icon missing (actions icon group)

**Comment by gallardoalba** [comment]
I'll do it!

**Comment by bgruening** [comment]
I hope that is solved. @ic4f thanks for creating this issues.
