### ISSUE TITLE
Fix (or remove) broken links, minor typos in tutorials

### ISSUE THREAD

**Issue by ic4f** [galaxyproject/training-material#2078]
- [x] [Rule Based Uploader](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/upload-rules/tutorial.html):
	- Hands-on: Downloading Data from ENA: downloaded directly **here**
- [x] [R basics in Galaxy](https://training.galaxyproject.org/training-material/topics/introduction/tutorials/r-basics/tutorial.html): 
	- Learning more about lists: **nice tutorial**
- [x] [NGS data logistics](https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-ngs-data-managment/tutorial.html):
	- [x] From “Understanding and improving high-throughput sequencing data production and analysis”, Ph.D. dissertation by **Martin Kircher**
	- [x] From Ph.D. dissertation of **Martin Kircher**.
	- [x] What are base qualities? - last paragraph: missing closing paren (after Wikipedia)

**Comment by hexylena** [comment]
The first one is a 500 internal server error on their end. But we should definitely move this dataset to zenodo!

**Comment by ic4f** [comment]
@hexylena I notified them (ENA) using their contact form. 
(I don't have all the dataset info to fill out the Zenodo form though.)

**Comment by hexylena** [comment]
@ic4f it doesn't take that much information for a zenodo entry, for what it's worth. e.g. https://zenodo.org/record/3603221

- GTN Tutorial: Name
- Short description like "data for this tuto"
- The files
- CC4.0
- there's an option for associating it with a collection, just find the galaxy/gtn one
- I don't think there's anything more?

**Comment by ic4f** [comment]
@hexylena Seems simple enough, will do!

**Comment by hexylena** [comment]
Just to check: were you claiming this issue as in you want to work on it? Or just reporting the issue for someone else to?

**Comment by ic4f** [comment]
Not claiming the issue, just adding the dataset to zenodo to check it off.

**Comment by ic4f** [comment]
@hexylena apparently those datasets are on zenodo (although with overwritten sequence identifiers), and those URLs are in the tutorial - right below the paragraph with the broken link. More importantly, the link is fixed ^.
