### ISSUE TITLE
"Compose text parameter value tool" is missing or does not appear in the search.  

### ISSUE THREAD

**Issue by jaidevjoshi83** [galaxyproject/training-material#2083]
- In the tutorial [Using Workflow Parameters ](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/workflow-parameters/tutorial.html), section,  “Create a text parameter from multiple parameters” and “Read a parameter from a dataset”,  tool “Compose text parameter value” might be missing or search is not able to fetch the tool. @paper-cut

**Comment by wm75** [comment]
Are you in the WF editor when looking for the tool? *Expression Tools* like WF *Inputs* are not supposed to be findable in the "regular" Tools Bar.
If your are in the WF editor, which server are you using?

**Comment by jaidevjoshi83** [comment]
Yes, it's working.   I got it, it's my bad Marius already suggested this. Can I close this?
