### ISSUE TITLE
"Using Workflow Parameters" tutorial is missing a step. 

### ISSUE THREAD

**Issue by jaidevjoshi83** [galaxyproject/training-material#2084]
- [Using Workflow Parameters](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/workflow-parameters/tutorial.html) tutorial is missing a step: before editing the tool in the workflow, you need to click the workflow and select "edit" from the menu. Or is this assumed to be obvious?

**Comment by shiltemann** [comment]
@jaidevjoshi83 thanks for spotting this! this step should definitely be added to the tutorial :+1:

**Comment by gallardoalba** [comment]
It can be closed I think @mvdbeek.

**Comment by mvdbeek** [comment]
Thanks everyone!
