### ISSUE TITLE
Count matrix in RNA-seq reads to count tutorial

### ISSUE THREAD

**Issue by MzwaneleN** [galaxyproject/training-material#2125]
Hi.

I have been following the RNA-seq reads to count tutorial. At the end my count matrix is different than the one at the end of the tutorial. The overwhelming majority of the genes in my count matrix have zero counts compared to the tutorial count. Did I make a mistake along the way?

Geneid	MCL1-DL	MCL1-DK	MCL1-DJ	MCL1-DI	MCL1-DH	MCL1-DG	MCL1-LF	MCL1-LE	MCL1-LD	MCL1-LC	MCL1-LB	MCL1-LA
100008567	0	0	0	0	0	0	0	0	0	0	0	0
100009600	0	0	0	0	0	0	0	0	0	0	0	0
100009609	0	0	0	0	0	0	0	0	0	0	0	0
100009614	0	0	0	0	0	0	0	0	0	0	0	0
100009664	0	0	0	0	0	0	0	0	0	0	0	0
100012	0	0	0	0	0	0	0	0	0	0	0	0
100017	0	0	0	0	0	0	0	0	1	0	0	0
100019	0	0	0	0	0	0	0	0	0	0	0	1
100033459	0	0	0	0	0	0	0	0	0	0	0	0
100034251	0	0	0	0	0	0	0	1	0	0	0	0
100034361	0	0	0	0	0	0	0	0	0	0	0	0
100034363	0	0	0	0	0	0	0	0	0	0	0	0
100034684	0	0	0	0	0	0	0	0	0	0	0	0
100034726	0	0	0	0	0	0	0	0	0	0	0	0
100034729	0	0	0	0	0	0	0	0	0	0	0	0

**Comment by mblue9** [comment]
Hi @MzwaneleN, that's expected, the screenshot shows what the full dataset would look like. The tutorial uses a small subset of the data ~ 1000 reads per sample to save on processing time. You should have  ~600 non-zero rows in that matrix.

**Comment by mblue9** [comment]
I'm making some modifications to the tutorial at the moment so I'll add a sentence to make that clearer. Thanks for the question.
