### ISSUE TITLE
Hover text for hands-on icon needs fixing

### ISSUE THREAD

**Issue by wm75** [galaxyproject/training-material#2134]
![Screenshot from 2020-11-18 13-15-43](https://user-images.githubusercontent.com/4742081/99529720-8ce11700-29a0-11eb-99d2-fb2601c324c7.png)

*Where to run the tutorial* is currently displayed for both the "hands-on" icon and the "instance/world" icon, but makes sense only for the latter.

Maybe the hands-on text could say *Follow the tutorial in different languages" or sth similar? Or perhaps the languages should only be mentioned when hovering above the arrow-down icon?

**Comment by hexylena** [comment]
> the languages should only be mentioned when hovering above the arrow-down icon

this sounds good. Maybe the main button can just read "Follow the tutorial"
