### ISSUE TITLE
Suggestion for template addition: format tool names and file names

### ISSUE THREAD

**Issue by AnnaSyme** [galaxyproject/training-material#214]
Hi all, 

We have been writing some Galaxy tutorials (which I am hoping to contribute over here soon) and were using CSS to add some formatting to various parts. I include an example here in case you are interested in using this too.

For example: tool names/settings in blue, and file names with a border: 
![screen shot 2017-02-09 at 2 28 05 pm](https://cloud.githubusercontent.com/assets/13082854/22768125/fed0d58c-eed3-11e6-8b7d-0b5b061e106f.png)

In Markdown format, we then added tags such as "ss" for screen shot text and "fn" for filenames.

Then in the CSS file, we added these descriptions, e.g. 

SS {
  font-family: "Lucida Grande", sans-serif;
  font-size: 80%;
  font-weight: bolder;
  color: black;
  text-align: center;
  border-radius: 5px;
  background: lightsteelblue;
  padding: 0.3ex 1ex;

}

FN {
  font-family: "Lucida Grande", sans-serif;
  font-size: 80%;
  color: black;
  text-align: center;
  padding: 0.3ex 1ex;
  border: solid thin black;
  border-radius: 4px;
}

Just putting it here as a suggestion. 

Anna

**Comment by bebatut** [comment]
Thanks @AnnaSyme for this suggestion. It could be nice to have something to make even more clear which tool using on which tool.

How is the markdown looking to do that? 

For now, we do not have special formatting for the filename, just for the tools:
![screen shot 2017-02-09 at 09 01 40](https://cloud.githubusercontent.com/assets/1842467/22774210/65db7e68-eea6-11e6-9203-340a80c38f45.png)

In markdown:
```
2. **TopHat** :wrench:: Run **TopHat** with:
    - "Paired-end (as individual datasets)" instead of "Single-end"
    - The Trim Galore outputs in the correct order (forward and reverse reads)
    - "Drosophila melanogaster: dm3" as reference genome
    - Default values for *strandedness* and *insert size*
```

PS: as the section where to find the tool can change from one instance to the other, we decided to not adding them

**Comment by AnnaSyme** [comment]
Thanks @bebatut for your reply. 

I will use the current formatting for now - that looks good - with the **  and the wrench. 

If we ever want to use the CSS style, the way to do it in Markdown is to surround the text with CSS tags such as `<ss> text </ss>`

**Comment by bgruening** [comment]
@AnnaSyme should we discuss this further during the upcoming training contribution fest, or can we close this?

**Comment by AnnaSyme** [comment]
@bgruening @bebatut  we can close this for now - it's always an option for the future but the current format looks good.

**Comment by bgruening** [comment]
@AnnaSyme great, thanks!
