### ISSUE TITLE
Ansible tutorial: replace geerlingguy.git with alternative that is not already installed on VMs

### ISSUE THREAD

**Issue by ic4f** [galaxyproject/training-material#2166]
The Ansible tutorial expects the user to have a failed playbook run [when installing a package](https://training.galaxyproject.org/training-material/topics/admin/tutorials/ansible/tutorial.html#question-question-2). However, this doesn't happen because Git is already installed. 
Solution: we need to use a different module as an example.

(This was discussed prior to and during admin training at BCC 2020.)

**Comment by hexylena** [comment]
Do `geerlingguy.memcached`, that's a pretty harmless service.
