### ISSUE TITLE
Error in Normalization using DESEQ2: Step 7 in Reference-based RNA-Seq data analysis tutorial

### ISSUE THREAD

**Issue by mgabere** [galaxyproject/training-material#2224]
Hi Galaxy team,

I went through the Reference-based RNA-Seq data analysis using Galaxy. The tutorial is very informative and easy to
understand. Great.

However, there is a minor mistake in the section "Normalization using DESEQ2), that is step 7 (Compute the normalized counts: divide the original counts by the scaling factors). The original counts were multiplied by the scaling factors to get the scaled read counts. Please change it by dividing with the scaling factor. For example, the scaled read counts for Gene C should be 33/0.4 = 83, and so forth. 

Also, please correct the reference for StatQuest video, that is, in the line with following verbatim:

This explanation is a transcription and adaptation of the [StatQuest video explaining Library Normalization in DESEq2](https://www.youtube.com/watch?v=UFB993xufUU&t=35s)

Thanks,
musa

**Comment by yvanlebras** [comment]
Dear Musa, 

I tried a first PR taking into account your comments here: https://github.com/galaxyproject/training-material/pull/2228

THANK you for helping us ameliorating continuously our training material !

Kind regards,

Yvan

**Comment by mgabere** [comment]
Great. Thanks. musa
