### ISSUE TITLE
New GTN tutorial on Zenodo publishing guidelines

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/training-material#2251]
It would be appropriate to create a GTN tutorial to provide users with a basic guide on how to publish data in Zenodo.

Some of the points to be addressed should include:
- Procedure for downsampling the datasets
- Adequate size for datasets
- Data licensing considerations

**Comment by bebatut** [comment]
Part of that is already covered in the ["Creating a new tutorial" tutorial](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/create-new-tutorial/tutorial.html#a-toy-dataset)

**Comment by hexylena** [comment]
We could probably extract that into it's own tutorial for visibility?

**Comment by bebatut** [comment]
Sure!

**Comment by hexylena** [comment]
Is this done @gallardoalba? I think we still wanted to move it into it's own tutorial maybe.
