### ISSUE TITLE
New templates: de.NBI / University Freiburg / MPI Freiburg

### ISSUE THREAD

**Issue by TorHou** [galaxyproject/training-material#226]
It would be nice to have templates to make the affiliations clearer when giving our biannual workshops for example.

**Comment by bgruening** [comment]
@TorHou any idea here? We could discuss this a little bit during our workshop in Cambridge.

**Comment by bebatut** [comment]
any idea for that? Is it really? Are the logos on the first page not enough?

**Comment by bebatut** [comment]
@TorHou I will close this issue.
If anyone thinks we should find another solution, we can still reopen it later
