### ISSUE TITLE
Help us out with video captions!

### ISSUE THREAD

**Issue by shiltemann** [galaxyproject/training-material#2273]
Hi Everybody!

As you may know, we have 2 big Galaxy workshops coming up:
1. [Admin Training](https://galaxyproject.org/events/2021-01-admin-training/) - Learn how to run your own Galaxy Server!
2. [GTN Smörgåsbord](https://shiltemann.github.io/global-galaxy-course/) - Get a taste of what the GTN has to offer!. 

These courses will have many videos available for participants (which will also remain online afterwards for everybody to use). To make these videos accessible for the widest possible audience, we would like to ensure they all have **high quality subtitles**. 

YouTube does a decent job of creating automated captions, but these need some manual editing (mostly adding punctuation, capitalization, fixing names and technical words, etc.)

**How you can help:**  Watch the videos and fix the auto-generated subtitles where needed

The auto-generated captions and further instructions can be found below:
- [Admin Training](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit?ts=600575ea#heading=h.cjfkeo30dmz8) (All done! Thanks so much everybody!)
-  [GTN Smörgåsbord](https://docs.google.com/document/d/10Sya2qN9RC82ijyGvXlZaeGC1a2yy_dsyJvIPIIEunA/edit?usp=sharing)

Make sure you add your name to these documents if you've helped out with the captions for a particular training session, we will credit you on the video!

**Comment by nomadscientist** [comment]
@shiltemann is this done?

**Comment by shiltemann** [comment]
thanks @nomadscientist yes this can be closed now (thanks to everybody who helped out!)
