### ISSUE TITLE
Circos trainining karyotype configuration file problem

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/training-material#2286]
When using the file [hg18_karyotype_bands.tsv](https://zenodo.org/record/3603221/files/hg18_karyotype_bands.tsv) as karyotipe configuration, it generates the following error:
```
Traceback (most recent call last):
  File "/data/share/staging/14508696/tool_files/karyotype-colors.py", line 9, in <module>
    idx=idx, pos=int(float(idx) / highest * 360)
ZeroDivisionError: float division by zero
```
I checked the file format, and it seems right according to the [circos documentation](http://circos.ca/tutorials/lessons/image_maps/bands/).

**Comment by hexylena** [comment]
So you've used a bands file I think as input to the karyotype field. This is fine, if and only if, there are also the karyotype definitions. The tool does not support stand-alone bands files currently.

**Comment by gallardoalba** [comment]
Nice, concatenating hg18_karyotype.txt and hg18_karyotype_bands.tsv solved the problem.
