### ISSUE TITLE
Video on scrna-intro is 1 slide out of sync due to Requirements slide

### ISSUE THREAD

**Issue by mtekman** [galaxyproject/training-material#2316]
* [the Video](https://training.galaxyproject.org/training-material/topics/transcriptomics/videos/#video-transcriptomics-scrna-intro)

If you look at the video at 6 seconds in, there is an extra slide added "Requirements", which is not defined [in the markdown](https://github.com/galaxyproject/training-material/blob/12853cc254201681cbdb700843cc36bcaf9be70f/topics/transcriptomics/tutorials/scrna-intro/slides.html#L31).

 I believe this throws off the video captions by 1 slide. Is this an easy fix?

**Comment by hexylena** [comment]
It's already fixed :) we're rebuilding soon

**Comment by hexylena** [comment]
#2314 , #2315

**Comment by mtekman** [comment]
Oh sweet!
