### ISSUE TITLE
Dev Corner - Docker for Tool Dependencies

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/training-material#232]
There is a good chance "Conda and Containers for Tool Dependencies" will be selected for a tutorial at the GCC. It would be good to have a dedicated tutorial for using Docker as tool dependencies. It would be nice if it covered two approaches - manual and with BioContainers magic.

- A good existing - if somewhat dated - resource for manual Docker dependencies would be the tutorial from @apetkau at https://github.com/apetkau/galaxy-hackathon-2014.
- I don't think any BioContainers documentation exists but it should be built up (probably as part of planemo) and a set of slides added to this repository.

**Comment by bgruening** [comment]
xref: https://github.com/bgruening/docker-galaxy-stable/#enable-galaxy-to-use-biocontainers-docker--toc
