### ISSUE TITLE
SARS-Cov2 rDock Docking tutorial

### ISSUE THREAD

**Issue by ppxasjsm** [galaxyproject/training-material#2324]
Hi everyone at the galaxy project!

It looks really nice and haven't really looked at it in more detail yet, so apologies if my questions is redundant and answered somewhere in the documentation. I have been looking at the rDock Sars-Cov2 tutorial by @simonbray (https://training.galaxyproject.org/training-material/topics/computational-chemistry/tutorials/covid19-docking/tutorial.html#docking-and-scoring)

I found it quite difficult to actually set up the tools needed for the tutorial, e.g. how to install rDock, which may be quite a hurdle to get started, particularly for novices in Comp Chem who may have never compiled code from source. Is there a way in which requirement handling and installing of software needed for the tutorial is addressed? Do you use something like Binder where you could just run the tutorial with all the necessary prerequisites installed? Should a guide on how to install the required software be part of a tutorial?

Thanks for any help/comments. 

Best wishes,
-Toni

**Comment by hexylena** [comment]
Hi @ppxasjsm, yes! We have answers :) at the top of the tutorial you'll find a number of public servers where the tools can be run, as well as a docker container that should support local running of the tools.

![image](https://user-images.githubusercontent.com/458683/106735812-fa522a80-6614-11eb-8511-7ce321b1fee2.png)

**Comment by simonbray** [comment]
Hi @ppxasjsm,

To elaborate a bit on Helena's answer, one of the central ideas of Galaxy is to allow users to perform analyses without being exposed to the kind of issues that you mention. Galaxy tools provide access to command line tools via a graphical interface. Dependencies are provided via Conda or in Docker/Singularity containers, so compilation is not required. (I agree rdock compilation is a real pain.)

What the user needs is access to a Galaxy server with the necessary tools installed. They can either set this up themselves - the Docker container mentioned above by Helena would be the easiest way - or, alternatively, use one of the public servers available, for example https://cheminformatics.usegalaxy.eu/. The latter is the easiest option if you just want to give the tutorial a quick try.

Here's an example of one of the rdock tools: https://usegalaxy.eu/?tool_id=rdock_rbdock

**Comment by hexylena** [comment]
Thanks for expanding on that @simonbray! that's a much more detailed answer.

**Comment by ppxasjsm** [comment]
@hexylena and @simonbray thank you both for your quick replies! This is super helpful. I had more of a look around and would love to contribute to the project. It is such a great training resource.

**Comment by bgruening** [comment]
@ppxasjsm welcome to GTN. If you like join us on https://gitter.im/Galaxy-Training-Network/Lobby

**Comment by simonbray** [comment]
@ppxasjsm that's great to hear - I sent you an email.
