### ISSUE TITLE
`make install` is too slow

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/training-material#2336]
Installing jekyll takes unimaginable amount of time. Perhaps using something like `gem install --no-ri --no-rdoc` might help here -> 
https://github.com/galaxyproject/training-material/blob/351236f23f47ec7d3038377714ff806e1d015510/Makefile#L45

**Comment by hexylena** [comment]
Those are good suggestions, the documentation is definitely not needed! We can add that.

**Comment by hexylena** [comment]
But also it's something you do once, or, once a year at most, we hadn't had any complaints thus far.
