### ISSUE TITLE
Circular dependency in prerequisite knowledge

### ISSUE THREAD

**Issue by ic4f** [galaxyproject/training-material#2351]
Most likely, this is a non-issue. Opening this just in case.
The Understanding Barcodes tutorial [points to](
https://github.com/galaxyproject/training-material/blame/154166b7c8623e9d8144e66467da1434bc2e2f31/topics/transcriptomics/tutorials/scrna-umis/tutorial.md#L82) the Plates, Batches, and Barcodes slides as a prerequisite. But those slides [point to](https://training.galaxyproject.org/training-material/topics/transcriptomics/tutorials/scrna-plates-batches-barcodes/slides.html#2) the Understanding Barcodes tutorial as a prerequisite.

**Comment by nsoranzo** [comment]
Ping @mtekman

**Comment by mtekman** [comment]
Oh whoops! Quickfix: https://github.com/galaxyproject/training-material/pull/2359

**Comment by shiltemann** [comment]
Thanks @ic4f and @mtekman !
