### ISSUE TITLE
Workflow for Proteogenomics 1 

### ISSUE THREAD

**Issue by assuntad23** [galaxyproject/training-material#2354]
In the course of testing for Smörgåsbord , I came across a few error swith the workflow for https://training.galaxyproject.org/training-material/topics/proteomics/tutorials/proteogenomics-dbcreation/tutorial.html

- The workflow fails because, in the Tabular-to-FASTA step, the "Title column" is blank (should be 1) and the "Sequence Column" is 2 (when it should be CustomProDB Merged Fasta).
- The workflow fails on the FreeBayes tool, with the following error: "unable to find FASTA index entry for 'chr10'
ERROR(freebayes): Target region coordinates (chr1 0 195471971) outside of reference sequence bounds (chr1 30427671) terminating.
unable to find FASTA index entry for 'chr11'
unable to find FASTA index entry fo"
- The workflow fails on the gffCompare step with the following error: "Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/shed_tools/toolshed.g2.bx.psu.edu/repos/galaxyp/gffcompare_to_bed/7e572e148175/gffcompare_to_bed/gffcompare_to_bed.py", line 132, in <module>
    __main__()
  File "/cvmfs/main.gala"

**Comment by assuntad23** [comment]
It's also worth noting that the tutorial assumes that the user will know to use the regex "Replace text in a specific column" for the Change the chromosome names in the Ensembl GTF to match a UCSC genome reference step. 

I feel like that should be more explicit.

**Comment by subinamehta** [comment]
Thank you @assuntad23 for testing our training. I tested the workflow but I couldn't replicate the Freebayes and gffcompare error in Galaxy(https://usegalaxy.eu/u/galaxyp/h/test) . However, I have provided a note regarding the "Tabular-to-Fasta" step in the GTN ( to specify column 1 as title). Also, I have added additional information regarding "Replace text in a specific column" regex statement.

**Comment by natefoo** [comment]
@subinamehta I think this is because the GTF used as input for StringTie in the tutorial is the original uploaded version and not the one we've manipulated the chromosome names of. I am working on a few clarifications in #2368 and mention it there.
