### ISSUE TITLE
Folder structure for training material

### ISSUE THREAD

**Issue by Stortebecker** [galaxyproject/training-material#238]
Hi.

I recently added [training material for proteomics](https://github.com/galaxyproject/training-material/tree/master/Proteomics). So far, all tutorials we had were based on Transcriptomics, so no subfolder structure was necessary. To avoid mixing of proteomics with transcriptomics, I created all tutorials in a subfolder `Proteomics`. Maybe also the Transcriptomics tutorials should be moved into a `Transcriptomics` subfolder. As more and more content is added, it otherwise gets hard to find what you are searching for.

Is a subfolder structure a problem for rendering the tutorials with Jekyll?

**Comment by Stortebecker** [comment]
@all Ping. Ping.

Restructuring the folder structure gets harder, the more material we add. And yes, I would volunteer to do the actual restructuring, as soon as we decided something definite.

**Comment by bgruening** [comment]
Please use Proteomics for all your training material for now.
