### ISSUE TITLE
Advanced Rule Builder Tutorial Misses use of Saved Rule Selector 

### ISSUE THREAD

**Issue by assuntad23** [galaxyproject/training-material#2392]
This ticket is to add information regarding the saved rule selector/recently used rules/history icon to the Advanced Rule Builder Tutorial. 

This can be done in the section called Building Matched Collections, since the current tutorial has users copy the previous step's JSON into the JSON builder.

**Comment by hexylena** [comment]
Yes! This would be a super nice addition to that tutorial.
