### ISSUE TITLE
Updates to JupyterLab Tutorial

### ISSUE THREAD

**Issue by assuntad23** [galaxyproject/training-material#2397]
This tutorial (https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/jupyterlab/tutorial.html) needs two updates:

1. Main/.org can now run Jupyter jobs, so the tips about how to access JupyterLab from main are not necessary.
2. At the end, there needs to be a step about clicking File > Shut Down. If you don't do this, the job will run indefinitely and you will not get the .pynb file output.

**Comment by nomadscientist** [comment]
On it!

**Comment by nomadscientist** [comment]
https://github.com/galaxyproject/training-material/pull/2500
BOOM! Pull-requested!
