### ISSUE TITLE
Minor updates to Galaxy 101 tutorial

### ISSUE THREAD

**Issue by ic4f** [galaxyproject/training-material#2398]
1. Locating Exons >> Hands-on: Upload SNPs and Exons: instructions mention outdated upload icon; should be changed to "Upload Data" button. Screenshot needs to be updated too.
2. The tutorial uses zenodo datasets (using UCSC is optional), so the results are reproducible. However, the results in the Analysis section are inconsistent with the results obtained from following the tutorial:
   - For the first 3 exons in your file, what is the number of SNPs that fall into that exon? The exons are correct, but my numbers were 2, 2, 4 (not 24, 24, 40) (see https://usegalaxy.org/u/ic4f/h/tutorial-galaxy-101)
     -  The solution lists “Common SNPs(151)”, however, I think that should be 153 (as per zenodo file link)?
   - Same goes for Hands-on: Sorting and Select the top five exons.
3. Recovering exon info >> Hands-on:
   - step 1: second instance of "Using column" should be "and column"
   - screenshot has incorrect header (extra columns with titles)
5. Convert your analysis history into a workflow: screenshot missing step 6 and 7

EDIT: Importing data through the UCSC browser logs out user has been an issue [at least since 02/2020](https://github.com/galaxyproject/galaxy/issues/9451). If that cannot be easily fixed on the Galaxy end, we need to make a note of it in the tutorial: following the optional steps is impossible without logging in after each upload and copying datasets between histories).

EDIT 2: The dataset in "Find exons with the most SNPs" contains 10 columns, not 12 (it's not a Galaxy UI bug).

EDIT 3: Run workflow on different data >> step 7: this requires an extra step: clicking expand to full workflow.

**Comment by gallardoalba** [comment]
I'll work on it.

**Comment by gallardoalba** [comment]
I think that it can be closed @bebatut.
