### ISSUE TITLE
Galaxy 101 for everyone - tiny text inconsistency

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/training-material#2400]
In [The Workflow Editor section](https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101-everyone/tutorial.html#the-workflow-editor) there are some parts where it mentions using `asterisks` to mark outputs as important but the screenshots seem more up-to-date and display a checkbox instead.

This was detected during the 21.01 release testing.

**Comment by hexylena** [comment]
Thanks! tagged paper cut for the cofest on thursday.
