### ISSUE TITLE
Using dataset collections - a bit outdated

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/training-material#2402]
The [Using dataset collections](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/collections/tutorial.html#retaining-proper-pairs) tutorial can be followed on 21.01 but there are some small issues:

- Most of the screenshots are outdated.
- There is a screenshot at the beginning of the [Retaining ‘proper pairs’ section](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/collections/tutorial.html#retaining-proper-pairs) that seems unrelated to the tutorial or, at least, it confuses me since the tool and the parameters don't match the explanation:
  ![image](https://user-images.githubusercontent.com/46503462/108875671-b5ab2500-75fd-11eb-82d7-a51524b492b6.png)
- The IGV file in the last step can be downloaded using Firefox. Using Chrome, the new tab closes automatically and the file doesn't download. I don't know if it is worth mentioning in the tutorial or if it working for others in Chrome.

**Comment by hexylena** [comment]
Unfortunately why we heavily discourage screenshots due to the outdatedness, but certain authors use them nonetheless.

It'd be great to get this updated if anyone has time, it's such a key feature to teach students.

**Comment by bernt-matthias** [comment]
Stumbled over the same thing and a few more:

- the screenshot is completely wrong .. just does not belong here
- `Filter SAM or BAM` is now `samtools view`

Also instead of mixing samtools and picard I would suggest 

- instead of MergeSamFiles from the Picard suite `samtools merge`
- also downsampling can be done with samtools view

**Comment by gallardoalba** [comment]
I'll work on it!

**Comment by gallardoalba** [comment]
> I'll work on it!

It seems that all the suggestions have been already fixed in:
- https://github.com/galaxyproject/training-material/pull/2722/files
- https://github.com/galaxyproject/training-material/pull/2738

It can be closed I guess @hexylena.

**Comment by hexylena** [comment]
I guess so! fantastic
