### ISSUE TITLE
Running example

### ISSUE THREAD

**Issue by guwek** [galaxyproject/training-material#242]
I am a new user to Galaxy and wanted to try out the example. It seems that the code should be

    docker run -d -p 8080:80 bgruening/galaxy-stable

instead of 

    docker run -d -p 8080:80 bgruening/docker-galaxy-stable

At least for me (Mac, Sierra, Docker 1.13.1) it works this way (and not the other way).

**Comment by bgruening** [comment]
@guwek nice to see you here. The main image is here: https://github.com/bgruening/docker-galaxy-stable/

This training material is currently under heavy construction and not all trainings do have a valid Docker image. It should be we just lacking time. How to extend a Image is described here in more dewtail: https://github.com/bgruening/docker-galaxy-stable/#extending-the-docker-image--toc
