### ISSUE TITLE
Build failing -

### ISSUE THREAD

**Issue by fubar2** [galaxyproject/training-material#2424]
I'm seeing this error:
```

Run gem install bundler
Successfully installed bundler-2.2.11
Parsing documentation for bundler-2.2.11
Installing ri documentation for bundler-2.2.11
Done installing documentation for bundler after 7 seconds
1 gem installed
Could not locate Gemfile
Error: Process completed with exit code 10.

```

Interesting note about deprecation in a preceding step:

```
0s
Run actions/setup-ruby@v1
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
------------------------
```
It's my fork - any suggestions on what I need to do to fix it or does the action need to be changed like the message suggests ?
From the readme at the migrate URL above seems that actions/setup may be deprecated and ruby/setup-ruby is needed - but that's not enough - still breaks.

**Comment by hexylena** [comment]
This is an issue specific to https://github.com/galaxyproject/training-material/pull/2423 and your fork, we can continue discussion there
