### ISSUE TITLE
htmlproofer should ignore all the html contents of topic docker subdirectories

### ISSUE THREAD

**Issue by fubar2** [galaxyproject/training-material#2427]
> Run bundle exec htmlproofer 

This failed in #2423 because there was an HTML file welcome.html designed for a docker Galaxy image in the docker subdirectory of a topic where there are links not found - style sheets and galaxy tours for example.

Changing the filetype to txt in the repo then back to html when it gets copied by the Dockerfile is easy enough now that I know but as @hexylena pointed out this should be properly fixed. 

Can htmlproofer be made aware that any directory called `docker` is off limits?

**Comment by hexylena** [comment]
Yes. Can you add it to your PR? You'll need to update the Makefile, and .github/workflows/ci.yml with the following:

```
,"/\/tutorials\/.*\/docker\//"
```

right after the node modules ignore. (i.e. `--file-ignore "/.*\/files\/.*/","/.*\/node_modules\/.*/","/\/tutorials\/.*\/docker\//"`) And in the future, if the build is failing for something that needs an ugly workaround, if you can leave the build failing it's more helpful to us to help fix the build process!

**Comment by fubar2** [comment]
Should that be 
 
"/.*\/tutorials\/.*\/docker\//"

so it's any tutorial subdirectory rather than:
,"/\/tutorials\/.*\/docker\//"

**Comment by fubar2** [comment]
Yeah, nah. You were right. 
I know aught about ruby regexps - thanks!
Will declare victory on this one....
