### ISSUE TITLE
The "Search Tutorials" function on the webpage doesn't seem to find some tools

### ISSUE THREAD

**Issue by AnnaSyme** [galaxyproject/training-material#2455]
Issue: A bug in the search function? or a suggested enhancement to the search function

Detail: On the webpage https://training.galaxyproject.org/training-material/  if I want to search the tutorials for a particular tool (e.g. Blast), there are no results found. However this is a tool that is used in some tutorials (e.g. https://training.galaxyproject.org/archive/2019-06-01/topics/genome-annotation/tutorials/genome-annotation/tutorial.html). 

Suggestion: I don't think this is necessarily a bug as some other tool searches seem to work. But perhaps there's a way to enhance the search function?

**Comment by hexylena** [comment]
Currently it only searches the metadata and not the whole tutorial. I've got a branch where it's opened up to completely full text search but it isn't merged yet. We can definitely resurrect that work and fix this :)
