### ISSUE TITLE
List interesting tutorials in different topics

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#2545]
Some tutorials would fit in different topics and it is sometimes difficult to choose where to put them.

Currently we recommend to tag these but people need to know about the tags. 
It would be nice to have these tutorials listed in several topics, but without duplicating them. 

Solutions:
- Symlink?
- Other solution?

**Comment by hexylena** [comment]
Could you provide some examples here? Symlinking would be pretty easy (but we'd have to watch out for duplicate search results / multiple urls with same content / being counted multiple times in e.g. stats pages).

It feels similar to the gcc training issue, we've got tutorials that fit in multiple topics and @shiltemann and I've discussed a couple times maybe not categorising them at all, instead tagging them, and having them listed under every tag. It would be a big change for the GTN but we could think of something similar here?

**Comment by hexylena** [comment]
would be fixed by proposal in https://github.com/galaxyproject/training-material/discussions/3264, closing in favour of moving discussion there
