### ISSUE TITLE
Subtopics for proteomics

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/training-material#2570]
Hey @foellmelanie @subinamehta what would you think of splitting up the proteomics tutorials into subtopics? We could provide some more structure and sub-categories to help learners find the topics that interest them.

It looks like this in the transcriptomics topics https://training.galaxyproject.org/training-material/topics/transcriptomics/ and I'm currently doing the same for the developer focused tutorials #2567 .

If you all have categories for those / short descriptions for the categories, I'd be happy to make a PR with that update.

**Comment by foellmelanie** [comment]
Hi @hexylena thanks for the suggestion and offering help! 
We indeed had the same thing in mind and I have already a list of categories and tags that the community agreed on. I will arrange it in a plain text document and send it to you soonish if you agree.

Thanks a bunch!
Melanie

**Comment by hexylena** [comment]
@foellmelanie oh that's fantastic news. plain text document works fine!

**Comment by foellmelanie** [comment]
I just paste it in here, I hope that's fine. Maybe @subinamehta can have a look and confirm that I got it all right.

**Comment by foellmelanie** [comment]
1) Introduction

 Start here if you are new to proteomic analysis in Galaxy.
 
"Introduction to proteomics, protein identification, quantification and statistical modelling"

2) Protein identification and quantification

These tutorials cover protein identification and/or label-free and label based quantification from data dependent acquisition (DDA) and data independent acquisition (DIA).

"database-handling"; tags: "DDA"
"protein-id-oms"; tags: "DDA"
"protein-id-sg-ps"; tags: "DDA"
"protein-quant-sil"; tags: "DDA"; "SILAC"
"labelfree-vs-labelled"; tags: "DDA"
"maxquant-label-free"; tags: "DDA", "label-free"
"MaxQuant and MSstats for the analysis of label-free data"; tags: "label-fee"
"DIA_lib_OSW"; tags: "DIA"
"DIA_Analysis_OSW"; tags: "DIA"


3) Postprocessing of proteomics data

 These tutorial cover statistical analyses and visualizations after protein identification and quantification. 

"proteome_annotation"; tags: "DDA", "human"
"biomarker_selection"; tags: "DDA", "human"
"DIA_Analysis_MSstats"; tags: "DIA"
"secretome-prediction"; tags: "human"


4) Special proteomics techniques

 These tutorials focus on special techniques such as N-terminomics and mass spectrometry imaging. 

"n-tails"
"mass-spectrometry-imaging-loading-exploring-data"; tags: "mouse", "imaging"


5) Multi-omics analyses

 These tutorials combine proteomics with other -omics technologies such as transcriptomics. 

"metaproteomics"; tags: "microbiome"
"metaquantome-data-creation"; tags: "microbiome"
"metaquantome-function"; tags: "microbiome"
"metaquantome-taxonomy"; tags: "microbiome"
"proteogenomics-dbcreation"; tags: "proteogenomics"
"proteogenomics-dbsearch"; tags: "proteogenomics"
"proteogenomics-novel-peptide-analysis"; tags: "proteogenomics"


6) Prediction of peptide properties

 These tutorials explain in-silico analyses of different peptide properties. 

"peptide-library-data-analysis"
"ml-modeling-of-anti-cancer-peptides"; tags: "cancer"

**Comment by subinamehta** [comment]
Thanks Melanie ... looks good...thanks for doing this
