### ISSUE TITLE
in preparation for the data hack at GCC

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/training-material#262]
@jennaj @MoHeydarian and all other Data Hackers. What would you like to see implemented in this repo to be suited as a target for the data hack?

I think this repo is kind of suited to collect ideas, workflows, descriptions from data hackers - which we turn into tutorials at some point. I'm start to wondering what is needed to make this happen.

**Comment by MoHeydarian** [comment]
I think the interests of the data hack and the GTN are quite similar and, as you point out, topics that we'll work on during the data hack can be made into tutorials (where appropriate). 

I think it will be very useful to have a place to generate, discuss, and log ideas prior to the data hack. If this is done in the training material repo, would we start a single issue to log these ideas? Or would this discussion be more organized if there were a separate repo for the data hack? I'm open to either, but we should make sure the discussions are organized and easy to find. 

(ping @yvanlebras @malloryfreeberg)

**Comment by jennaj** [comment]
Last year we created a high-level Master ticket in the primary galaxy repo, later moved that into bxlab once the hackathons started to get organized, and we linked in tickets from other repos as appropriate for the details. I think that worked well. One of those linked tickets could be another summary ticket in this repo with training-only related content (with more links out to specifics, etc).

Here is 2016 https://github.com/galaxyproject/galaxy/issues/2520

A 2017-specific hack fork hasn't been created yet. We could choose to update last year's fork (event level fork) and keep using it or create one that is more specific (event+year level fork). I am leaning towards the first but both have pluses.

Some choices ... what to others think?

**Comment by bgruening** [comment]
I guess we will also discuss this further during the hack in 1 week. Label is accordingly.

**Comment by bebatut** [comment]
I think this issue is outdated 😄

**Comment by bgruening** [comment]
How comes? ;)
