### ISSUE TITLE
Missing paragraph break in snippet boxes 

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/training-material#2622]
It seems that something in the code merges paragraphs in tips, see screenshot from https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-short/tutorial.html that uses the tip `faqs/galaxy/histories_create_new.md`

![Screenshot 2021-06-10 at 18-40-47 Galaxy Training A short introduction to Galaxy](https://user-images.githubusercontent.com/4924623/121573625-60b0e480-ca1d-11eb-9757-a9c571c38174.png)

**Comment by shiltemann** [comment]
This seems to have been fixed in https://github.com/galaxyproject/training-material/pull/2673 :+1: 

![image](https://user-images.githubusercontent.com/2563865/123633837-ffa94f00-d819-11eb-8339-25f35eca23e6.png)
