### ISSUE TITLE
provide closed captions for vimeo screencasts

### ISSUE THREAD

**Issue by martenson** [galaxyproject/training-material#264]
At least for the most prominent and important ones we should provide this accessibility improvement. Vimeo [supports](https://help.vimeo.com/hc/en-us/articles/224968828-Captions-and-subtitles) uploading of subtitle files.

our vimeo channel: https://vimeo.com/galaxyproject

Idea by ga77_Prof on [Twitter](https://twitter.com/ga77_Prof/status/835143749432930305)

**Comment by MoHeydarian** [comment]
I think this should be the case for all video tutorials by Galaxy. They are packed with information, but may be difficult for non-english speakers to follow at the (1x) pace of the video.

**Comment by bgruening** [comment]
:100: but how do we do this?
I would rather find a technical solution that goes along this way.
* create a Galaxy tour
* capture automatically the Galaxy tour as a video
* figure out howto use the text in the tour as subtitles etc ...
* update video frequently

**Comment by martenson** [comment]
Simply annotating the important screencasts/videos is 90% of what is needed here I think. This is fairly easy to do and a very friendly task for people starting with contributing to Galaxy.

@MoHeydarian This is important not only for non-English speakers but also for persons with hearing loss.

@bgruening I appreciate your 'once and for all' approach but I think it does not fit here. Once you throw in modifying of tours, updating videos, and maintaining video URLs this becomes fairly scary task as opposed to just annotation.

**Comment by erasche** [comment]
We have since removed all screencasts from the training materials repository and moved away from video based trainings completely given the inability to keep up with UI changes and the difficulty in updating them every time.

@martenson is this then complete / ok to close?

**Comment by martenson** [comment]
we still have the vimeo channel, but I guess we are not producing any more video content so closing is fine
