### ISSUE TITLE
Lint semantically import whitespace in diffs

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/training-material#2663]
Fully blank lines in diff bodies are not valid, each line must begin with `+`, `-`, or ` ` (space) or the syntax highligher will not recognize lines after blank lines to be diffs. Editors like to strip extra whitespace off the end of lines but it's necessary in diffs. Current cases were fixed using [quick and dirty scripts](https://gist.github.com/natefoo/4f9ce9717ed77f4e97347304de1d94b4) in #2662 but @hexylena would like to add proper linting for this.

xref: https://github.com/rouge-ruby/rouge/issues/1676#issuecomment-823115598

**Comment by hexylena** [comment]
fixed in #2662
