### ISSUE TITLE
Supporting data for Galaxy Introduction: From peaks to genes

### ISSUE THREAD

**Issue by apark229** [galaxyproject/training-material#267]
Hi, I was completing the tutorial for Galaxy Introduction: From peaks to genes on usegalaxy.org.  Under the tutorial section "Hands-on: Get new gene file from Data Library," I was trying to access the "Genomes + Annotations" folder but could not find it under Shared Data>Data Libraries.

**Comment by yvanlebras** [comment]
Hi, I saw discussion around putting all training material data on the usegalaxy.org 'shared data' section but this is not already made if I'm not wrong. Finally, training material data are often on Zenodo.... and for this tuto, readme file says ".. will be soon on Zenodo". So I think we have to wait... did you look at https://github.com/galaxyproject/training-material/tree/master/Introduction/input_data ?

**Comment by apark229** [comment]
Thank you for the link you provided! I was able to find the data set there under a different name.

**Comment by bgruening** [comment]
@apark229 sorry for the inconvenience. All data should be on Zenodo or any other DOI enabled storage. The references to a data library are to specific for a particular Galaxy instance and should be removed.
Sorry again.

**Comment by bebatut** [comment]
This issue has been fixed: there is no reference to the data library in the tutorial http://galaxyproject.github.io/training-material/topics/introduction/tutorials/galaxy-intro-peaks2genes/tutorial.html
