### ISSUE TITLE
Bad name for RNA-seq training Docker image ?

### ISSUE THREAD

**Issue by yvanlebras** [galaxyproject/training-material#268]
Hi everyone,

I found this mention to deploy a Galaxy training material RNA-seq oriented container : bgruening/galaxy-rna-seq-training but I'm not sure this image exists... The right Docker image is maybe bgruening/galaxy-rna-seq ?

**Comment by bgruening** [comment]
Mea culpa! The training-docker-image is just not created to far. it should inherit from the one you mentioined and add training material and a workflow

**Comment by bgruening** [comment]
@yvanlebras I have now the first one deployed. https://hub.docker.com/r/biocontainers/galaxy-rna-seq-training/
Let me know what you think and feel free to reopen!
