### ISSUE TITLE
Create a Tutorial for Workflow Reports

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/training-material#2707]
Requested during GCC 2021 by Anne Fouilloux.

(If this is an inappropriate place for this issue I can transfer it to galaxyproject/galaxy)

**Comment by wm75** [comment]
Seems very appropriate here :)

**Comment by shiltemann** [comment]
Thanks @jmchilton! Yes good idea to make issues for requested tutorials. I've started porting iReports for some of my users to workflow reports and have been meaning to create a tutorial based on one of them as well :+1:

**Comment by hexylena** [comment]
at least 13 people voted for this in remo, we definitely need someone to contribute their reports!

**Comment by cgirardot** [comment]
I frequently wondered how to use this feature so +1 from my side

**Comment by hexylena** [comment]
Fixed in #3478
