### ISSUE TITLE
Thank you very much for the tutorial, it was extremely helpful.

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/training-material#2731]
*moved from wrong location*

Thank you very much for the tutorial, it was extremely helpful. 

May I please ask you a quick question?
I have used the following parameters for DeSeq2 in galaxy.
Factor 1: Treatment
Factor level 1: CONTROL
Factor level 2: Treatment 1
Factor level 3 : Treatment 1
 
I wanted to make the following comparisons (and the corresponding plots). 
Control vs Treatment 1
Control vs Treatment 2
Treatment 1 vs Treatment 2
Control vs Treatment 1 + Treatment 2 combined

Would you please let me know if the factor and factor levels chosen are appropriate to make these comparisons?

Many thanks,
GG

_Originally posted by @GOPAKG in https://github.com/galaxyproject/training-material/discussions/1452#discussioncomment-1090027_

**Comment by bebatut** [comment]
They contacted me by email. I just answered them
