### ISSUE TITLE
Abstract for GCC17

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#275]
Hi all, 

We were thinking about submitting an abstract for GCC about the training material.

Here is the draft: https://docs.google.com/document/d/1vk246XMLL-BOZ9aVCi7nLZkNO_1-Z8Yz8dQuGuJkR38/edit?usp=sharing

If you want to be part, add yourself as author. Any feedback (specially on the English 😄 ) is welcome

Bérénice

**Comment by bgruening** [comment]
Ok, we submitted something to GCC and BOSC - let's hope the best! :)

Thanks @bebatut for all your effort!
