### ISSUE TITLE
Bug in feedback display

### ISSUE THREAD

**Issue by shiltemann** [galaxyproject/training-material#2755]
When opening the feedback for (among some others), "A short introduction to Galaxy", something funky happens with the rendering:

![gtn-feedback-quirk](https://user-images.githubusercontent.com/2563865/131679114-b0e93587-8830-4826-a25f-99c0c9bfc4f7.gif)

**Comment by bebatut** [comment]
I will investigate that.

I need also to check how it works with tutorials in spanish
