### ISSUE TITLE
Unable to undelete collection

### ISSUE THREAD

**Issue by ayaanhossain** [galaxyproject/training-material#279]
I was following [this](https://galaxyproject.org/tutorials/nt_rnaseq/) tutorial, and I deleted a collection of HISAT mapped reads. Later I wanted the collection back but didn't find an undelete option like those found for normal datasets.

**Comment by bgruening** [comment]
@ayaanhossain I will forward this to the Galaxy bug tracker. It seems to be a Galaxy issue and not related to training material.

**Comment by bgruening** [comment]
please see https://github.com/galaxyproject/galaxy/issues/3957
