### ISSUE TITLE
DNA Methylation Tutorial: Missing Data

### ISSUE THREAD

**Issue by tristancofer** [galaxyproject/training-material#281]
Hello all, 

I would like to run the [DNA Methylation data analysis](https://galaxyproject.github.io/training-material//MethylC-Seq/tutorials/methylation-seq) tutorial, but the MethylSeq_2017 data library is unavailable.

**Comment by bgruening** [comment]
@joachimwolff can you please upload these datasets to zenodo? Thanks!
@tristancofer we will work on this, sorry - everything still in progress! Thanks for your patience.

**Comment by tristancofer** [comment]
No problem. Thanks for the quick response!

**Comment by joachimwolff** [comment]
@dpryan79 You wanted to check the licence of the data if we can re-publish it and not violating something. If I have your ok I will upload the data.

**Comment by dpryan79** [comment]
@joachimwolff I can't find any details regarding redistribution on ArrayExpress (it's a public database, so it really shouldn't be an issue). I'll just send the authors an email and get an OK directly from them. Then all of our bases are covered :)

**Comment by dpryan79** [comment]
We have a very enthusiastic OK from the authors :)

> Thank you for contacting us regarding the use of our WGBS data as part of the training dataset for Galaxy. We are delighted that it will be used as such that it benefits the wider scientific community, and please do go ahead with it.

> Regards,

> I-Hsuan

**Comment by joachimwolff** [comment]
Thanks a lot @dpryan79.
@tristancofer I will upload the data today.

**Comment by bgruening** [comment]
@joachimwolff can you please add this link to the training? Thanks!
