### ISSUE TITLE
climate tutorials are not with workflows

### ISSUE THREAD

**Issue by miaomiaozhou88** [galaxyproject/training-material#2813]
it seems the climate tutorials are not with workflows? https://training.galaxyproject.org/training-material/topics/climate/. 
thanks!

**Comment by hexylena** [comment]
@annefou perhaps you have some histories that could be exported, or workflows already prepared that could be included?

**Comment by annefou** [comment]
Yes. We have workflows for
-  https://training.galaxyproject.org/training-material/topics/climate/tutorials/climate-101/tutorial.html in workflowhub.eu (https://workflowhub.eu/workflows/42)
-  https://training.galaxyproject.org/training-material/topics/climate/tutorials/fates/tutorial.html in workflowhub.eu (https://workflowhub.eu/workflows/65)

**Comment by hexylena** [comment]
Fantastic! I'll open a PR to import those back into the GTN. Thanks for the quick response @annefou!
