### ISSUE TITLE
Send announcements automatically to chat channels

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/training-material#2829]
We'd like to share cool news with the community whenever it happens, our primary method of communication is matrix and twitter (and matrix is easier to talk to, so we'll focus on that.)

We've got a couple category of announcements that should be shared:

- New news posts e.g. https://training.galaxyproject.org/training-material/news.html we'd like to post a short blurb of the news post, link, and the image if it's supplied.
- New slide videos that have been contributed
- New contributors, we'd like to recognise them!
- New tutorials
- New slides

It's pretty easy to send things to the matrix API

```bash
curl -XPOST -H "Authorization: Bearer $access_token" \
	-d '{"msgtype":"m.notice", "body":"Hello from '"$USER"'", "format": "org.matrix.custom.html", "formatted_body": "Hey <b>test</b>"}' \
	'https://matrix.org/_matrix/client/r0/rooms/!LcoypptdBmTAvbxeJm:matrix.org/send/m.room.message'
```

(where the access token will be in our github actions).

The announcements to be sent can probably be determined in the github action based on the current version of the site vs the one that is about to be deployed, i.e. did contributors.yaml change, were there new news posts, etc.

**Comment by Chinonyemildred** [comment]
Aw, I don't write python code yet. Is there any other way I can help....with your guidance if you don't mind. This is a fantastic idea

**Comment by hexylena** [comment]
Please don't wait on my portion, go ahead and write something that just generates the notes, the matrix announcement portion can be completely separate.

**Comment by hexylena** [comment]
Additionally please know that you can use this script to extract the frontmatter of any tutorial, slide, or news item as JSON, this can help you fill out the text of the announcements

```
$ ruby bin/extract-frontmatter.rb news/_posts/2021-03-01-gat.md
{
  "title": "Galaxy Admin Training Success",
  "tags": [
    "admin",
    "gat",
    "event",
    "pandemic",
    "remote-teaching"
  ],
  "link": "https://gallantries.github.io/posts/2021/02/01/gat/",
  "layout": "news"
}
```
