### ISSUE TITLE
RNA-seq: Introduction Tutorial

### ISSUE THREAD

**Issue by joepersi** [galaxyproject/training-material#283]
Hello,

I was completing the RNA-seq: Introduction tutorial and ran into a few issues which resulted in several tries before I could complete the tutorial. When running the TopHat command, in one instance my jobs sat in the History with an exclamation mark (!) for over a day before finally being killed with the following error message:
Remote job server indicated a problem running or monitoring this job.

When TopHat did run, I received an error message stating:
An error occurred setting the metadata for this dataset
Set it manually or retry auto-detection

I could not continue with the tutorial unless I clicked on the data set and selected auto-detection. The tricky part about this was that the error message was not visible from my History. I needed to click on the TopHat output for my collection of data to see that some or all of the metadata had not been properly detected. 

I enjoyed the tutorial, and appreciate the work of those involved in putting it together and keeping it user-friendly.

Thanks,
Joe Persichetti

**Comment by bgruening** [comment]
@joepersi thanks a lot for you review! This is certainly a bug in Galaxy or the instance you are running it. We will look in it! We will work in the next weeks intensively on the training material, so drop by if you are interested in more training :)
