### ISSUE TITLE
Make the author list in tutorial more welcome to contribution

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#2835]
The author list on the top of the tutorial may feel like set in the stones and people may feel like their names could be there if they contribute:

![image](https://user-images.githubusercontent.com/1842467/136917471-dc0112ac-6ee3-4399-bd3d-31f050d0dc6c.png)

What could we do to make the author list more welcome to contribution? Adding a "+" / you/next contributor to show that new contributors are welcome there?

**Comment by bebatut** [comment]
I had more in mind a greyed out "your name here". Not sure about clickable. What should it link to?

> Or we could add CTA below the Authors - "Interested in contributing to this tutorial" and "become an author" link below it.

Such links would be useful definitely below the authors.

> This is what I could think of right now but there are several other ways to spur people to contribute. 

Do you have other suggestions there?

**Comment by bebatut** [comment]
Do you want to try to implement something in this direction?

**Comment by bebatut** [comment]
The structure of the layouts and includes is indeed quite confusing. Feel free to reach me on Gitter/Matrix if you need help

**Comment by Chinonyemildred** [comment]
I didn't link this issue so it did not automatically close. @bebatut any help with this please?

**Comment by bebatut** [comment]
Nice catch @Chinonyemildred. Thanks. I close it now.
