### ISSUE TITLE
Add video to all tutorials

### ISSUE THREAD

**Issue by Chinonyemildred** [galaxyproject/training-material#2837]
Hi, I have been able to go through the tutorials under 'Introduction to Galaxy Analyses', [https://training.galaxyproject.org/training-material/topics/introduction/](url) and I observed that only one video (I stand to be corrected) has a video to accompany the step by step tutorial.

Galaxy 101 has a video [https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101/tutorial.html](url)

But the rest don't: [https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101-everyone/tutorial.html](url)
[https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-reproduce/tutorial.html](url)
[https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-strands/tutorial.html](url)
[https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-ngs-data-managment/tutorial.html](url)

While they have screenshots of the screens accompanying the step by step instructions, a video will help anyone, especially beginners and non-professionals flow with the instructions.

I also observed a feedback from one of such tutorials stated, "Maybe a video at the end doing(showing) all this". I also empathize with the frustrations and confusion that this missing feature made the users who dropped feedback feel.

It'll be important to make our community not just accessible but inclusive as well: taking note of the different kinds of people who will be using the tutorials. 

For instance, a person with dyslexia or vision problems may not be able to follow the instructions because the screenshots are quite crammed up or the texts are not so legible. A video showing the steps can give such persons a better learning experience.

And in making the learning experience better for them, we are making the experience better for everyone.

**Comment by otatadeabigail** [comment]
I agree. While going through the text tutorials, I thought about the same thing. A step-by-step video tutorial would indeed be explicit and easy to understand. I like you last phrase 'better experience for everyone".

**Comment by otatadeabigail** [comment]
This looks like an interesting project to work on.

**Comment by hexylena** [comment]
Hi @Chinonyemildred @otatadeabigail we have another avenue through which we are doing this. We like the idea, we're going to do it, but it is not a good project to start hacking on I'm afraid.

We have a large repository of videos https://www.youtube.com/playlist?list=PLNFLKDpdM3B_3M7i8fQ3rH_sax6rmAsyz

>  add extra metadata with the tutorial with links to videos, who recorded it and when

I don't want to put the metadata in the GTN, we've got it externally as a yaml file, and we can know there which tutorial a set of videos is related to.


> display the link to video with a drop-down button in the top box of the tutorial

yeah, exactly, we'll show  it in a dropdown eventually.

**Comment by Chinonyemildred** [comment]
> > As a temporary 'fix', can the link to the videos be added to the tutorial page? So that while the big project is being worked upon, users can still have better learning experience.
> 
> I understand the goal, but I don't want to mislead students and have them asking
> 
> > oh no where did the videos go
> 
> when we later fix it properly. I think personally I would rather keep it in this state for another month or two until we can get the video library integrated, and then users don't have confusion over why the training materials are changing and where to find the videos.

Okay, the video library is superb. Better to have that, thank you so much for your input :)

**Comment by Chinonyemildred** [comment]
I'm really glad we have our GTN video library now #3030 , I'll close this issue right away. Thank you so much!❤❤❤
