### ISSUE TITLE
Some spelling error needs correction

### ISSUE THREAD

**Issue by otatadeabigail** [galaxyproject/training-material#2841]
While reading, I noticed some minor spelling and grammar errors that could use correction.[Contributing to Galaxy training ](https://training.galaxyproject.org/training-material/topics/contributing/) 
![Screenshot_20211012-130700](https://user-images.githubusercontent.com/78880128/136954946-e25ed1a6-bf8b-41e0-9936-eb2f50d83bf6.png)
![Screenshot_20211012-130745](https://user-images.githubusercontent.com/78880128/136954953-622e58a9-87c0-43eb-b672-67840dc6872c.png)

**Comment by bebatut** [comment]
@otatadeabigail do you want to fix this issue? The source can be found here: https://github.com/galaxyproject/training-material/blob/main/topics/contributing/metadata.yaml

**Comment by hexylena** [comment]
Fixed in #2845
