### ISSUE TITLE
Not able to view scatterplots directly without downloading

### ISSUE THREAD

**Issue by 1-creator** [galaxyproject/training-material#2862]
tutorial:Galaxy 101 for everyone
site: https://usegalaxy.org/
operating system : linux(ubuntu)
browser :firefox
tool:Scatterplot w ggplot2
my history : https://usegalaxy.org/u/1-val/h/galaxy-101-for-everyone

![Screenshot 2021-10-18 at 11-03-20 Galaxy](https://user-images.githubusercontent.com/61587290/137695741-bd7e5b21-796d-43ff-abdc-0b7e75ee876c.png)

When trying to visualize dataset features with two-dimensional scatterplots i am getting the following error when i try viewing my output directly without  downloading it
        
        options(show.error.messages=F, error=function(){cat(geterrmessage(), file=stderr()); q("no",1,F)})

        loc <- Sys.setlocale("LC_MESSAGES", "en_US.UTF-8")
    

          library(ggplot2)

        #Choose between automatically scaled x and y axis or user defi

**Comment by bebatut** [comment]
Could you share your history so we can have a look? Thanks
