### ISSUE TITLE
Linking workflows in the tutorial table

### ISSUE THREAD

**Issue by Stortebecker** [galaxyproject/training-material#287]
Hejhej, 

I added GalaxyP workflows for my tutorials (e.g. https://github.com/galaxyproject/training-material/tree/master/Proteomics/workflows/database-handling). Now I wonder how to link those at the central Readme (https://github.com/galaxyproject/training-material/tree/master/Proteomics/README.md).

It would be nice to have an icon for workflows, just like the :book: for the tutorials. What about :package: or :zap: ?

Greetings, Flo

**Comment by Stortebecker** [comment]
The workflows should maybe even be visible in the GitHub pages table. Also, I added workflows that do not belong to a tutorial (yet). Adding a new "Workflow" column to the GitBug Page table would allow to link also these.

**Comment by Stortebecker** [comment]
Besides, two of my workflows do not need any input data. It would be great to be able to leave out the 📁  icon, if there are not input data.

**Comment by bgruening** [comment]
@Stortebecker can you think of any use-case where you don't have any inpput dataset?

**Comment by Stortebecker** [comment]
One use-case is my [tutorial on database handling](https://galaxyproject.github.io/training-material/topics/proteomics/tutorials/database-handling/tutorial.html)

**Comment by bebatut** [comment]
@Stortebecker do you think that this is still an issue?

**Comment by Stortebecker** [comment]
@bebatut I think it would still be useful to be able to access workflows directly from the github.io/topics page.
