### ISSUE TITLE
Tools not showing up (getting proposed) when searched

### ISSUE THREAD

**Issue by mylestande** [galaxyproject/training-material#2884]
One challenge while using the platform is the inability for tools show up first / rank higher as they are searched for in the Tools Panel on the leftmost part of the Galaxy Interface. 'FastQC' for instance, when searched for in the Tools Panel, does not show up first even after the entire search phrase is typed out. 'Filter by quality' too when searched for, ranks fourth. Newbies and people who generally lack patience might find it a tad difficult to continue on with the analyses given the time they have to use to search for the tools they require.

![filter-by-quality-search](https://user-images.githubusercontent.com/38287577/137975050-456a6d45-fcf3-4cce-922c-507f0366bbe7.png)

**Comment by bebatut** [comment]
There is currently work to improve the tool search in Galaxy. But it is not an easy task

To help learners, we try to add in all tutorials link to tools on the server they are currently using. Please check the GIF at https://training.galaxyproject.org/training-material/topics/contributing/tutorials/create-new-tutorial-content/tutorial.html#tool-links for more information about this feature.

**Comment by hexylena** [comment]
This has been an ongoing issue for years in Galaxy, and we do index by a significant number of tool attributes, but the search problem is quite quite difficult :( We've been tracking progress on this issue here galaxyproject/galaxy#2272
