### ISSUE TITLE
Incorrect image in ChIP-seq tutorial

### ISSUE THREAD

**Issue by vijaymp38** [galaxyproject/training-material#289]
The image below the option 'Motif Tools → MEME' is an incorrect repeat of the image that is below 'FASTA Manipulation -> Filter sequences by length'. It has to be replaced with with correct one depicting the screen for MEME.

**Comment by bgruening** [comment]
Thanks for your report, we will fix that during our upcoming contribution fest!

**Comment by bebatut** [comment]
I think this issue has been fixed: I can not find it 😄
