### ISSUE TITLE
RNAseq:Introduction error message

### ISSUE THREAD

**Issue by amt5284** [galaxyproject/training-material#291]
"An error occurred setting the metadata for this dataset
Set it manually or retry auto-detection"
I was unable to view spliced alignments produced by TopHat
https://usegalaxy.org/u/amt5284/h/final-proj---tindall
Thanks!

**Comment by bgruening** [comment]
On which Galaxy instance is this happening? If you rerun this tool again, do you get the same error?

**Comment by bebatut** [comment]
I am closing this issue. @amt5284 if you have still the error, please open a new issue
