### ISSUE TITLE
Tutorials' Feedback Form

### ISSUE THREAD

**Issue by rahmot** [galaxyproject/training-material#2923]
All this while, I have been trying to leave feedback after each tutorial but whenever I click the "how it went" link, it redirects to the page where we have collated feedback from students. I was hoping to see a form, which I do see but thought it was a screenshot.

![feedback form](https://user-images.githubusercontent.com/39836912/138554776-50c08aea-4444-42fa-b2b0-cd5c9ba5edf5.png)

Fortunately, I raised this issue during the papercut call and I was shocked when I heard the form image isn't a screenshot but an actual form. I think this is quite confusing and so many others might have the same thoughts as mine. 

We can tweak it a bit by adding a simple sentence such as this "As an individual or student click the form image below" above the form. This will increase the number of feedback we receive from students, hopefully. What do you think?

**Comment by hexylena** [comment]
fixed in #2944
