### ISSUE TITLE
Galaxy-intro-strands tutorial format 

### ISSUE THREAD

**Issue by sandygudie** [galaxyproject/training-material#2926]
Hi i went through the tutorial for [Introduction to Genomics and Galaxy ](https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-strands/tutorial.html ) and i observed that:
- some hands on do not follow the right format . Example
![image](https://user-images.githubusercontent.com/54219127/138674949-ed263cf5-180a-4099-9095-ba6f8a5bf69e.png)

- incorrect image guide and icon. 
![image](https://user-images.githubusercontent.com/54219127/138676195-c8b33eda-99b0-43cd-bfe1-7db4842e8a14.png)

i will like to work on this

**Comment by hexylena** [comment]
Should be fixed in referenced PRs.
