### ISSUE TITLE
Incorrect labels in tutorial for ChIP-Seq data analysis 

### ISSUE THREAD

**Issue by HengyeChen** [galaxyproject/training-material#293]
I have run a ChIP-Seq tutorial for anton's BMMB554 class. In the tutorial "Identification of the binding sites of the T-cell acute lymphocytic leukemia protein 1 (TAL1)", the whole process works well, however the labels and names of files were not described very clear. And in step 10, according to the settings in computeMatrix, the left two heatmaps in the last heatmap plot should be G1Es and the right two should be Mks.

**Comment by bgruening** [comment]
Thanks for your report, we will fix that during our upcoming contribution fest!

**Comment by bebatut** [comment]
I think this issue is also addressed in #456
