### ISSUE TITLE
Change "master" branch to "main" in Contributing with GitHub via command-line tutorial 

### ISSUE THREAD

**Issue by Ksenia2102** [galaxyproject/training-material#2932]
There are several places where main branch still called master. So now we facing the situation where at some parts it called main and at others master. This can be confusing for new users. 

[Tutorial](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/github-command-line-contribution/tutorial.html)

Parts where problem occur (pointed with red arrows): 

![2021-10-25_16-33-13](https://user-images.githubusercontent.com/57745661/138706552-fc4c1f86-7c0e-45f7-b805-902e7c89c966.png)

![2021-10-25_16-34-42](https://user-images.githubusercontent.com/57745661/138706686-df5ad21f-345c-41fa-9631-dd2287827a4f.png)

![2021-10-25_16-35-52](https://user-images.githubusercontent.com/57745661/138706712-7b46f802-1edf-4778-8378-988913408c91.png)

![2021-10-25_16-36-53](https://user-images.githubusercontent.com/57745661/138706739-743e549b-2afc-4f55-b3c8-6498299f1209.png)

![2021-10-25_16-38-15](https://user-images.githubusercontent.com/57745661/138706747-c263e078-7df6-415d-93be-dcb41fc18fd7.png)

**Comment by hexylena** [comment]
Fixed in referenced PR
