### ISSUE TITLE
Screen-shot for ChIP-seq-FASTA manipulation incorrect

### ISSUE THREAD

**Issue by MehreenRuhi** [galaxyproject/training-material#294]
The screenshot to explain FASTA manipulation → Filter sequences by length is a repeat of the step Fetch Alignments/Sequences → Extract Genomic DNA. 

Also, in the line "In this tutorials we will use MACS2 peak caller" tutorial should be singular.

**Comment by bgruening** [comment]
Thanks for your report, we will fix that during our upcoming contribution fest!

**Comment by bebatut** [comment]
This duplication has already been fixed: I can not see it anymore in http://galaxyproject.github.io/training-material/topics/chip-seq/tutorials/tal1-binding-site-identification/tutorial.html
