### ISSUE TITLE
Sequence analysis: Link doesn't work Sequence analysis(Quality Control Tutorial)

### ISSUE THREAD

**Issue by Ksenia2102** [galaxyproject/training-material#2960]
Link to FAQ doesn't work. 

Due to feedback: user wanted to use some help and it shows blank white screen. 
If we have a FAQ section it should be eather working or removed.

[Tutorial](https://training.galaxyproject.org/training-material/topics/sequence-analysis/tutorials/quality-control/tutorial.html)

Where to find the link:
![2021-10-30_17-28-34](https://user-images.githubusercontent.com/57745661/139537273-7dbb0cb7-def5-4686-9252-8a5ea3409ce0.png)

[Empty link](https://training.galaxyproject.org/training-material/topics/sequence-analysis/faqs/)

What the link shows:
![2021-10-30_17-29-04](https://user-images.githubusercontent.com/57745661/139537285-e1ce2996-a504-47a6-ad1b-5f3ddcbcfed3.png)

**Comment by saritadc** [comment]
@Ksenia2102 can I work on this issue?

**Comment by bebatut** [comment]
Hi. This is expected. Please see the content of #2942

We have collected a lot of tutorial level FAQs that are not yet integrated, but fewer topic level FAQs. Perhaps we will someday update the template to hide the topics without FAQs currently.
