### ISSUE TITLE
Missing FAQs dedicated pages for different topics

### ISSUE THREAD

**Issue by mariipia10** [galaxyproject/training-material#2967]
While writing the blog post about outreachy's different communities I wanted to access the different FAQs to get a better insight and be able to describe the topic with my own words but I found out some topics do not have a FAQs dedicated page with data  (It states that each tutorial has it's own FAQs but what if I just wanted to do access the overall topic FAQs?

[Here's  the URL](https://training.galaxyproject.org/training-material/faq) where i checked from and i found out all pages are missing with the exception of **Assembly, Visualisation, Galaxy Server administration, Development in Galaxy and Contributing to the Galaxy Training Material**  

See for e.g some empty ones
- [Introduction to Galaxy Analysis](https://training.galaxyproject.org/training-material/topics/introduction/faqs/)
- [Climate](https://training.galaxyproject.org/training-material/topics/climate/faqs/)
- [Computational Chemistry](https://training.galaxyproject.org/training-material/topics/computational-chemistry/faqs/)
- [Ecology](https://training.galaxyproject.org/training-material/topics/ecology/faqs/ )

**Comment by bebatut** [comment]
Hi. This is expected. Please see the content of #2942

We have collected a lot of tutorial level FAQs that are not yet integrated, but fewer topic level FAQs. Perhaps we will someday update the template to hide the topics without FAQs currently.
