### ISSUE TITLE
[Template / CSS] "Add Contributions!" not aligned with other authors in slides

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#2970]
![image](https://user-images.githubusercontent.com/1842467/139808629-b171be9f-054d-4508-aaed-b5a4ad390ebc.png)

**Comment by millen2223** [comment]
@bebatut can I try to correct it? I think it might fix it with properties:
```
    white-space: nowrap;
    display: inline-flex;
    flex-direction: row;
    align-items: center;
    border-radius: 1em;
    border: 1px solid #b7daff;
    padding-right: 0.5em;
    margin: 0.2em;
```

It seems to happen when "Add Contibutions!" is on the same line with other contributors
![image](https://user-images.githubusercontent.com/87771278/139835396-e0362e81-7678-4467-b2ad-c5812258aa5c.png)
![image](https://user-images.githubusercontent.com/87771278/139835530-db3d8348-18f9-4769-a5f4-2938ce897d70.png)

**Comment by millen2223** [comment]
before 
![image](https://user-images.githubusercontent.com/87771278/139837975-a72f3660-ca41-4dcb-9e19-64ebdbc37789.png)

after
![image](https://user-images.githubusercontent.com/87771278/139837807-e1e23703-5f68-4b16-bc24-f78002ff032a.png)

**Comment by hexylena** [comment]
I can have a look at this next week. Do you want to make a PR to the assets/style/main.css and ping me @millen2223 ?

**Comment by millen2223** [comment]
@hexylena I would be happy to make PR, thank you!
