### ISSUE TITLE
Support contributors on the FAQs

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/training-material#2973]
These are full fledged pages now, we could recognise all of the contributors to individual FAQs. This would help recognise newcomers to the GTN who might be contributing to one of those as an easy way to get started.

To do this one would need to:

- Add an `contributors:` field to the FAQ pages
- Update `_layouts/faq.html` to include the contributor badges (see _layouts/tutorial_hands_on.html for an example)

Anyone is welcome to work on this! Just write that you are here and open a PR with your changes. We don't need to update all past FAQs to start with, we can do that later (and it won't be easy, we'll have to dig through the git history for that.)

**Comment by saritadc** [comment]
@hexylena I want to work on this.

**Comment by millen2223** [comment]
@hexylena, me too :)

**Comment by Ezichi-Fav** [comment]
can I collaborate too?

**Comment by saritadc** [comment]
> @hexylena I want to work on this.

@hexylena  can you have a look on this PR https://github.com/galaxyproject/training-material/pull/2980
