### ISSUE TITLE
Unicycler assembly of SARS-CoV-2 genome with preprocessing to remove human genome reads tutorials seems to have some codes visible on the user interface

### ISSUE THREAD

**Issue by Ezichi-Fav** [galaxyproject/training-material#2991]
I noticed the Unicycler assembly of SARS-CoV-2 genome with preprocessing to remove human genome reads tutorials have some codes visible on the interface. I have reloaded the page severally to check if its network but it returns the same. Please can mentors check on their own end too. If that is the actual case, I would love to resolve it but I will need help and directions on what to do because I am still grooming my skills on using markdown.

**Comment by Ezichi-Fav** [comment]
Please has this been confirmed by anyone yet?

**Comment by hexylena** [comment]
> have some codes visible on the interface

could you please explain a bit more by what you mean here? Screenshots are always helpful for us to understand!

**Comment by Ezichi-Fav** [comment]
I'm sorry for the late reply. I have attached an image from the page I saw.
However, I checked the site again. I think it has been resolved because the
link route has changed. The link below is where I found the error.
https://training.galaxyproject.org/training-material/topics/assembly/tutorials/assembly-with-preprocessing/slides-plain.html

**Comment by hexylena** [comment]
Oh! Yes, it is a known issue that CSS classes used in the slides are displayed on that screen. We have no way of removing them currently. It's a bit unfortunate, but, this interface was meant mostly for accessibility reasons, having a plain text interface that's a bit easier for screenreaders to navigate. Someday I'll fix that but it will take some time I fear.
