### ISSUE TITLE
Improve Navigation to view tutorial materials in other languages.

### ISSUE THREAD

**Issue by Chinonyemildred** [galaxyproject/training-material#3002]
In the tutorial feedback issue opened by @shiltemann , I noticed a user made this comment: _"I think you need to introduce a bit of other languages because some participates do understand English but preferably native languages will make it easier for them to understand. thank you"_

I use the GTN library a lot and I know that asides the Spanish and other curated translations, there is a google translator embedded in the training but users like this person may not be aware because they are not directed to it properly.

I want to add some lines to improve this navigation to improve non-English speaking user experience.

**Comment by hexylena** [comment]
We're open to your suggestions! I've thought about putting one one of the translation icons in the navigation bar that could link to google translate to make it easier to find? 

![image](https://user-images.githubusercontent.com/458683/140744181-df59b99f-c557-4aee-936b-e3d0065a92e9.png)

**Comment by Chinonyemildred** [comment]
Great idea! This can automatically translate the GTN library, starting from the homepage.

I was thinking of adding an explanatory line like, _"you can view the tutorial materials in your language by clicking the drop down icon beside the hands-on icon."_
![Screenshot_20211108-141220](https://user-images.githubusercontent.com/82679007/140750856-da85cb52-a770-48e2-8970-f309bb704b43.png)

And then instead of **and more!** We edit it to **More Languages**. It's a more precise call to action

What do you think?

**Comment by Chinonyemildred** [comment]
We can have all three....the icon at the navigation bar, the explanatory line and the precise CTA just incase any one is missed, the user can still find help.

Is that okay?

**Comment by hexylena** [comment]
> , "you can view the tutorial materials in your language by clicking the drop down icon beside the hands-on icon

where would you think to put this?

Otherwise yes the other two sound good!

**Comment by Chinonyemildred** [comment]
I was thinking of adding it in italics to the subtitle here
![Screenshot_20211108-164032](https://user-images.githubusercontent.com/82679007/140772602-def3d6f8-c8c0-4b2f-a426-1215798a49f3.png)

But then again it may mean adding it all the tutorial topics page...that is, Climate,Assembly, and co

**Comment by hexylena** [comment]
I think that's ok yeah. Please feel free to go for it, adding it to all three places sounds good!

**Comment by Chinonyemildred** [comment]
Great, I'll do that❤❤

**Comment by Chinonyemildred** [comment]
Hi, I tried running the forked repo in gitpod today and I keep getting the error `make***no rule to make target 'metadata/swagger.yml', needed by 'api/swagger.json'. stop.` when I run the `make serve-gitpod` command.

How do I rectify it please?

**Comment by hexylena** [comment]
Ahh it was an error on my end. Could you please replace `swagger.yml` with `swagger.yaml` everywhere in the Makefile? That would be very helpful!

**Comment by Chinonyemildred** [comment]
> Ahh it was an error on my end. Could you please replace `swagger.yml` with `swagger.yaml` everywhere in the Makefile? That would be very helpful!

Okay, I'll do it

**Comment by Chinonyemildred** [comment]
Please check the file, if it worked. I edited it from my repo and merged the main

**Comment by Chinonyemildred** [comment]
This is what happened (the screenshot). How do I pull request the GTN repo please?
![Screenshot_20211110-141354](https://user-images.githubusercontent.com/82679007/141119767-e7ad2407-a5dc-4e6f-baef-53995561c3c0.png)

**Comment by Chinonyemildred** [comment]
Thank you so much for your help @hexylena, I'll close this now.
