### ISSUE TITLE
Cambridge Training Hackathon

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/training-material#301]
A few issues that can be addressed during the hackathon are labeled with [`Contribution fest`](
https://github.com/galaxyproject/training-material/labels/Contribution%20fest) or [`help-wanted`](https://github.com/galaxyproject/training-material/labels/help-wanted)

A few discussion that would be great to trigger during the hack are here: https://github.com/galaxyproject/training-material/labels/discussion

A few things to work on ordered by topic:
MethylC-seq: https://github.com/galaxyproject/training-material/labels/methylc-seq
ChIP-sq: https://github.com/galaxyproject/training-material/labels/chip-seq
Exome-seq: https://github.com/galaxyproject/training-material/labels/exome-seq
RNA-seq: https://github.com/galaxyproject/training-material/labels/rna-seq

Moreover, we tried to use GitHub projects, so please also have a look at: https://github.com/galaxyproject/training-material/projects

We will also communicate over [gitter](https://gitter.im/Galaxy-Training-Network/Lobby) and will have a hangout for everyone to join remotely.

Link to the hangout: https://hangouts.google.com/call/lrnciszza5hfxpmh567ontp24yy

xref #304

**Comment by bebatut** [comment]
Cambridge hackathon took place in May
