### ISSUE TITLE
User interface: Operations of multiple datasets button unalligned with All/None buttons, makes menu options difficult to read

### ISSUE THREAD

**Issue by mariipia10** [galaxyproject/training-material#3010]
When working with Galaxy following the tutorial titled [Using dataset collections](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/collections/tutorial.html#processing-data-organized-as-a-collection) I've noticed that when my designed language is in Spanish as the translation for "For all selected" is longer in the button doesn't follow the same height as the others right next to it. 

This affects the menu display when clicking the button as the options aren't visible 

![weird_ui_spanish](https://user-images.githubusercontent.com/92181987/140973164-a217fb1e-312b-4dcc-a30a-1f6a584b2d6e.gif)

I'd  maybe expect the button to either go below the All/None buttons and the menu to open to the right side or adapt to the history div size

**Comment by hexylena** [comment]
This issue has been registered recently in the Galaxy repository https://github.com/galaxyproject/galaxy/issues/12822 Thanks for submitting the issue! Sorry it's still not fixed :(

**Comment by mariipia10** [comment]
No biggie @hexylena ,thanks for the heads up!
