### ISSUE TITLE
FAQ Page for tutorials is empty

### ISSUE THREAD

**Issue by rahmot** [galaxyproject/training-material#3015]
One feedback received on the Quality Control tutorial mentioned that "Frequently asked questions inclusion would help. Link does not work". Then I decided to confirm if it is only this tutorial that has a blank FAQ Page, but several other tutorials' FAQ Page are also empty.

How does the FAQ Page work? Does it auto-generate questions and answers based on the questions asked in the Gitter channel and Help forum and the responses received? I guess we should disable the link if the page is empty or find a solution to that. What do you think?

**Comment by hexylena** [comment]
Please see the content here, it is expected https://github.com/galaxyproject/training-material/issues/2942

The FAQs are manually curated, e.g. https://training.galaxyproject.org/training-material/topics/metagenomics/tutorials/mothur-miseq-sop/faqs/ 

It is an idea to hide it but it will be some effort to do that, and maybe people don't know they can add FAQ entries then, we want that feature to be visible and people to contribute questions there based on their time teaching courses.

In fact we have a huge set of FAQ documents from the past events e.g. https://docs.google.com/document/u/1/d/e/2PACX-1vTfNT2qS2Yb7qTAcnOFrMWwE_aPPUuYJJ0hdjw5gqV_JtMUWQ3NSkr6qAdrmF2EUGBBzTL8wFiILz8B/pub (you can find them here https://galaxyproject.org/events/gcc2021/training/science-track) that need to be migrated into the GTN

**Comment by rahmot** [comment]
Oh, thanks for the clarification! I would have loved to help hide it, but since it will take some effort for experts to do that, I will spend forever on it. 

How can people contribute questions besides feedback? I haven't seen such a link.

How can the FAQ document be migrated into the GTN?

**Comment by hexylena** [comment]
> How can people contribute questions besides feedback? I haven't seen such a link.

This is not really something for students or people doing training to contribute, instead something for teachers/trainers folks to add. Either through seeing the question asked multiple times in Gitter, or having an FAQ document like the GCC event and collecting common questions.

> How can the FAQ document be migrated into the GTN?

Great question! it's quite easy. So for example https://docs.google.com/document/u/1/d/e/2PACX-1vSVFOV1C6hqMPGIpZ1qeOo6t-ubjaWbtsGSTMH9TwNlvfqZrP48i0_7_Xk5rxmY7g2CroOF1dNIyfMY/pub to take one faq document as example. These are questions over Single Cell RNA-Seq, so we would add them as FAQs in the transcriptomics topic. So inside https://github.com/galaxyproject/training-material/tree/main/topics/transcriptomics/faqs we would add an FAQ file like this:

**Original**

Q: Can RNA-seq techniques be applied to scRNA-seq?
A: The short answer is ‘no, but yes’. At the beginning this was impossible due to the over-prevalence of dropout events (“zeroes”) in the data complicating the normalisation techniques, but this is not so much of a problem any more with newer methods.

This would then be converted to an **FAQ Version**

```markdown
---
title: Can RNA-seq techniques be applied to scRNA-seq?
area: scRNA
box_type: tip
layout: faq
---

The short answer is ‘no, but yes’. At the beginning this was impossible due to the over-prevalence of dropout events (“zeroes”) in the data complicating the normalisation techniques, but this is not so much of a problem any more with newer methods.
```

**Comment by rahmot** [comment]
> This is not really something for students or people doing training to contribute, instead of something for teachers/trainers folks to add. Either through seeing the question asked multiple times in Gitter, or having an FAQ document like the GCC event and collecting common questions.
> 
Okay, I got that now. Thanks!
 
> Great question! it's quite easy. So for example https://docs.google.com/document/u/1/d/e/2PACX-1vSVFOV1C6hqMPGIpZ1qeOo6t-ubjaWbtsGSTMH9TwNlvfqZrP48i0_7_Xk5rxmY7g2CroOF1dNIyfMY/pub to take one faq document as an example. These are questions over Single Cell RNA-Seq, so we would add them as FAQs in the transcriptomics topic. So inside https://github.com/galaxyproject/training-material/tree/main/topics/transcriptomics/faqs we would add an FAQ file like this:
> 
Cool! Thanks for the vivid explanation and example. I will work on this.

**Comment by millen2223** [comment]
@rahmot I wanted to say thank you to you for helping me to understand pull requests a bit better!

**Comment by hexylena** [comment]
Fixed in #3027, #3037, #3041, #3048, y'all are awesome!

**Comment by hexylena** [comment]
(There's still more to go always, but, this is such a fantastic start I think we can close the issue now maybe? Unless you all want to keep it open to track which topics don't have FAQs yet?)

**Comment by millen2223** [comment]
@hexylena  unintentionally I guess I made an error, I didn't want to make, I wanted to accept last remarks on yours review, can it be fixed?

**Comment by millen2223** [comment]
I think it's a already a good-known issue, and I could look at it at any time even closed, what do you think @rahmot?

**Comment by rahmot** [comment]
> @rahmot I wanted to say thank you to you for helping me to understand pull requests a bit better!

Oh, I did! So delighted to see that you have made pull requests recently.

**Comment by rahmot** [comment]
> (There's still more to go always, but, this is such a fantastic start I think we can close the issue now maybe? Unless you all want to keep it open to track which topics don't have FAQs yet?)

> I think it's a already a good-known issue, and I could look at it at any time even closed, what do you think @rahmot?

@millen2223 and @hexylena yes, it can be closed since we have access to all the FAQ documents. We will keep migrating them to GTN.
