### ISSUE TITLE
Infrastructure for subsetting and pinning course content.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/training-material#302]
xref https://github.com/galaxyproject/training-material/issues/300

Dagobah offers course material in separate time pinned branches. This ensures allow participants to go back and see their version of the material and it allows the course content to modified with specific slides, cloud URLs, etc....

![](https://cloud.githubusercontent.com/assets/1740254/26035819/a59ce186-38ca-11e7-9398-7cda83929f19.png)

Is this infrastructure worth providing at the level of this project? Is a branch based model worth adopting or should suggest tutorial presenters take the material and provide it via a separate mechanism (e.g. publishing static content however they wish)? 

As a bonus this could be used to cover material customized for particular servers such as main I think.

**Comment by bgruening** [comment]
As I said [here](https://github.com/galaxyproject/training-material/issues/300#issuecomment-301826616) already, this can be done by simply tagging a version of the repo and freeze the content. However, the problem is not the git content, it is the content that we rely on - some ansible tarballs that simply disappear and so on.
Please also see one of our first issue, where we tried to discuss and address the problem of branding/costomized instances: https://github.com/galaxyproject/training-material/issues/5

**Comment by jmchilton** [comment]
Happy to close this as a duplicate of #5 if you'd like. I wouldn't worry too much about ansible tar balls and such. If you are going back over and re-running a past tutorial on your own - you should use the latest version. The past, customized tutorials would be mostly for reference.

**Comment by erasche** [comment]
> Is this infrastructure worth providing at the level of this project? Is a branch based model worth adopting or should suggest tutorial presenters take the material and provide it via a separate mechanism (e.g. publishing static content however they wish)?

The focus is "this is *the* training site", the one url that's used everywhere and is well known, and if course participants get lost they can always find the materials again. For the content side the focus is that everything is made general enough to be run on multiple servers and platforms. This doesn't give you branched versions, I know, we really want a single best version.

We have added the [archive](https://training.galaxyproject.org/archive/). Here we have time pinned versions of the training materials for use in courses.

For additional cases of "changes for specific infrastructure" we have the option of having multiple versions of a tutorial, and I'm exploring having a selector at top for specific infrastructure (e.g. launching VMs on amazon vs digital ocean vs openstack. https://github.com/galaxyproject/training-material/pull/1120)

I know this doesn't completely solve your issue, I'm sorry, but I think it's outside the planned scope. :(
