### ISSUE TITLE
Infrastructure: Refining static content generation framework for training-materials

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/training-material#304]
The current jekyll-based infrastructure for deployment of training-materials was a good first step, but significant issues remain. This issue is listing some of them:

- [x] The styling for site is immature. It is not pleasant to the eye (although this is of course subjective). One solution is to adopt the same styling used for galaxy-hub. 
- [ ] The current training materials styling allows for injection of styles using {{ }} syntax. If the styling is redone in galaxy-hub-like way we should keep this functionality.
- [x] Some tutorials will have slides, some won't. Some will have docker images, some won't. Some will cover main site, and some will be generic. Top level menu should be easily configurable to address this. There are tutorials that have docker icons at the top level menu, but these are empty.
- [x] I strongly dislike icons shown within tutorials (such as Pencil etc.). We should stick with a single style. I would prefer using fontsawesome throughout (or any other consistent, well designed library). 
- [ ] If metalsmith is used as the static content generator is should be possible to view changes in real time. The current version for galaxy-hub is waaay too slow. It is very painful to edit current galaxy-hub content because every reload (via `make serve`) takes minutes to finish.
- [x] there has to be a way to "hide" tutorials. Some existing tutorials are incomplete, have no docker images, have no meaningful slides, or otherwise broken. It should be possible to label these at "WIP" and make sure that they do not appear in the production site.

**Comment by Slugger70** [comment]
Hackathon Group 2 - We think this is a good idea and should be available as guidelines and templates for creation of new materials. e.g. Slide examples for different slide types - titles, images, text, video etc.. Then templates/examples/guides for tutorial documents with reveal/hints etc...

**Comment by bebatut** [comment]
@nekrut Do you think we can close this issue?

**Comment by bebatut** [comment]
@nekrut Do you think we can close this issue?

**Comment by bebatut** [comment]
I think this issue is outdated now. I will close it. We can reopen it if needed :smile:
