### ISSUE TITLE
Workflows and the role in training?

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/training-material#305]

**Comment by MoHeydarian** [comment]
Workflows are one of the strongest features of Galaxy. Since we use the GTN materials as a method to teach bioinformatics to a diverse range of researchers, we should emphasize the use of workflows and how they are a useful addition to making research reproducible.

**Comment by bgruening** [comment]
xref: https://github.com/galaxyproject/training-material/issues/287

**Comment by Slugger70** [comment]
Hackathon Group 2 - Workflows are a really tool to solidify peoples knowledge etc. If they were a final outcome of any tutorial.. So here we've done the tut manually, and now here is the workflow that recreates it..

**Comment by malloryfreeberg** [comment]
Hackathon Group 2 - A feature that would be great to have is a workflow reconciliation step that occurs between choosing to import a workflow and viewing the workflow in an editor. Meaning, if a user has downloaded or extracted a workflow from a training session and wants to use it on another instance, they have the option to replace tool versions if their current instance doesn't have the version in the workflow. Or replace broken links between tools. This might be a separate issue but a good idea if we are to emphasize workflows in training sessions.

**Comment by KeywanHP** [comment]
We prefer teaching workflows from scratch without using extract workflows from history....

**Comment by nsoranzo** [comment]
@KeywanHP It surely is useful to teach how to create a workflow from scratch in the "Galaxy introduction" set of tutorials. But for a topic-specific workflow, going first tool-after-tool mimics more accurately the process a user normally goes through to create a workflow, in my opinion.

**Comment by bgruening** [comment]
Workflows should be a main part of each tutorial, with an image of the workflow a short description and the `ga` file.

**Comment by jmchilton** [comment]
I like the idea of having a workflow for each tutorial when it is appropriate. I'd be eager to help write planemo test cases for these workflows from the training data. Running these test cases in this repository would be great - it would ensure that all the required backend tools and features work with each new version of Galaxy. If someone picks a candidate tutorial and gives me a workflow - I can start work on scripting this.

**Comment by bgruening** [comment]
@jmchilton the current plan is.
* build a container including, training-data, reference genomes, tours, tools and workflows
* run usual travis tests for Docker flavors
* run the workflow on the training datasets
* run the tour with travis

If this could be scripted and part of planemo and https://github.com/galaxyproject/galaxy-flavor-testing this would be fantastic!

Thanks @jmchilton!

**Comment by Stortebecker** [comment]
> Workflows should be a main part of each tutorial, with an image of the workflow a short description and the ga file.
> Extracting workflows from histories should be part of a training session and should be linked at the and of a training.

I would prefer to present workflows separately from the tutorials. Workflows could have a separate page with a short description of input and output (see this [example](https://github.com/Stortebecker/secretome_prediction)). At the end of the tutorial, a link should direct the users to the workflow page. 

Thus, workflows could be accessed more directly, if a user does not want to do the tutorial. And we could publish some more complicated workflows, where a step-wise reproduction would be too tedious for a tutorial.

**Comment by erasche** [comment]
We have workflows for lots of tutorials, and they will take more prominence in the next years!
