### ISSUE TITLE
Referenced tool "Column join on multiple data sets" not in Galaxy

### ISSUE THREAD

**Issue by quacksawbones** [galaxyproject/training-material#3054]
A user informed be that in the [rna-seq-reads-to-counts](https://training.galaxyproject.org/training-material/topics/transcriptomics/tutorials/rna-seq-reads-to-counts/tutorial.html#create-count-matrix) tutorial at the "Create Count Matrix" step, the tool that is referenced "Column join on multiple data sets" is not anywhere I can find.

I believe the tool is "Multi-join" (within the [text_processing](https://toolshed.g2.bx.psu.edu/repository?repository_id=2593fd36ae8011aa) tool set, but could this tutorial step be clarified and updated to include the correct tool.

Thanks

**Comment by hexylena** [comment]
https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/collection_column_join/collection_column_join/0.0.3 It is this tool here, it's available on usegalaxy.eu!
