### ISSUE TITLE
Integration with TeSS

### ISSUE THREAD

**Issue by vdda** [galaxyproject/training-material#306]
In TeSS https://tess.elixir-europe.org/ 
we want to connect work-flows, tools, training material and events. Do we should duplicate this effort?

**Comment by bgruening** [comment]
* How do we handle events?

**Comment by bebatut** [comment]
Do you want to keep a track of them? Where? On the Hub?
And do we want also to have feedbacks (only instructors or also trainees)?

**Comment by dannon** [comment]
(G4) Maybe we scrape galaxy-tagged events published on TES and present them in the galaxy events feed at galaxyproject.org/events (hub-generated)

**Comment by nsoranzo** [comment]
Apparently the opposite may be easier:
- trainer submits an event to the Galaxy hub, either by creating a PR or using a form (to be created) on the Galaxy Training website
- TeSS aggregates the events from the Galaxy Hub.

**Comment by dannon** [comment]
Sounds good to me.  We need to add more 'friendly' ways for people to add content like this (A github issue or PR template was one suggested option)

**Comment by bebatut** [comment]
TeSS is now automatically aggregating
- the tutorials from here: https://tess.elixir-europe.org/content_providers/galaxy-training
- the events from the Hub: https://tess.elixir-europe.org/content_providers/galaxy-project

I will close this issue then
