### ISSUE TITLE
Maintainers and tutorials

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/training-material#307]
* How many maintainers are needed for one topic?
* How do we "elect" them?
* What do we do if a topic does not have a maintainer?
* Credits for maintainers?

xref: https://github.com/galaxyproject/training-material/issues/63

**Comment by bebatut** [comment]
And  question also: What has a maintainer to do? Reviewing all material related to a topic? Checking both the content and the form? ...

**Comment by dannon** [comment]
(Group 4) Maybe more like a 'coordinator'?  Volunteer basis, no need to elect, but we probably want 2 per tutorial.

**Comment by malloryfreeberg** [comment]
Hackathon Group 2 - At least the person(s) who wrote the tutorial should be a maintainer/coordinator in the beginning and should have final commit say for any changes. In addition, though, the people who actively use the tutorial should also be considered maintainers and offer suggestions/PRs for updates to tools, edits, etc.

**Comment by bgruening** [comment]
> How many maintainers are needed for one topic?

At least 2 per topic, ideally 2 per tutorial.

> How do we "elect" them?

Initial contributor of this tutorial and later volunteers. 

> What do we do if a topic does not have a maintainer?

As soon as our tests fail, hide them from the website, but keep the content on github.

> Credits for maintainers?

* Contributors file (automatic generated)
* Regular manuscript on bioarxiv/F1000... with the contributors of the last year
* every two years submitting it to a journal?

**Comment by erasche** [comment]
Discussion was continue in #489, is this ok to close @bgruening?

**Comment by bgruening** [comment]
Jupp!
