### ISSUE TITLE
Restructuring the tutorials

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#310]
Hi,

In Cambridge hackathon, we discussed about a new structure for content of each tutorial and topic

```
topic
|_ tutorials
    |_ tutorial 1
    |_ tutorial 2
        |_ tutorial.md
        |_ metada.yml  # metadata for the tutorial, with also tags 
        |_ slides.html  # if needed
        |_ tools.yml  # with all tools needed to run the tutorial
        |_ data_libraries.yml # with the data libraries (link to input data on Zenodo)
        |_ workflow.ga  # with the workflow of the tutorial
        |_ tour.yml  # with the tour of the tutorial
|_ slides
|_ docker
    |_ Dockerfile # automatically generated from the content of the tutorials
```

It will help to add all needed material and infrastructure to run a tutorial. 
We can provide scripts to help admin to populate the tools, the data libraries, the workflow, the tour for a tutorial (using the API).
We can also add some automatic tests to check that everything needed for a tutorial is there.

**Comment by dannon** [comment]
![image](https://cloud.githubusercontent.com/assets/155398/26313832/ffc279de-3f03-11e7-88ed-e99795e1e37b.png)

**Comment by bebatut** [comment]
I have a quite similar structure now
