### ISSUE TITLE
Asking auto translation using GTN material through webhook gives an error message

### ISSUE THREAD

**Issue by yvanlebras** [galaxyproject/training-material#3106]
![image](https://user-images.githubusercontent.com/7910679/145360235-004ae910-d211-4539-ad9c-b425e28146c6.png)

Maybe due to the webhook, or maybe to the subdomain ?

**Comment by yvanlebras** [comment]
Just verified, this is not due to the subdomain.. S oapparently "just" due to the webhook functionality

**Comment by hexylena** [comment]
That is not terribly surprising, this is a security restriction by google, that the translate pages cannot be placed in an iframe. There is no possible way to work around this, so I will close it.

(Let me know when you get a french translation team figured out ;))
