### ISSUE TITLE
GTN paper: almost ready! Need your review now :)

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#3107]
We are working for more than 2 years now on paper to present the GTN to instructors.

We think it is almost ready to be send. But we would like the feedback from the community first.

If you want to participate, please **before the 10th of January**:
- open the document at: https://www.overleaf.com/5685435963xxydhyqdnwmj
- read the paper
- add your comments / suggestions in the document 
- add your name
- reach us if you have any major concerns

Thank you!

**Comment by ic4f** [comment]
@bebatut  What's the best way to proof/comment on the paper? Should I edit the source directly? (sorry, I've never used overleaf before).

**Comment by bebatut** [comment]
@ic4f Yes you can edit the source directly. I see already (at least) a change you did. Thanks for that :)

**Comment by hexylena** [comment]
Pinging everyone who is watching this :)
