### ISSUE TITLE
FTP tutorial Papercut

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/training-material#3135]
There is an "error" in the example code for the Galaxy/FTP portion of galaxyservers.yml.  if you intend to use separate upload directories (with email addresses as the folder name) for each user - as the tutorial indicates will happen - then the current code (below) will result in the uploads going into the parent directory "/uploads" instead of "uploads/user_email" .  

# FTP
    ftp_upload_dir: /data/uploads
    ftp_upload_site: "{{ inventory_hostname }}"

Instead the code should be (add a "/"):

# FTP
    ftp_upload_dir: /data/uploads/
    ftp_upload_site: "{{ inventory_hostname }}"

Took me a while to work out why it was going into the wrong directory.

Also - it should be stated that there may be a newer version of the playbook that could solve errors/conflicts with newer operating system versions than those used in the tutorial.  

Also suggest highlighting parts in the code examples which should be customized to your server environment if you are using this as a guide to setup your own installation (primarily directories where stuff is located).   

*Note: this comment was autogenerated*

_Originally posted by @shiltemann in https://github.com/galaxyproject/training-material/issues/989#issuecomment-1013548807_

**Comment by lldelisle** [comment]
Hi,
This is strange because on my config (galaxy version 21.01) using:
```
    ftp_upload_dir: /data/galaxy/uploads
```
produced one directory per user...

**Comment by hexylena** [comment]
Huh, odd. It shouldn't be necessary to have the trailing slash, since `ftp_upload_dir_template` includes the slash `${ftp_upload_dir}/${ftp_upload_dir_identifier}`. I think you're right @lldelisle we can close this.
