### ISSUE TITLE
Generation of the Docker images

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#314]
Maybe it could be nice to have a Quay.io organization for the training material where we could create a repository for each topic.
Each repository will point to this GitHub repository but on different folder. 
Quay.io could then build a Docker image for each topic.

What do you think?

**Comment by colindaven** [comment]
We think this is a great idea since we are currently having problems using docker build behind a nasty proxy to build the transcriptomics training material. If this was on quay.io it would just be a download.

Thanks, Colin

**Comment by bebatut** [comment]
@bgruening worked on that in #627
