### ISSUE TITLE
Requirement page for slides

### ISSUE THREAD

**Issue by pajanne** [galaxyproject/training-material#315]
Hi @bebatut,

Would it be possible to have the possibility to remove the requirement page when there is no requirement for the tutorial slides? I am currently working on the Galaxay introduction training materials and though it would be useful to have the ability to choose to have it or not. I am happy to change the code but do not know where to start. Many thanks for helping.

Best,
Anne.

**Comment by bebatut** [comment]
Yes it must be possible. 
But maybe we can change that in the new infrastructure. @dannon what do you think?

**Comment by dannon** [comment]
Yep, should be possible, we'll just have to conditionally include that slide in the deck

**Comment by bebatut** [comment]
I think it is fixed now
