### ISSUE TITLE
Create Docker container for 16S Metagenomics Tutorial

### ISSUE THREAD

**Issue by dsobral** [galaxyproject/training-material#319]
A very simple container, based on ngs-preprocessing, with some extra tools necessary for the tutorial. Probably does not need example data, since uploading it is part of the tutorial.

**Comment by bgruening** [comment]
@dsobral thanks. This is done, right?

**Comment by dsobral** [comment]
Yes, I think so. May be worth removing the setup_data_libraries.py which is not used, but otherwise should be ok. Thanks!

**Comment by bgruening** [comment]
Please feel free to remove all setup_data_lib files :)
