### ISSUE TITLE
links to tags are not working

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/training-material#3196]
I would like to have a link that lists all tutorials for a tag. That was working previously via the search page, but seems to not work anymore. E.g. https://training.galaxyproject.org/training-material/search?nanopore

**Comment by wm75** [comment]
Still working, but it's:
https://training.galaxyproject.org/training-material/search?query=nanopore

**Comment by bgruening** [comment]
Try to click on one of the tags.

**Comment by wm75** [comment]
I see :(
