### ISSUE TITLE
[Tutorial: Creating content in Markdown] Markdown code snippets to document adding image transformed into HTML

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#3214]
In: https://training.galaxyproject.org/training-material/topics/contributing/tutorials/create-new-tutorial-content/tutorial.html#adding-images-with-captions

![image](https://user-images.githubusercontent.com/1842467/156371480-0f313a14-2aa7-49af-b484-7d2c2c6e07c7.png)

All Mardown snippets to explain how to add images are transformed into HTML, even with `{% raw %}`

**Comment by hexylena** [comment]
Now fixed
