### ISSUE TITLE
Issues running GTN website locally on Mac

### ISSUE THREAD

**Issue by mblue9** [galaxyproject/training-material#3218]
Hi, I was having issues with `make serve` and ended up doing a fresh clone of this repo. But when running `make create-env` (as [here](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/running-jekyll/tutorial.html)) I get the error
```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - gxx=9
  - gcc=9

make: *** [create-env] Error 1
```

I'm guessing as there's no gcc9 (or g++9) for Mac in conda here https://anaconda.org/conda-forge/gcc ? 

I'll try using GitPod in the meantime but does anyone know if/how I can get past this error?

**Comment by hexylena** [comment]
Xref https://github.com/galaxyproject/training-material/pull/3156#issuecomment-1157642695

**Comment by nomadscientist** [comment]
Hi yes! Same issue here, and tried it on 2 Macs (one that this used to work fine on and another fresh one) and both failed :(

**Comment by hexylena** [comment]
I think @nekrut recently reported this as well. We should make a separate environment-osx.yml for conda to use conditionally
