### ISSUE TITLE
ggplot2 cheat sheet link is broken

### ISSUE THREAD

**Issue by NickSto** [galaxyproject/training-material#3260]
In the [RNA Seq Counts to Viz in R](https://training.galaxyproject.org/topics/transcriptomics/tutorials/rna-seq-counts-to-viz-in-r/tutorial.html#question-create-a-r-script-with-plots) tutorial, there's a link to a [ggplot2 cheat sheet](https://github.com/rstudio/cheatsheets/raw/master/data-visualization-2.1.pdf) that's broken. It looks like that's due to a rename of their `master` branch to `main`, because this link works: https://github.com/rstudio/cheatsheets/raw/main/data-visualization-2.1.pdf

Originally reported by Yu-Chen Wu during the GTN Tapas event.

**Comment by hexylena** [comment]
want to fix that in a PR?

**Comment by NickSto** [comment]
I will if I have a chance. I just don't have the build system set up right now.

**Comment by hexylena** [comment]
you don't need to build the website to submit a PR, our test coverage is quite good and one of us will review it :)
(Also gitpod exists if you _really_ need it.)

**Comment by hexylena** [comment]
fixed in 3a006bbaa0c
