### ISSUE TITLE
missing text in gxadmin GTN tutorial

### ISSUE THREAD

**Issue by abueg** [galaxyproject/training-material#3281]
Hello! Reporting a typo with the gxadmin GTN tutorial - the paragraph describing Nate's favorite query seems to end prematurely:

> natefoo’s favourite: gxadmin query job-inputs. He contributed this function which helps him debug jobs which are not running and should be. The query can

**Comment by hexylena** [comment]
I've got some other post-gat fixes, I'll get this then :)

**Comment by hexylena** [comment]
fixed in 7de6400f8e0
