### ISSUE TITLE
Possibility of multiple dockers for each topic, or reconsider topic organization

### ISSUE THREAD

**Issue by dsobral** [galaxyproject/training-material#334]
Hello,

I was wondering if it makes sense to have more than one docker for a topic.

I can think on several reasons for this. 

For once, within one topic, depending on the tutorial, the galaxy used can have quite different tools and datasets. For example, metagenomics for now is just the 16S. In the case of "true" metagenomics, the docker will probably have to be quite different, potentially very big in size.

In this case, you can argue maybe we should create different topics altogether:

16S "metagenomics" could be in "amplicon sequencing" or something similar, while metagenomics could be reserved for "true" shotgun metagenomics.

I can also think of another reason, which has to do with the possibility to cater to different audiences. 
Variant calling for bacteria can use different tools and methodologies than the human case, and surely require much less space. Similarly for denovo assembly and annotation.

I'm in favor of minimizing the number of images that require maintenance, but if we do a single docker for one topic, we may end up with very big ones, which can be limiting in some cases.

In any case, I'm happy to hear what people think about it.

**Comment by bebatut** [comment]
I think keeping one Docker image per topic is already enough work. @bgruening what do you think?

**Comment by bgruening** [comment]
Yes. I think to test one instance and make it solid is problematic enough for the moment. we can change this later if we see this is useful.
