### ISSUE TITLE
Change table layout on topic web page

### ISSUE THREAD

**Issue by pajanne** [galaxyproject/training-material#335]
If you go to http://galaxyproject.github.io/training-material/Introduction/, the current layout is 

<img width="515" alt="screen shot 2017-05-24 at 11 34 55" src="https://cloud.githubusercontent.com/assets/214738/26399518/1fefe49a-4075-11e7-86e7-8bce58bd02c5.png">

Would it be better to have the 'Slides' column first?

**Comment by willdurand** [comment]
Hi! Have you seen #463 by chance? Also, I'd love to know the reasoning behind this change request.

**Comment by nsoranzo** [comment]
I suppose because slides are introductory to the tutorial. But I think that an alphabetical order would be even better, both in https://galaxyproject.github.io/training-material/ and in the topic pages.
