### ISSUE TITLE
Diff display problem

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/training-material#3351]
There's something strange on https://training.galaxyproject.org/training-material/topics/admin/tutorials/connect-to-compute-cluster/tutorial.html (at least), sometimes the g from "galaxyproject" is not displayed in the diffs (while it's there in the src markdown file):

![image](https://user-images.githubusercontent.com/238755/162386157-a829810b-73a4-4569-90db-b1b0e089de1b.png)

**Comment by hexylena** [comment]
oh bugger. I thought I fixed that :sob: thanks for catching these

**Comment by hexylena** [comment]
ahh it's the `<span notranslate>` that's confusing the algorithm, oof.
