### ISSUE TITLE
Hands-on Tutorial on Qiime (Metagenomics)

### ISSUE THREAD

**Issue by dsobral** [galaxyproject/training-material#336]
Hello,

I'm writing a tutorial based on this:
http://nbviewer.jupyter.org/github/biocore/qiime/blob/1.9.1/examples/ipynb/illumina_overview_tutorial.ipynb

Daniel

**Comment by dsobral** [comment]
The biom suit of tools are not available. Would need at least the biom summarize-table for this tutorial.

**Comment by dsobral** [comment]
The perform open-reference OTU picking tool generates an empty file which is necessary for the tutorial

**Comment by bebatut** [comment]
I will work on the missing tools (in [biom-format](https://github.com/galaxyproject/tools-iuc/tree/master/tools/biom_format)) in the next days
What is the generated empty file by `pick_open_reference_otus`?

**Comment by dsobral** [comment]
It's the "OTU table with taxonomic assignment and without sequences failing the alignment to the OTU representative sequences". Basically the equivalent to otu_table_mc2_w_tax_no_pynast_failures.biom

**Comment by bebatut** [comment]
@dsobral Are you still working on the tutorial? Do you need any help with it?

**Comment by dsobral** [comment]
I have been busy with other stuff, but I plan to continue working on the tutorial. I'll check if the tools now allow me to complete the qiime overview tutorial.

**Comment by dsobral** [comment]
By the way, are the new biom tools in the main toolshed? Thanks!

**Comment by dsobral** [comment]
Sorry, I saw they are in the Test Toolshed.

**Comment by erasche** [comment]
We will write tutorials for QIIME2 as soon as it is ready. @blankenberg can you update us on the status of the qiime2 integration?
