### ISSUE TITLE
Add link to feedback form on GTN page and tutorials

### ISSUE THREAD

**Issue by MoHeydarian** [galaxyproject/training-material#337]
It would be nice to link to a feedback form on the GTN and tutorial pages. This short form would allow us to know who is using the material and for what purpose. It would also be an informal way to get input from our users on the content/layout/etc. 

I think a simple Google form would suffice.

**Comment by bgruening** [comment]
@MoHeydarian :+1: !

**Comment by malloryfreeberg** [comment]
This is a great idea. Let's do it!

**Comment by MoHeydarian** [comment]
Here is the link to the GTN feedback form: https://tinyurl.com/GTNfeedback

This form is owned by the GalaxyTrainingNetwork gmail account. We'll distribute the pw at GCC2017. 

Closing this.

**Comment by bgruening** [comment]
@MoHeydarian we should at this at the end of all hands-on sessions, right?

**Comment by shiltemann** [comment]
@bgruening I will add it to the template now :)
