### ISSUE TITLE
Update location of docker container for each topic

### ISSUE THREAD

**Issue by pajanne** [galaxyproject/training-material#342]
I've updated the docker file for the introduction's topic and I am wondering how to update the location of the new container. Currently we have:
- in the metadata file: `docker_image: "bgruening/galaxy-stable"`
- in the rendered web page: `docker run -d -p 8080:80 bgruening/galaxy-stable`

Will the new docker container be published automatically based on the docker file in each topics? Thanks :wink:

**Comment by bebatut** [comment]
The location of the container is in `metadata.yaml` files. @bgruening worked in #627 on automatic pushing of the Dockerfile on quay.io to create the images.
I hope it is answering your questions @pajanne.
I am closing this issue. If needed we can still reopen it 😄
