### ISSUE TITLE
[FAQs] FAQ present in both GTN FAQs and Galaxy FAQs

### ISSUE THREAD

**Issue by garimavs** [galaxyproject/training-material#3440]
Two instances of the same FAQ in both the [GTN](https://training.galaxyproject.org/training-material/faqs/gtn/#what-information-should-i-include-when-reporting-a-problem) and the [Galaxy](https://training.galaxyproject.org/training-material/faqs/galaxy/#what-information-should-i-include-when-reporting-a-problem) faqs.

![image](https://user-images.githubusercontent.com/77723358/165757999-6cd4bd08-b954-4489-8e98-6dcde248384d.png)

![image](https://user-images.githubusercontent.com/77723358/165758141-7c28408f-62ac-464d-b032-99db3a3fa534.png)

**Comment by garimavs** [comment]
I had a doubt here that it might be possible that both the links are referenced somewhere. It is also possible that deleting any of these may lead to many broken links. Will it be wise to go ahead with this issue?
Kindly comment @beatrizserrano @annefou

**Comment by beatrizserrano** [comment]
I don't know if a `redirect` could be added to one of the files pointing to the other one. That way, we avoid the duplication and don't break links.

**Comment by garimavs** [comment]
By `redirect`, we simply change the content of one faq by linking it with the other one?

**Comment by garimavs** [comment]
Hello team, 
Do let me know how to proceed with this issue!

**Comment by shiltemann** [comment]
This is just the same FAQ symlinked from GTN folder because it is relevant there. So there is no duplication here. A redirect_from may have worked too, but no real reason to change it now I think.
