### ISSUE TITLE
diff fixer is too aggressive

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/training-material#3494]
Hey folks,

I've used these tutorials a few times and it has been really helpful. 

However, I've found a typo that I can't correct in the "Training Material" Git repo:

"Galaxy Installation with Ansible":
<img width="960" alt="Galaxy_ansible_tutorial_typo" src="https://user-images.githubusercontent.com/1300104/173179694-688b66d2-4d92-429c-9433-5ccaa88c4287.png">

"Use Singularity containers for running Galaxy jobs":
<img width="960" alt="Galaxy_ansible_singularity_typo" src="https://user-images.githubusercontent.com/1300104/173180028-77578f76-79ed-4348-94dc-b445ce8d6ffa.png">

Thanks folks,

DC

_Originally posted by @quacksawbones in https://github.com/galaxyproject/training-material/discussions/1452#discussioncomment-2927776_

**Comment by hexylena** [comment]
So we have a script that visually "fixes" diffs to make it easier to copy and paste but it's has some occasional issues where it's mis detected the start. I'll look into this next week.

**Comment by hexylena** [comment]
@quacksawbones

what was the error in the singularity tutorial? I'm afraid I can't tell from the screenshot.  I think you've selected the green line, but that looks ok? I've fixed the other issue, it was simply a missing space: https://github.com/galaxyproject/training-material/pull/3495

**Comment by quacksawbones** [comment]
In the singularity one, the green line incorrectly reads: `- name: galaxyroject.tusd` and is missing a "p" in "project".

I understand that these are minor things and I appreciate you looking at them :)

**Comment by hexylena** [comment]
Ahhh missed the p, cheers!

**Comment by hexylena** [comment]
ok #3495 should fix it completely. Thanks for reporting these! They get missed very easily since it's only visible in the final version of the site + javascript, which isn't an environment we test other than by humans reading it, so we really appreciate it getting caught before someone copy and pastes something wrong!
