### ISSUE TITLE
RMSD, RMSF and PCA didn't work in the tutorial: Analysis of molecular dynamics simulations

### ISSUE THREAD

**Issue by biotemon** [galaxyproject/training-material#3580]
The tutorial of the matter is: 

https://training.galaxyproject.org/training-material/topics/computational-chemistry/tutorials/analysis-md-simulations/tutorial.html

The steps involving RMSD, RMSF and PCA are useless. They all end in the following error.

```
/corral4/main/jobs/045/151/45151780/tool_script.sh: line 9: Rscript: not found
Fatal error: Exit code 127 ()
```

**Comment by bgruening** [comment]
@biotemon which server are you using?

**Comment by biotemon** [comment]
usegalaxy.org doesn't have the tool, but I found it in usegalaxy.eu and cheminformatics.usegalaxy.eu
