### ISSUE TITLE
"Merge GROMACS topologies" tool is not found

### ISSUE THREAD

**Issue by biotemon** [galaxyproject/training-material#3581]
I am trying to run the High Throughput Molecular Dynamics and Analysis tutorial (https://training.galaxyproject.org/training-material/topics/computational-chemistry/tutorials/htmd-analysis/tutorial.html). But the tool "Merge Gromacs topologies" is nowhere to be found. I am using the usegalaxy.eu and cheminformatics.usegalaxy.eu servers. What can I do? @simonbray @tsenapathi @bgruening

**Comment by bgruening** [comment]
try this tool here: https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/chemteam/gmx_merge_topology_files/gmx_merge_topology_files/3.2.0+galaxy0

**Comment by shiltemann** [comment]
The tool seems to show up in the search on EU now (and using tutorial mode is always a good suggestion yeah :+1: ), so I will close this issue (feel free to re-open if there is still an issue for you)
