### ISSUE TITLE
Headings should be link anchors

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/training-material#3583]
I would like to be able to link to part of a tutorial. For this to work headings, like the "Calling with FreeBayes" below (from [this tutorial](https://training.galaxyproject.org/training-material/topics/variant-analysis/tutorials/dip/tutorial.html)) should be link anchors. I haven't looked at the code yet, but I hope this is easy to implement.

![image](https://user-images.githubusercontent.com/4154788/184662163-dfb872a8-f603-42dd-a868-f95ba51a1267.png)

**Comment by hexylena** [comment]
They are, already. https://training.galaxyproject.org/training-material/topics/variant-analysis/tutorials/dip/tutorial.html#calling-with-freebayes

you can find the link directly from the Table of Contents in the agenda, or at some point in the future I'm going to add one of those lil hover link icons.
