### ISSUE TITLE
"Old style" display applications are no longer accessible - possibly related to  #14341

### ISSUE THREAD

**Issue by hrukkudyr** [galaxyproject/training-material#3589]
**Describe the bug**
Beta history is not rendering HTML/CSS for a class called _display-applications_ -  these can be seen by switching to Legacy History 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: {"version_major":"22.05","version_minor":"1"}
https://usegalaxy.eu/training-material/topics/transcriptomics/tutorials/ref-based/tutorial.html - no IGV links

**Additional context**
This may have already been corrected in the galaxyproject/galaxy#14341 report and not yet propagated to the GTN server, if so - my apologies.

**Comment by mvdbeek** [comment]
I've moved it to the GTN because the description and sceenshot need to be updated, let's keep this open until that's done.

**Comment by shiltemann** [comment]
I believe you fixed this in https://github.com/galaxyproject/training-material/pull/3585 @hrukkudyr, thanks! So am closing this. Feel free to re-open this issue if there is something more that needs to be done here that I may have overlooked.
