### ISSUE TITLE
From peaks to genes training: missing option

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/training-material#3636]
In the visualization section, the Sort tool requires the following options according with the training:

![Screenshot from 2022-09-30 16-16-54](https://user-images.githubusercontent.com/26678117/193290031-74cbc5a7-e2a7-43b9-a8d2-2674cdfcb88a.png)

However, the *Natural/Version sort (-V)* doesn't exist in any of the tool versions (at least I wasn't able to find it).

**Comment by shiltemann** [comment]
If you use the tutorial mode (hat icon) in Galaxy, and click on the tool name, it opens the correct sort tool: 
![image](https://user-images.githubusercontent.com/2563865/193850315-87a49438-c76b-4cc5-8910-d81954f81b81.png)
