### ISSUE TITLE
@jmchilton's GCC Training Homework 

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/training-material#365]
Included in this PR:

- Tool development using Conda and Bioconda slides. Fixes #231.
- Tool development with Containers and BioContainers slides. Fixes #232.
- Galaxy Code Architecture slides synchronzied from galaxyproject/galaxy.

I still have a lot I'd like to do but this seems like a workable first draft.

Conda:
 - [ ] Discussion of merged mulled environments perhaps, more slides about dependency resolution in general?

Containers:
 - [x] Update all slides for mulled-v2. 
 - [x] Update with information on multi-package-containers repository and monitoring tool repositories for missing containers.
 - [ ] Singularity information.
 - [ ] Information on newer container-based deployment options - Kubernetes, Chronos, and Condor Docker universe.

Arch:
 - [ ] Redo startup slides since they may have changed since last year - especially tool monitoring and stuff.
 - [ ] Add a section about web hooks.

**Comment by bgruening** [comment]
first part implemented here: xref: https://github.com/galaxyproject/training-material/pull/357

**Comment by erasche** [comment]
Sorry bad close. Is this still relevant? We have some training on k8s,webhooks, etc.

**Comment by shiltemann** [comment]
going to close this since its 5 years old, feel free to re-open or recreate an issue for parts of this if still relevant
