### ISSUE TITLE
Gitpod fails during make serve

### ISSUE THREAD

**Issue by AnnaSyme** [galaxyproject/training-material#3650]
Hi all, 

Following this tutorial: 
https://training.galaxyproject.org/training-material/topics/contributing/tutorials/gitpod/tutorial.html

Having an issue with Gitpod when I run `make serve-gitpod`

error message: 

```
source /home/gitpod/miniconda3/bin/activate galaxy_training_material && \
cat metadata/swagger.yaml | python bin/yaml2json.py > api/swagger.json
bash: /home/gitpod/miniconda3/bin/activate: No such file or directory
make: *** [Makefile:259: api/swagger.json] Error 1
```

Does anyone know why? Is perhaps miniconda not being installed in the correct place? 

Or it may be an issue with Gitpod itself. 

Thanks, 
Anna

**Comment by hexylena** [comment]
In the short term you can do

```
make serve-gitpod ACTIVATE_ENV=pwd
```

and it'll work.
