### ISSUE TITLE
Error with make install, to install jekyll

### ISSUE THREAD

**Issue by AnnaSyme** [galaxyproject/training-material#3651]
Hi all, 

Following this tutorial to serve the GTN materials locally:
https://training.galaxyproject.org/training-material/topics/contributing/tutorials/running-jekyll/tutorial.html

I am working on a Mac, have updated my GitHub fork, cloned a fresh copy of the training-material locally, run the commands to install conda and create a virtual env called galaxy_training_material, then activated it. 

Issue:
When I run `make install` I get errors. 

These include:
```
Building native extensions. This could take a while...
ERROR:  Error installing jekyll-last-modified-at:
	ERROR: Failed to build gem native extension.
```

and

```
compiling posix-spawn.c
posix-spawn.c:6:10: fatal error: 'errno.h' file not found
#include <errno.h>
         ^~~~~~~~~
1 error generated.
make[1]: *** [posix-spawn.o] Error 1
```

and 

```
11 gems installed
make: *** [install] Error 1
```

Does anyone know why? 
I can include the full screen log if that's useful. 
Thanks, 
Anna

**Comment by hexylena** [comment]
This is an OSX specific error it seems, and I'm not sure how to address it. I've found the following links which might be interesting:

https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave/52530212#52530212

**Comment by shiltemann** [comment]
maybe @bebatut has some insight as a Mac user?
