### ISSUE TITLE
Architecture diagrams still reference uWSGI

### ISSUE THREAD

**Issue by elichad** [galaxyproject/training-material#3665]
In these slides: https://training.galaxyproject.org/training-material/topics/admin/tutorials/ansible-galaxy/slides.html

It's been changed in [ansible-galaxy-intro-2.png](https://github.com/galaxyproject/training-material/blob/main/topics/admin/images/ansible-galaxy-intro-2.png) but is yet to be changed in the rest of the `ansible-galaxy-intro-*.png` images.

(P.S. if the images were SVGs I'd have updated the uWSGI text myself, but matching fonts to update a PNG is harder, which is why I haven't done it. I assume someone has the original diagrams that were exported to PNG...)

**Comment by hexylena** [comment]
@Slugger70 is fixing this in #3654

**Comment by elichad** [comment]
Oh sweet, thanks!

**Comment by hexylena** [comment]
Ah, this was fixed in #3779, apologies I forgot to link this
