### ISSUE TITLE
Tool Form Run Button renamed

### ISSUE THREAD

**Issue by ElectronicBlueberry** [galaxyproject/training-material#3688]
https://github.com/galaxyproject/galaxy/pull/14549 renamed the `Execute` button to `Run Tool` for the upcoming Galaxy 23.1 release.
This should be reflected in the training material, once 23.1 is released.

**Comment by hexylena** [comment]
Oh jeez, good to know about. I'd missed that one! Thanks so much for filing the issue ahead of time.

**Comment by hexylena** [comment]
```
$ ag 'Execute' topics -c | cut -d: -f2 | sum-lines
455
```

cool that won't be painful at all or anything :sweat_smile:
