### ISSUE TITLE
No reference genome available for bwameth

### ISSUE THREAD

**Issue by hannahkimincompbio** [galaxyproject/training-material#3782]
Dear Galaxy Team, 

I am following this tutorial: https://training.galaxyproject.org/training-material/topics/epigenetics/tutorials/methylation-seq/tutorial.html. 

I am using their workflow as given in the tutorial, and I see that there is no reference genome available for bwameth. Would you help solving this problem? The attached is the screenshots of what I have encountered.

<img width="844" alt="Screen Shot 2022-12-08 at 3 08 52 PM" src="https://user-images.githubusercontent.com/21369275/206559427-82e5d69a-145d-4e53-99c6-ec5880dc3ea5.png">
<img width="856" alt="Screen Shot 2022-12-08 at 3 15 33 PM" src="https://user-images.githubusercontent.com/21369275/206559434-b058f112-5c40-48f1-b23f-2e9515439d5c.png">

The data that I am using: https://usegalaxy.org/u/hannahkimincompbio/h/dna-methylation-tutorial-data

**Comment by bgruening** [comment]
@hannahkimincompbio if you like you can use the EU Galaxy server with this tool for the training: https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/bwameth/bwameth/0.2.3+galaxy0

**Comment by hexylena** [comment]
This is a server specific issue that we cannot help with. EU supports this tutorial, Org does not unfortunately due to reference data.
