### ISSUE TITLE
File modification date vs current date

### ISSUE THREAD

**Issue by tuncK** [galaxyproject/training-material#3790]
For some reason, the modification date of the files (ex. uploaded workflows) always appear as today. 
![image](https://user-images.githubusercontent.com/19364610/208862140-2bfc9569-7507-4bdb-b656-a1205ac3d0fc.png)

This probably has something to do with here:
https://github.com/galaxyproject/training-material/blob/2789970476e71b3b169c5ce7dd36cf0ed832dadf/_layouts/workflow-list.html#L26

**Comment by hexylena** [comment]
Indeed they do! We've been fighting with this endlessly due to how file modification times are tracked in git, especially in shallow clones. I'll see if I can fix it.
