### ISSUE TITLE
Galaxy 101 - display in UCSC from history item

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/training-material#3835]
This can no longer be done in the history in 23.0:
![image](https://user-images.githubusercontent.com/42562517/214210997-f83ed73e-1cd8-40a7-b473-ae72511afdc1.png)

But it can be done by clicking the "visualize" icon for a dataset:
![image](https://user-images.githubusercontent.com/42562517/214211177-46a60d11-01d3-4e01-8eee-178523c2a237.png)

Not sure if this was intentionally left out (and the tutorial needs updating) or it's a bug in 23.0?

**Comment by hexylena** [comment]
Same as https://github.com/galaxyproject/training-material/issues/3838 which I already tagged in a "fixes this issue" commit so I'll go ahead and close this one instead of the others.

Thanks for the catch @neoformit
