### ISSUE TITLE
Rule Based Uploader: Advanced - Outdated Info

### ISSUE THREAD

**Issue by ElectronicBlueberry** [galaxyproject/training-material#3840]
Release Testing 23.0

* “Building URLs from Accession Information”, Hands-on: Uniport Outdated Info and Screenshots
  - Format can now be found under Download. Format menu point no longer exists
  - Page now has an api url generator, which may be a better fit for this tutorial. It is found under the parent section, and is formated: `https://rest.uniprot.org/uniprotkb/stream?format=fasta&query=accession%{identifier}`
* "Apply Rules to Existing Collections", Step 3: Click `Build` should be Click `Upload`
* Outdated Screenshots showing the History

**Comment by hexylena** [comment]
All of the Galaxy screenshots here are generated automatically, I do not know how they are updated. It was written by a colleague that has now left. 

E.g.
https://galaxy-tests.s3.amazonaws.com/galaxy-gtn-screenshots/local/rules_example_4_7_mapping_extension_and_name.png

I find the name in https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy_test/selenium/test_uploads.py#L309  but I don't see `galaxy-gtn-screenshots` anywhere in the codebase

Ah, found the PR: https://github.com/galaxyproject/training-material/pull/2271 Which references https://github.com/galaxyproject/ci-testing which hasn't been touched in 2 years (ahh guess they're not automatic then like we thought.)

I really do not understand why that was a separate repo and not part of the GTN, that's a bit, hmm. I guess we need to integrate that. I'll ask around for the aws keys.
