### ISSUE TITLE
Tutorials refer to outdated syntax for advanced search

### ISSUE THREAD

**Issue by thepineapplepirate** [galaxyproject/training-material#3843]
"Searching your history" tutorial

Release testing 23.0

- Now the syntaxes used for advanced search have changed. For example, if you have pdb files in your hx, the tutorial suggests searching for them by “format=pdb”. In the new setup, this would have to be done by “extension:pdb”. This appears to apply to all example search items in the tutorial.

- Also, to search multiple histories, the current UI doesn’t automatically display all histories next to each other (as in the tutorial), the user has to select which histories to add to the panel.

**Comment by jdavcs** [comment]
Does this affect one or multiple tutorials?

**Comment by jdavcs** [comment]
@thepineapplepirate can you, please, verify what tutorial this relates to?

**Comment by thepineapplepirate** [comment]
> @thepineapplepirate can you, please, verify what tutorial this relates to?

yeah this is the "Searching your history" tutorial. 
https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/search/tutorial.html
