### ISSUE TITLE
"Understanding Galaxy History System" tutorial refers to an outdated UI

### ISSUE THREAD

**Issue by thepineapplepirate** [galaxyproject/training-material#3846]
Release testing 23.0

screenshots and associated descriptions need updated for the new UI

this pertains to this tutorial:
https://github.com/galaxyproject/training-material/blob/main/topics/galaxy-interface/tutorials/history/tutorial.md

**Comment by jdavcs** [comment]
Could you, please, provide a more specific description? You don't have to itemize repetitive stuff, but a list of UI elements that are no longer current would be helpful here. Same for associated descriptions: does this relate to the entire tutorial (in which case everything needs to be rewritten), or does that affect specific parts or even steps in the instructions?

**Comment by hexylena** [comment]
I'm going through and updating this one, it's .. a lot of screenshots that need to be changed.

**Comment by thepineapplepirate** [comment]
> I'm going through and updating this one, it's .. a lot of screenshots that need to be changed.

I can imagine :s. I mean honestly I don't think it's necessarily vital and users could probably get by, I just brought it up as per the guidelines in our meetings, and I guess updated screenshots was one of them. Thanks!
