### ISSUE TITLE
Dev - Feedback from GCC

### ISSUE THREAD

**Issue by lecorguille** [galaxyproject/training-material#390]
Some feedbacks from the GCC tool integration training session.

- [x] Remove the curly braces from the coloured wrapper
- [x] Add some quotes around in/output in the coloured wrapper 
- [x] Update the picture in `inputs > param > conditional` to link with the `<param`
- [x] Change the picture in `inputs > param > repeat` to display at least 2 set of the 3 parameters
- [x] Add a picture for `section`
- [x] Add `test` on stdout

@martenson @nsoranzo @mvdbeek @bgruening @davebx @shiltemann @NickSto 
Feel free to add some other comments or tasks

**Comment by nsoranzo** [comment]
xref. https://github.com/galaxyproject/training-material/issues/184

**Comment by lecorguille** [comment]
Fix: https://github.com/galaxyproject/training-material/pull/429/commits/60be7f2f0201a786201124b97e3776bf2a0ce83e
