### ISSUE TITLE
Set tmp_dir in job_conf

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/training-material#3944]
Dear admin trainers,
While you are reformatting the admin training. I wanted to know if you mind to include the `tmp_dir: true` in job conf (https://github.com/galaxyproject/galaxy/blob/1dc25d1bbd9ef28c564c8dc4a9314f6bfd766096/lib/galaxy/config/sample/job_conf.sample.yml#L690) (I can write a PR to one of your branch if you think it is a good idea).
For me, it was really important to set it as usually servers have a fixed size for the `/tmp` partition and in the absence of cleanup scripts which remove old directory in the `/tmp` partition you may fill this partition and then get errors.

**Comment by hexylena** [comment]
> I can write a PR to one of your branch if you think it is a good idea.

yes, please! I will happily merge that, especially if you add a small tip box explaining the values and why you'd choose which one. Your experience is valuable to share here

**Comment by lldelisle** [comment]
On which tutorial (Mapping Jobs to Destinations or Installing Galaxy with Ansible) would you put it?

**Comment by lldelisle** [comment]
So I write it into @natefoo PR #3942 ?

**Comment by hexylena** [comment]
yes please!
