### ISSUE TITLE
How to share/maintain software binaries between Galaxy/HPC ?

### ISSUE THREAD

**Issue by leonorpalmeira** [galaxyproject/training-material#396]
What would be the best practice (or your best thought) on how to share/maintain software binaries (and dependencies) that can be used both within Galaxy (that runs on our HPC) or directly on the HPC from the command-line.

Some of our users might want to run the (exact) same tools either through Galaxy or through the HPC command-line. And we also would like to ease the process of "developing/testing under Galaxy" and then automating/optimizing SLURM scripts to go into production. Having to maintain two Conda setups would be too much of a hassle... ;-)

Currently, we use 'modules' to deal with our HPC software, and we have a fresh Galaxy instance that we are still testing, so any ideas are welcome.

Thanks!

**Comment by bgruening** [comment]
@leonorpalmeira all conda dependencies are available on command line. They are stored in it's own environment which can be easily activated on your HPC cluster. You could also write very simple module scripts that will activate these environments if you like. This would also avoid the strange names of these environments.

Sorry for the late response, conference season.

**Comment by bernt-matthias** [comment]
I would like to extend the question for libraries and tool data (in particular when generated with data  managers).  

For libraries and (old style) tool data this seems to be easy since the data is organized by the admin anyway, but for data_managers this is not obvious for me.

**Comment by bgruening** [comment]
@bernt-matthias data_manager generated data also ends up very structured on your hard-drive isn't it? This location should be already on a shared filesystem, where all HPC users can access it (read-only maybe).

**Comment by bernt-matthias** [comment]
Ah right. I need to read more about this :) thanks!

**Comment by bebatut** [comment]
@leonorpalmeira I hope you had the answers to your question. I am closing this issue. If you think some questions still remain, we can still reopen this issue
