### ISSUE TITLE
GCC 2017 Problems - Conda and Containers Training.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/training-material#397]
- [x] ``conda_env`` needs to be sourced.
- [ ] Mention ``conda lint`` in first exercise.
- [ ] Move skeleton to advanced topics.
- [ ] Markdown broken on tests slide.
- [ ] Don't mention skeleton during exercises slides.
- [ ] Correct install instructions for fleeqtk.
- [ ] Update container slides against @jmchilton's BioContainer slides for GCC 2017 - the are a bit more polished.

Just in general there was probably too much content for this topic and I didn't even cover huge parts of the containers stuff.

**Comment by nsoranzo** [comment]
I think the first point should have been fixed by https://github.com/galaxyproject/training-material/pull/395.

**Comment by erasche** [comment]
@jmchilton is this still an issue?
