### ISSUE TITLE
Extras - Theme  - AU

### ISSUE THREAD

**Issue by GarethPrice-Aus** [galaxyproject/training-material#3976]
The AU theme of GTN is a bit of fun and should stay.
Minor issue - when it reverts to top down text the welcome message has NZ left and right. Should this be a flag or an image? Or could they just be removed?

![image](https://user-images.githubusercontent.com/35213418/229007401-5e735f22-3d61-4e71-8de8-2ab493248f92.png)

**Comment by hexylena** [comment]
ah those are *supposed to be* emoji actually

the flag was a bit of a shitpost, I was having a bit of a go at my aussie friends by intentionally picking the similar looking but wrong flag. But yea, we can remove that.

Do you see the roo and koala? or are those also missing for you?
![image](https://user-images.githubusercontent.com/458683/229056240-ec0ca687-e1ca-4207-92e5-80e04dd9b4b6.png)

**Comment by GarethPrice-Aus** [comment]
Hi Helena

I could see the Roos and Koalas - loved em!
And the flag - nice twist. I do wonder who many people would have noticed. But if they are not rendering...I agree, easier to ditch.

Cheers, G
