### ISSUE TITLE
GCC 2017 Architecture Follow Up

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/training-material#398]
Notes from @natefoo:

We really need to frame the web request response cycle in the context of a particular request. We walk through the stuff but there is no context and I think that is terrible.

Polled the room asking who was interested in hacking:
- The UI: 0 hands
- The backend: Many many hands

Polled the room asking if it was too admin-y or too developer-y
- Too admin-y: no hands
- Too developer-y: ~5 hands

Projects to add:
 - Ephemeris
 - Parsec
 - Kickstart

Components to add:
 - Jobs
 - code structure w/ diagrams
 - JobDestination objects
 - Job flow
 - Status changes
 - Code flow (jobwrapper.prepare() -> runner.queue_job() -> ...
 - GIEs?
 - Containers???
 - Update to latest usegalaxy.org slides.

Random stuff:
 - Reorder WSGI slides: outline/text before the figure
 - DrammaJobRunner -> DrmmaJobRunner
 - Object Store UML should show that the non-nested Object Store plugins are also children of the nested ones
 - Managers are currently discussed at a random point in the slides - should probably go between controllers and model
Non-slide stuff:
 - Document webless handlers
 - Document job_conf.xml plugin workers attrib

**Comment by erasche** [comment]
Hey @jmchilton would you have time or interest for any of this today during the CoFest? Should we close this or assign it to someone else to do for the next gcc?

**Comment by jmchilton** [comment]
I don't think I am going to get to it today - but I thought my presentation of these slides in 2019 was even more .... problematic. They're quite out of date. I'll get to this before the next GCC I'm sure, happy to have others take a pass or two at presenting things better before then.

**Comment by hexylena** [comment]
Closing due to #1906
