### ISSUE TITLE
GCC 2017 - collapsing boxes

### ISSUE THREAD

**Issue by bagnacan** [galaxyproject/training-material#399]
Would be nice to put additional information about a specific subject (within a tutorial) in a box that can be opened and closed. This way additional information can be hidden, and accessed "on-demand" without tampering with the overall outline. What do you think?

**Comment by bgruening** [comment]
For technical details and in-depth biological details this would be super nice I think.

**Comment by bgruening** [comment]
Similar to the Q box?

**Comment by bebatut** [comment]
This is now possible since #781 has been merged
