### ISSUE TITLE
Localization of training material

### ISSUE THREAD

**Issue by manabuishii** [galaxyproject/training-material#404]
How about translation ( localization , internationalization ) of training-material ?
At least we need main Galaxy  translation coverage more higher.
And tool translation is needed (https://github.com/galaxyproject/galaxy/pull/4251).

I hope that we discuss about traininge-material translation .

**Comment by bebatut** [comment]
Thanks for opening this discussion! It could be great to have translations of the training material.
Do you have in mind a possible solution for the training material? 
We need to keep in mind to avoid any redundancy, and the solution must be quite automatic.

Any idea?

**Comment by bgruening** [comment]
@manabuishii @yvanlebras we discussed this issue during our Hackathon in Norwich and wondered how good Google Translate is for your languages?

If possible we would try to make the sentences we use easier to translate for Google translate and Co. Ideally, but I have not found it yet, we could annotate our text in HTML to give Google hints how to translate text.

Do you think this is possible and would help, even if its not a manual high quality translation?

**Comment by anilthanki** [comment]
Hi

If you use "class=notranslate" or <code> tags, content within won't be translated by Google Translate. It an be useful for tools and parameters name, and labels, etc

I hope it helps

**Comment by bgruening** [comment]
@anilthanki awesome! Do you have a reference for this? That is exactly what we need. We could tag our special boxes with this.

**Comment by yvanlebras** [comment]
Thanks for the update and groovy news !!! If we can try something @anilthanki @bgruening on our side, don't hesitate !!!

**Comment by anilthanki** [comment]
@bgruening sure here it is... https://www.w3schools.com/tags/att_global_translate.asp @nsoranzo

**Comment by bgruening** [comment]
@yvanlebras what I would like to know is if you have the feeling that google-translate or similar engines are good enough to translate the training in general. We try as hard as we can to improve it and provide hints to the engine but I guess they need to be at least good in the first place.

**Comment by yvanlebras** [comment]
@bgruening google-translate was realy not good but it appears to be best now.... so maybe ok... don't know if this can be ok for the training materials... We have to test! Did you want we (Galaxy-E) have a look on it?

**Comment by bgruening** [comment]
Please yes! :)
Would be nice to know if its good`ish and if we should try to enhance the translation by marking paragraphs as non-translatable or other hints.

**Comment by manabuishii** [comment]
Currentlly I don't know more useful translation tool than Google Translate .
When I translated some documents were,  we use translation tool after that we proofreading.
We don't use just only google translate to keep quality of documents, checking the quality by Japanese Community Members.
But it's good starting point.

As aspect of translation managing tool, we use Google Docs, but now we try https://hackmd.io/ this is a online collaboration MarkDown editor.

**Comment by manabuishii** [comment]
[Japanese Translation for 3 tutorials by A\-Asai · Pull Request \#862 · galaxyproject/training\-material · GitHub](https://github.com/galaxyproject/training-material/pull/862)

**Comment by frederikcoppens** [comment]
It seems you can build a link where you can choose the target language and the page. An example, generated by putting the URL in translate.google.com. Both changing the URL it points to (u=http...) and the language (tl=nl in example) seems to get the desired effect. 

https://translate.google.com/translate?sl=auto&tl=nl&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fgalaxyproject.github.io%2Ftraining-material%2Ftopics%2Fintroduction%2Ftutorials%2Fgalaxy-intro-peaks2genes%2Ftutorial.html&edit-text=&act=url

**Comment by bebatut** [comment]
Discussions about that during the last GTN meeting #954:

- There is an open PR for a translated tutorial. We all agree it is a good idea, but how do we deal with this? Do we keep a manual translation, do we have some that are manually done, some that are automatic/linked via google translate?
- We submitted a proposal for MozFest for automatic translation of community documentation. We will hopefully gather ideas from the community there. But no clear solution?
- Berenice tried to 'trick' the API to have it avoid translating specific portions of the page
- Gildas notes that google already proposes to translate things whenever your browser is in a different language to the webpage.
- Bjoern suggests that we add something on the template to link to the google translate URLs. We need to highlight on the front page that the current system is google translate and you should use.

**Comment by erasche** [comment]
Translation now integrated as part of #1131 #1143, left open for discussion?

**Comment by erasche** [comment]
The automatic translation seems to be working well for most cases. If there is still the need for localisation of the materials we should re-open this issue. Thanks y'all!
