### ISSUE TITLE
Wrong link in "options-for-using-galaxy" slides ("introduction" topic)

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#417]
As @shiltemann point out in #413, we are not sure where `https://www.genome-cloud.com/` in `topics/introduction/tutorials/options-for-using-galaxy/slides.html` should point

**Comment by nsoranzo** [comment]
It seems they went out of business, the website was down already at the Hackathon in Cambridge. Ping @tnabtaf

**Comment by tnabtaf** [comment]
Thanks for the heads up.  And that's bad news.  :-/  I'll look into this and fix it here and in the hub.

I would assign this to me, but I can't assign issues in this repo.  (Feel free to do so!)

**Comment by bgruening** [comment]
Added you to this repo and assigned it to you. Thanks Dave.

**Comment by tnabtaf** [comment]
Fixed in commit e1743b8911d929df8cd344700da84f9dffa6db60
