### ISSUE TITLE
Automatic Jupyter Notebooks not working

### ISSUE THREAD

**Issue by wee-snufkin** [galaxyproject/training-material#4220]
I wanted to open an automatically generated Jupyter Notebook from [one of the tutorials](https://training.galaxyproject.org/training-material/topics/single-cell/tutorials/scrna-case_monocle3-rstudio/tutorial.html) with this option, but got the following error:
`File Load Error for single-cell-scrna-case_monocle3-rstudio.ipynb
Unreadable Notebook: /data/jwd01/pulsar_staging/60901074/working/jupyter/single-cell-scrna-case_monocle3-rstudio.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "metadata": {\\n "kernelspec": {...')`

I also checked notebooks from other tutorials ([Scanpy TI](https://training.galaxyproject.org/training-material/topics/single-cell/tutorials/scrna-case_JUPYTER-trajectories/tutorial.html), [pangeo](https://training.galaxyproject.org/training-material/topics/climate/tutorials/pangeo-notebook/tutorial.html)) and they also don't work. It was not the case some time ago.

**Comment by hexylena** [comment]
ah shoot, that should've been caught, we have a linter for exactly that. I'll look into it

**Comment by wee-snufkin** [comment]
Fixed now, thanks!
