### ISSUE TITLE
Small screen print bug in GC-MS with xcms tutorial

### ISSUE THREAD

**Issue by yguitton** [galaxyproject/training-material#4255]
Hi

When opened in Galaxy the GC-MS with xcms tutorial show some code (for sure just a matter of , or . somewhere, but I'm not able to correct it on my own.)  Screenshot from Chrome, server usegalaxy.fr
![image](https://github.com/galaxyproject/training-material/assets/5373737/1e851ed3-617a-4cd4-814b-e144a4dfc6b2)

@hechth @melpetera any clue?

Best
Yann

**Comment by hexylena** [comment]
ah this can be due to spacing, adding a newline around the snippets should fix it

**Comment by xtrojak** [comment]
This snippet use to work just fine, we did no change in the tutorial since then.

@hexylena adding newlines does not help

**Comment by hexylena** [comment]
> we did no change in the tutorial since then.

Yes, but we (the GTN) have made changes over time that can cause this. I guess I will look into it, thank you for testing the newlines.

**Comment by xtrojak** [comment]
Actually it works just fine after the changes you did here https://github.com/galaxyproject/training-material/commit/d44643e11e471f33e099f3af36373bc96cbd49f6.

**Comment by hechth** [comment]
@yguitton can you check if the problem disappeared?

**Comment by hexylena** [comment]
https://training.galaxyproject.org/training-material/topics/metabolomics/tutorials/gc_ms_with_xcms/tutorial.html#hands-on-data-exploration looks fixed to me
