### ISSUE TITLE
Automated notebooks don't include images

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/training-material#4305]
We're making a bunch of automated notebook tutorials and have just realised that images embedded (and successfully rendering in the GTN site) don't appear in the notebooks. 
Is there a way to make them pull from their GitHub repo like in the tutorial?
![Screenshot 2023-07-25 at 13 10 39](https://github.com/galaxyproject/training-material/assets/44605769/669f2b34-f6f6-4d9f-b8c3-9a9ae18dcdf6)

@hexhowells found this

**Comment by hexylena** [comment]
they're definitely supposed to, the images are encoded as a base64 PNG file within the notebook intentionally so they work without network access. I'm not sure why they aren't showing up, which tutorial is this so I can reproduce it?

**Comment by nomadscientist** [comment]
https://training.galaxyproject.org/training-material/topics/single-cell/tutorials/scrna-case_JUPYTER-trajectories/tutorial.html

**Comment by nomadscientist** [comment]
https://training.galaxyproject.org/training-material/topics/single-cell/tutorials/scrna-case_JUPYTER-trajectories/tutorial.html
