### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/training-material#4311]
Hi - can we please get the (horizontal flipped) version of this icon in the training icons section? https://thenounproject.com/icon/hide-5247530/

We need it to tell users to select 'show hidden' datasets in this tutorial: https://training.galaxyproject.org/training-material/topics/single-cell/tutorials/scanpy_parameter_iterator/tutorial.html#number-of-neighbours-to-derive-knn-graph-for-scanpy-computegraph-tool

**Comment by wee-snufkin** [comment]
Oh yeah, having that tiny icon would be fab!
@shiltemann do you think we could have it added to the [list of available icons](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/create-new-tutorial-content/faqs/icons_list.html)? I wish I could add it myself if I knew how!

**Comment by hexylena** [comment]
> I wish I could add it myself if I knew how!

These are in `_config.yml`, there you'll find the list of icons as well as their font-awesome codes. Please check https://fontawesome.com/search?q=eye&o=r for the correct eye (we do not have 'pro'). Thanks for offering to fix it :)

**Comment by shiltemann** [comment]
I think the icon you are looking for is [fa-eye-slash](https://fontawesome.com/icons/eye-slash?f=classic&s=solid)

So if you add a line like this

```
galaxy-show-hidden: fas fa-eye-slash
```

near [this line in _config.yml](  galaxy-scratchbook: fas fa-th)

It should be available to use as {% icon galaxy-show-hidden %}

 (and should also automatically appear in the list of available icons FAQ that @wee-snufkin referenced, so no update needed there)

**Comment by wee-snufkin** [comment]
Already done [here](https://github.com/galaxyproject/training-material/pull/4334)!
