### ISSUE TITLE
minor feature request on tags

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/training-material#4389]
I know tags are being used for a heap of reasons, but when a page is - for example - 'single cell', the 'single cell' tags then are annoying to see.

Is it possible to mute a single tag on a training page? They can stay on the tutorials themselves, just if the page itself is ALL of that tag, perhaps it could be not shown?

**Comment by hexylena** [comment]
In general I think our rule is "don't tutorials in topic X with tag X" because that's redundant. You could probably just remove all of those instances? Unless you're relying on them being there for some purpose

**Comment by nomadscientist** [comment]
ahhhh ace! I was only including them in advance of potentially making tags auto-create their own page
Awesome, I'll remove them, thanks!
