### ISSUE TITLE
Error when running workflow for Filter, Plot and Explore Single-cell RNA-seq Data tutorial

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/training-material#4391]
When running the workflow published in the tutorial https://training.galaxyproject.org/training-material/topics/single-cell/tutorials/scrna-case_basic-pipeline/tutorial.html (with the published starting dataset) one of the last steps where it is renaming the clusters into cell types fails with:

```
Traceback (most recent call last):
  File "/drive/configs/tmpzfs90vu9", line 9, in <module>
    adata.rename_categories(
  File "/usr/local/lib/python3.9/site-packages/anndata/_core/anndata.py", line 1133, in rename_categories
    self.obs[key].cat.rename_categories(categories, inplace=True)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/accessor.py", line 92, in f
    return self._delegate_method(name, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/arrays/categorical.py", line 2487, in _delegate_method
    res = method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/arrays/categorical.py", line 920, in rename_categories
    cat.categories = new_categories
  File "/usr/local/lib/python3.9/site-packages/pandas/core/arrays/categorical.py", line 634, in categories
    raise ValueError(
ValueError: new categories need to have the same number of items as the old categories!
```

Most likely because there are more clusters than cell types being mentioned here:

```
adata.rename_categories(
    key='louvain',
    categories=['DP-M4', 'DP-M3', 'DP-M1', 'T-mat', 'DN', 'DP-L', 'DP-M2', 'Macrophages'])
```

Looking at markers, there are 9 clusters (0 to 8), however there are 8 cell types in the tutorial. This is running on singularity containers, so no modification in the environments. Maybe @nomadscientist can ping the workflow author?

**Comment by pcm32** [comment]
In the newer run we see these clusters:

![image](https://github.com/galaxyproject/training-material/assets/368478/106c4c88-182c-45ec-ba85-faa44e130b2b)

In the tutorial, we see these clusters:

![image](https://training.galaxyproject.org/training-material/topics/single-cell/images/scrna-casestudy/wab-3visualisations.png)

So I suspect that:

1. - From 0 to 4, everything seems very similar
2. - Cluster 5 and 6 are swapped: Cluster 5 in the new one (first figure) is number 6 in the old one (second figure), and the opposite (6 new == 5 old).
3. - New cluster 7 was a part of old cluster 3
4. - Old cluster 7 == new cluster 8

So, besides ignoring point 3, I would say that new order is:

DP-M4,DP-M3,DP-M1,T-mat,DN,DP-M2,DP-L,Unknown,Macrophages

**Comment by pcm32** [comment]
But maybe there are smaller filtering changes somewhere done differently between tutorial and final workflow.

**Comment by nomadscientist** [comment]
ahhh have the tools been updated? Every time the tools update the filtering changes slightly
It's also possible that we updated the tutorial but didn't upload an up-to-date workflow in the last tutorial update
Either way, I'll look into it, thanks so much!

**Comment by pcm32** [comment]
I ran the workflow file that is linked in the tutorial, I didn't run tools manually, which guarantees that the tool versions are the same.

**Comment by nomadscientist** [comment]
<img width="412" alt="Screenshot 2023-10-07 at 17 59 13" src="https://github.com/galaxyproject/training-material/assets/44605769/44ba2fab-a22c-41ed-b645-7423ec265a90">
which of these two did you run?

**Comment by pcm32** [comment]
I got it from the tutorial page itself at the bottom:

![image](https://github.com/galaxyproject/training-material/assets/368478/18466166-538c-4a26-ac7c-373d09028121)

**Comment by nomadscientist** [comment]
Right, so this just got really weird.
I ran that workflow from within the Galaxy interface and it did work fine.
I also ran - just to check - the workflow from the screenshot I sent you (the updated workflow) and it also worked fine.

So... I'm stumped. Where are you running it? Is it possible it's calling slightly different tools?

**Comment by pcm32** [comment]
I'm running on slurm with singularity, I suspect that usegalaxy.eu uses singularity as well. If not the reason might be down to that. When opening the workflow it never complained about missing versions, so it is using at least the version set on the workflow.

**Comment by nomadscientist** [comment]
Hmm... ok, well, I guess it works on a public instance? Or maybe somehow the cluster calling sets a seed on the public instance it isn't on yours, because there are those ML tools in there that can vary, maybe?

**Comment by pcm32** [comment]
I remember having a conversation with Malte many years ago where he was telling me that scanpy had no control on some random seeds from some underlying libraries for louvain or for UMAP, I can't remember. The side effect was that on different hardware, all things the same (and we are achieving that through versioning and singularity containers) you could get slightly different results. Maybe this is one case of that. So if you still get the same result on other hardware, I would leave it.

**Comment by nomadscientist** [comment]
Cool - I'll close this but keep it in mind if people on other instances have a similar issue
