### ISSUE TITLE
Website does not look "nice" on IE 11

### ISSUE THREAD

**Issue by willdurand** [galaxyproject/training-material#440]
Hi, I just noticed that the website does not look usable on IE 11 (at least). It is only a matter of CSS so I guess I could open a PR soon-ish.

**Comment by willdurand** [comment]
I believe #463 fixes this issue.

**Comment by nsoranzo** [comment]
@willdurand Close?

**Comment by willdurand** [comment]
Yup, thanks for the reminder!
