### ISSUE TITLE
Url of the training material

### ISSUE THREAD

**Issue by joachimwolff** [galaxyproject/training-material#441]
`http://training.galaxyproject.org` is redirected to `https://galaxyproject.github.io/training-material/`
but `https://training.galaxyproject.org` is redirected to `https://galaxyproject.org/`.

I think both, http and https should redirect to the same URL.

**Comment by bebatut** [comment]
ping @natefoo

**Comment by natefoo** [comment]
Fixed, thanks for the heads up (and @martenson - galaxyproject/infrastructure-playbook#18)

**Comment by bgruening** [comment]
Thanks Nate!
