### ISSUE TITLE
Unseen / draft mode of Learning Pathway

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/training-material#4419]
I want to induct interns/PhD students with certain things that I might want a more 'temporary' or less public Learning Pathway for. Is it possible to make pages unseen and share-via-link only?

**Comment by hexylena** [comment]
Definitely possible to add draft mode, good suggestion

**Comment by hexylena** [comment]
by "we can definitely add this" I meant "I had already added it on october 6th, and forgotten abut it, because it was on a branch I forgot existed."
