### ISSUE TITLE
Stable API

### ISSUE THREAD

**Issue by joachimwolff** [galaxyproject/training-material#444]
Would it be possible to have a stable API to create the training tutorials? You can add as many new features as you like to a development branch and release a new version from time to time.
The way it is now is a kind of annoying; as a content creator you have to check regularly for new functions. With a stable render API this could be solved.

Thanks for considering.

**Comment by bebatut** [comment]
I think the project is not mature enough to have that... We are doing our best not to break existing things, but we also don't want to slow down progress with a stable API.

Currently, we are collecting everything (including the feature changes) in the [Train the trainers](http://galaxyproject.github.io/training-material/topics/training/) topics, and particularly the ["Writing content in markdown"](https://galaxyproject.github.io/training-material//topics/training/tutorials/create-new-tutorial-content/tutorial.html).

**Comment by erasche** [comment]
I think this is mostly solved with the planemo script that converts a workflow to a tutorial, and the planned improvements around that. There have been some ongoing discussions for the utility of an API or website to convert a workflow more easily into a training and potential editors for training materials.
