### ISSUE TITLE
QC-Material

### ISSUE THREAD

**Issue by joachimwolff** [galaxyproject/training-material#447]
Given issue #63 @mwolfien is responsible for the QC material. 
@mwolfien Could you please update the slides and the hands-on tutorial? All the y-axes annotations are missing. 

Thanks a lot!

**Comment by bebatut** [comment]
Thanks for your issue. 
The role of a maintainer is obviously not clear and needs to be clarified. I will add a section in the CONTRIBUTING.md to explain it.

FYI (as mentioned in #63) a maintainers is more a role of an editor/reviewer (checking the changes, checking the format, checking if nothing is missing, ...) than to keep that the material up to date. It is more the role of instructors to update the materials they will use during training and the maintainer will review these changes.
