### ISSUE TITLE
auto-generated test file names are not accepted by github CI

### ISSUE THREAD

**Issue by thawn** [galaxyproject/training-material#4506]
as requested in pull request #4493 , I generated test files as described [in the tutorial](https://training.galaxyproject.org/training-material/faqs/gtn/gtn_workflow_testing.html). However, `planemo workflow_test_init` generated files named `<workflow name>_tests.yml` however, the CI complained that the workflows should be named <workflow name>-test.yml`

I would expect the names of automatically generated test files to match the expectation in the gitlab CI.

**Comment by hexylena** [comment]
we have expanded the list of permitted names
