### ISSUE TITLE
Gives 'better' tool_panel_section_label in the tool YAML

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/training-material#4513]
First of all, this is super cool to have the `Galaxy Administrators: Install the missing tools` section :heart: .
I think it would be even better if we could improve the tool_panel_section_label.
My idea would be to use https://github.com/usegalaxy-eu/usegalaxy-eu-tools and/or https://github.com/galaxyproject/usegalaxy-tools to attribute the good section label.
@hexylena proposed to:
```
generate a list of ids → sections, we could pull from the big 3 and use an algorithm like "if 2 agree, use that."
```

**Comment by lldelisle** [comment]
If we generate such a list, it would be super useful for a lot of perspectives, for example in IWC: https://github.com/galaxyproject/iwc/issues/281.
I proposed this to be a ephemeris tool (https://github.com/galaxyproject/ephemeris/issues/206) but maybe the ephemeris tool could simply use this list.

**Comment by hexylena** [comment]
Yes, we could provide a .json file that ephemeris could consume perhaps, like we do for other data products currently (toolshed version database)

**Comment by hexylena** [comment]
done eu + org before I ran out of time (meetings), will do au after.

**Comment by hexylena** [comment]
Misc statistic for the admins:

```
   1198 1 => 1 # unique
    707 2 => 1 # on 2 but 1 label
    173 2 => 2 # on 2 with two labels
    462 3 => 1
    188 3 => 2
     20 3 => 3 # All three disagree
```

**Comment by lldelisle** [comment]
Do the statistics count for the 'fixed' categories in eu or just the one exposed to api?

**Comment by hexylena** [comment]
these are just based on the tool repo APIs, not anything from galaxy. I might be missing what you mean by fixed

**Comment by lldelisle** [comment]
By fixed I meant the tools that go to multiple panels in tool repo of eu.
