### ISSUE TITLE
galaxy service is not up

### ISSUE THREAD

**Issue by sivap083** [galaxyproject/training-material#4531]
when is ran the sudo galaxyctl status command after executing the playbook. I am getting the below error.
Dynamic handlers are configured in Gravity but Galaxy is not configured to assign jobs to handlers dynamically, so these handlers will not handle jobs. Set the job handler assignment method in the Galaxy job configuration to `db-skip-locked` or `db-transaction-isolation` to fix this.
  UNIT LOAD ACTIVE SUB DESCRIPTION
0 loaded units listed.
To show all installed unit files use 'systemctl list-unit-files'.

**Comment by hexylena** [comment]
Hi @sivap083 depending where you are in the https://training.galaxyproject.org/training-material/topics/admin/tutorials/ansible-galaxy/tutorial.html tutorial, this is currently expected, please continue further on until the job handlers are properly configured.
