### ISSUE TITLE
broken links on slides

### ISSUE THREAD

**Issue by erxleben** [galaxyproject/training-material#457]
In the slides of "Galaxy Introduction" -> "Introduction" slides, the following links are not working:
on slide 25
- Options for using Galaxy
- Getting data into Galaxy
*******************************
In the slides of "ChIP-Seq data analysis" -> "Introduction" slides, the following link is not working:
on slide 8
- Introduction to Genome Assembly
- Edit on "GitHub"

**Comment by shiltemann** [comment]
thanks for reporting this @erxleben :) should be fixed in #458
