### ISSUE TITLE
Add Bioschemas to all training material to be queried by TeSS

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/training-material#46]
http://bioschemas.org/

**Comment by bebatut** [comment]
What we need to do for that?

**Comment by frederikcoppens** [comment]
Adding tags to identify the different elements (title, description, ...) to the html is one option, providing a json another. Niall Beard ( @njall on github ) from the Tess team can provide more details.

You can find an example how we did it using html tags in the source code for this page https://www.bits.vib.be/training-list/111-bits/training/previous-trainings/165-qbaseplus-training
This results in this TeSS entry: https://tess.elixir-uk.org/materials/analysis-of-qpcr-data-using-qbase

**Comment by bgruening** [comment]
A json file would be nice. I have a few different usecases in mind for this additional annotation.
On Sep 29, 2016 9:28 PM, Frederik Coppens <notifications@github.com> wrote:Adding tags to identify the different elements (title, description, ...) to the html is one option, providing a json another. Niall Beard ( @njall on github ) from the Tess team can provide more details.

You can find an example how we did it using html tags in the source code for this page https://www.bits.vib.be/training-list/111-bits/training/previous-trainings/165-qbaseplus-training
This results in this TeSS entry: https://tess.elixir-uk.org/materials/analysis-of-qpcr-data-using-qbase

**Comment by njall** [comment]
Hello!

Is this repository rendered with Jekyll? I once wrote something for Data carpentry that added metadata about training materials and rendered them as JSON-LD. 
This is the commit
https://github.com/datacarpentry/lesson-template/commit/3a242791243f49670f2b857b2375eafd74ed598c

Basically you can add bit of YAML metadata to the top of each training materials md file, and then use a common template to render the metadata variables.
e.g. specify here: https://github.com/datacarpentry/lesson-template/blob/gh-pages/index.md
render here: https://github.com/datacarpentry/lesson-template/blob/gh-pages/_layouts/lesson.html#L16-L51

**Comment by bgruening** [comment]
@njall glad to see you here! :)
I was thinking that a extra yaml file is more clean, but this template looks nice with the table. Any preference for yaml-file vs. embedded markdown?

**Comment by bebatut** [comment]
But this repository is not rendered with Jekyll. We use reveal.js for the slides and GitHub markdown for the hands-on tutorials. So maybe an extra yaml/json file would be more clean

**Comment by bebatut** [comment]
The training material is automatically scrapped and added to Tess: https://tess.elixir-europe.org/content_providers/galaxy-training#materials
I think we can close this issue now

**Comment by bgruening** [comment]
This is still relevant as it makes the scraping much more reliable and standard compliant.

**Comment by bebatut** [comment]
I thought it was just for the Tess integration. How do you see it?

**Comment by bgruening** [comment]
It is useful way beyond TeSS. It will potentially improve google seaches etc ...

**Comment by bebatut** [comment]
I think this issue has been fixed with #780. @njall @bgruening what do you think?

**Comment by bgruening** [comment]
Jupp, thanks to @njall this can be closed :) 
Thanks a lot again!
