### ISSUE TITLE
Source logo of GTN

### ISSUE THREAD

**Issue by willdurand** [galaxyproject/training-material#461]
Hi!

I am looking for a modifiable version of the GTN logo to make it prettier on a dark background. Does anyone have it? The `favicon.ico` has been generated without text too, so I guess there must be a version of the logo (without text) somewhere.

Thanks!

**Comment by bebatut** [comment]
ping @tnabtaf

**Comment by tnabtaf** [comment]
Sorry.  Just got to this.  @willdurand I sent @jxtx a version of the circle / star earlier today that has a text layer and an image layer (Gimp). I can post that to the logos page if that would help.

**Comment by willdurand** [comment]
Yes please :)

**Comment by jxtx** [comment]
I worked up an SVG but it is overly large. Need to retrace the star.

**Comment by tnabtaf** [comment]
Posting a number of options to the logos page shortly.  I can post the GIMP sources too.  @jxtx, anything bigger than half a meg will go in the depot.

**Comment by tnabtaf** [comment]
Take a look at https://galaxyproject.org/images/galaxy-logos/#galaxy-training-network.

Please let me know if one of those does not work for you.

**Comment by willdurand** [comment]
Wonderful, thanks!
