### ISSUE TITLE
Multiple CYOAs in one tutorial?

### ISSUE THREAD

**Issue by wee-snufkin** [galaxyproject/training-material#4664]
Hi, I encountered problems while trying to [include several CYOAs in my tutorial](https://github.com/galaxyproject/training-material/pull/4590/commits/667b275c05df2953c6d4b739c1e844768617143c) - first box rendered well, but others showed only one option and with the second option the tutorial collapsed. Then I tried [renaming the options](https://github.com/galaxyproject/training-material/pull/4590/commits/27a6bae2d8ca973d3f980f667c5c6f3849bb747b) so that they are not the same throughout the tutorial but it didn't help. That's not a big deal since the tutorial works fine with only one CYOA so [I've changed it back](https://github.com/galaxyproject/training-material/pull/4590/commits/23ffae96bfa5f54e225db5730978f769c1f29dea), but I'm just curious if that's some kind of a limitation of this method or something wrong with my formatting. If that's the former, it would be great to add a note for future tutorial developers that they can only include one CYOA so that they don't waste time on reformatting tutorials multiple times :)

**Comment by hexylena** [comment]
This _ought_ to work, but I have my suspicions for why it doesn't. I will look into it.
