### ISSUE TITLE
Expand the details regarding training resources accessible through the API

### ISSUE THREAD

**Issue by heisner-tillman** [galaxyproject/training-material#4710]
This Issue is connected to #4647, where the aim is to onboard all tutorials to the European Open Science Cloud (EOSC) Portal. 

EOSC offers an API to onboard training resources and they require a specific schema, when uploading training resources. Luckily almost all of the required fields can be extracted via the Galaxy Training Network API. By making a `GET` request to receive the topics - _`https://training.galaxyproject.org/training-material/api/topics/{topicID}.json`_ - it is possible to gather the necessary information for each tutorial. 

I am currently working on a script that is able to do this automatically and to fill in the schema of the EOSC API the following field is missing:

**Version Date(s) - The version date for the most recently published or broadcast resource.**

If it is possible to add the `Last Modification` field - see below for example - to the JSON received by making the mentioned `GET` request that would be awesome .
![image](https://github.com/galaxyproject/training-material/assets/117033448/ae109a11-e0ff-4f90-b8c7-abdecc54398c)

**Comment by hexylena** [comment]
Yep, we can add that, no worries.

**Comment by hexylena** [comment]
We (GTN leads) would be interested in how this will work and be maintained, for what it's worth. Is there a GTN page in the EOSC portal that we need to have access to, to keep logos/descriptions/etc updated? Is that being taken from our json-ld or similar? I guess this is the first @bebatut or @shiltemann or I have heard of it other than the #4647

**Comment by heisner-tillman** [comment]
> We (GTN leads) would be interested in how this will work and be maintained, for what it's worth. Is there a GTN page in the EOSC portal that we need to have access to, to keep logos/descriptions/etc updated? Is that being taken from our json-ld or similar? I guess this is the first @bebatut or @shiltemann or I have heard of it other than the #4647

For now it is all automatically taken from the json-ld. The goal is to run the script automatically every day. Once I am done and everything works I will let you know. At that point feedback on the mapping from the json-ld to the schema the of the EOSC would be very welcome and much appreciated!

Here is the link for the script: https://github.com/heisner-tillman/onboard_training_eosc

**Comment by hexylena** [comment]
Top, thanks @heisner-tillman! We can perhaps integrate it then into the GTN directly, we've got a number of other cron tasks. 

comments on the script:

- Perhaps it's useful to add multiprocessing (threads or processes, both should be fine) to your script at some point, I'm guessing it'll be largely network wait bound and that'll decrease the github actions minutes.
- license is in the tutorial metadata, and we'll need to use it-- we have a couple of MIT and Apache-2.0 licensed tutorials amongst the cc-by.
- access rights are always open, yes, we have no restricted or paid materials
- for the placeholder email you could use `galaxytrainingnetwork@gmail.com`

**Comment by hexylena** [comment]
very exciting though!
