### ISSUE TITLE
Divide up galaxy training list

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/training-material#4725]
The tutorial list of topics is super long these days.
Could we divide out into 3 sub-sections of 'Galaxy for scientists', for: Introduction (top button), FIELD and Molecule (or Technology also works)

<img width="328" alt="Screenshot 2024-02-13 at 15 34 50" src="https://github.com/galaxyproject/training-material/assets/44605769/2705861c-b765-467e-92b0-89e2fa8f2903">

I spend a lot of time going "Scroll down, but not that far, now find single cell" to users

**Comment by hexylena** [comment]
ugh yeah. it's been a discussion for ages, but this is a decent organisation! I like it!
