### ISSUE TITLE
Redirect tutorial feedback to a new issue ticket

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/training-material#4729]
Max comments was reached later last year for https://github.com/galaxyproject/training-material/issues/989

![Screen Shot 2024-02-15 at 3 54 12 PM](https://github.com/galaxyproject/training-material/assets/8999735/f4fab306-4530-4820-8199-220f6c1566bc)

**Comment by hexylena** [comment]
Woah, fascinating! I didn't know there was a maximum.

But ok, I don't think anyone was using that really, most of us unubscribed from that issue a *long* time ago. Maybe we can just sunset the feature and explore different ways in the future to share those comments with authors

**Comment by hexylena** [comment]
Will be fixed in https://github.com/galaxyproject/training-material/pull/4739

**Comment by hexylena** [comment]
@shiltemann can you remove the script that posts to github?
