### ISSUE TITLE
reorder the topic section

### ISSUE THREAD

**Issue by martenson** [galaxyproject/training-material#477]
Currently it feels fairly random, Galaxy Introduction should definitely be first, genomics topics should probably be grouped etc.

**Comment by bgruening** [comment]
Agree! `Tutorials using public Galaxy at usegalaxy.org` should be removed and the topics grouped accordingly. The association to instances will happen as part of the metadata.

**Comment by martenson** [comment]
Also the mixture of grouping per Main presence and grouping per domain is confusing.,

**Comment by nsoranzo** [comment]
xref. https://github.com/galaxyproject/training-material/issues/335

**Comment by bgruening** [comment]
This should be fixed by: https://github.com/galaxyproject/training-material/pull/543
@martenson ok for you. I will open a new one to re-integrate the `usegalaxy.org` tutorials.

**Comment by martenson** [comment]
@bgruening much beter, thanks for lcosing the issue

**Comment by martenson** [comment]
well, I did not notice you didn't lol, thanks @bebatut !
