### ISSUE TITLE
Spaces showing up for Zenodo links but absent from md

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/training-material#4853]
Hi -- someone noticed that the input URL in this tutorial have a space introduced into the copy functions but that the markdown doesn't include the space! Any idea what is happening or how to fix it? 

I checked in the editor and found the same. Then I spot check other tutorials and didn't notice problems in those.. so not a site wide problem. 

https://training.galaxyproject.org/training-material/topics/microbiome/tutorials/nanopore-16S-metagenomics/tutorial.html

Reported at https://help.galaxyproject.org/t/16s-microbial-analysis-tutorial/11968

**Comment by hexylena** [comment]
it's down to the spacing in markdown, I really hate how markdown handles spacing. I've pushed a fix.
