### ISSUE TITLE
Not showing Docker image when none provided

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#486]
To avoid: 
![screen shot 2017-08-31 at 09 39 20](https://user-images.githubusercontent.com/1842467/29911965-4bd2446e-8e30-11e7-8c19-0bdf0231ae22.png)

Need to adapt the tests in [`_layouts/topic.html`](https://github.com/galaxyproject/training-material/blob/master/_layouts/topic.html)

**Comment by bgruening** [comment]
Also the link at the top should be hided at this page.

**Comment by bebatut** [comment]
which link?
