### ISSUE TITLE
Moving the "Thanks" slide at the end of the slide deck?

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#487]
Currently the slide

![screen shot 2017-08-31 at 09 41 45](https://user-images.githubusercontent.com/1842467/29912063-a17d6222-8e30-11e7-84f9-13821be36993.png)

is the first one...

Maybe we could move it at the end of the slide deck. What do you think?

**Comment by bgruening** [comment]
Welcome should not be at the end ;) But yes the collaborative work thingy can ... :)
We probably don't need a welcome slide.
