### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#489]
Hi @galaxyproject/training,

I think we need to reopen the question of the maintainers #63 and update it.

> A maintainer acts as editors. She is responsible for making sure issues and change requests are looked at. She has the final say over what is included in the training material related to the topic. But, she is not responsible for writing training material content or deciding what lessons ought to exist, both coming from the community.

It could be great if we could get at least 2 per topic...

Otherwise as discussed in #307, we may hide the topic from the website if the tests are failing.

Can you check the following list, based on the current maintainers and some propositions? 

Topic | Maintainers
--- | ---
admin | @bgruening, @martenson, @erasche, @hrhotz?
assembly | @Slugger70
chip-seq | @malloryfreeberg, @MoHeydarian?, @friedue?
dev | @lecorguille, @bebatut, @erasche, @shiltemann?
epigenetics | @joachimwolff, @dpryan79?
introduction | @tnabtaf, @nsoranzo?
metagenomics | @bebatut, @shiltemann
proteomics | @Stortebecker, @bgruening, @blankclemens
sequence-analysis | @yvanlebras, @bebatut, @joachimwolff
training | @bebatut, @bgruening
transcriptomics | @bebatut, @malloryfreeberg, @friedue?
variant-analysis | @TorHou?, @nekrut?

I will update the metadata according to that afterwards

**Comment by erasche** [comment]
I'm happy to review stuff but I do not follow issues regularly unless I'm pinged on them. I went looking for the code that automatically determines maintainer and pings them but found this along the way. https://github.com/blog/2392-introducing-code-owners might be interesting?

**Comment by bebatut** [comment]
@erasche Yes it could be really great to have that!

**Comment by erasche** [comment]
This is out of date now, and we have started asking for maintainers on each CoFest call, as well as checking that people are still happy to be maintainers, so maybe we close this issue now
