### ISSUE TITLE
Integrate a template system

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/training-material#5]
We would like to integrate a small template system into our training material. It should be possible to easily compile a training-course PDF with individual logos or funding agencies.
We could also think about changing reference-genomes and the links to training material via templates.

**Comment by bgruening** [comment]
ping @bebatut 
Let me know if you have any ideas: sphinx, jinja ...

**Comment by frederikcoppens** [comment]
I advocate for a commonly used, maintained templating language. Even if this might not have all the features we might envision (I doubt this will be a problem). I'm not very much into this field, only have used jinja, which would be fine for me

**Comment by bebatut** [comment]
[Pandoc](http://pandoc.org/) is also a good solution. It can convert markdown to PDF using `pdflatex`. So if needed, you can use some latex commands and you can also integrate easily a `.bib`

**Comment by bgruening** [comment]
@bebatut pandoc will be defenetily used with some makefile to generate all slides and PDF's from this repository, but does it also have some templating system?

**Comment by bebatut** [comment]
You can add a [template](http://pandoc.org/README.html#templates). You can add a `.cls` file also

**Comment by bebatut** [comment]
Did you choose the slide format?

**Comment by bgruening** [comment]
@bebatut please have a look here: https://github.com/bgruening/training-material/issues/8
I need to read more about the pandoc templates, it would be nice to be as flexible as possible to maybe later swap out reference genomes.

E.g. `make mm9` will compile all PDFs with the mm9 reference genome.
We really need you and your expertise here :)

**Comment by bebatut** [comment]
Templates for the topic tutorial and slides are explained in the [`CONTRIBUTING.md`](https://github.com/bgruening/training-material/blob/master/CONTRIBUTING.md). The move to these templates was started in the PR

**Comment by bgruening** [comment]
This was about a template engine to compile tutorials and easily exchange the logos, funding agencies or reference genomes.

**Comment by nsoranzo** [comment]
The templating system may be also used to change the datasets, e.g. having the same RNA-Seq tutorial which can be personalised with human, animal and plant data.

**Comment by bebatut** [comment]
Do you think this issue is still of actuality?

**Comment by bgruening** [comment]
I don't think we can/will work on this in the near future, but we can leave it open to collect ideas?

**Comment by willdurand** [comment]
Well it seems to me that you're already using a template, it is called Liquid: https://jekyllrb.com/docs/templates/. The `_config.yml` file and the YAML front-matter can have as many variables as one wants and this should be the way to go if one wants to update data.

**Comment by erasche** [comment]
There is work for something like

>  We could also think about changing reference-genomes ... via templates.

In https://github.com/galaxyproject/training-material/pull/1120

**Comment by erasche** [comment]
The option I explored in #1120 did not work great and would be unpleasant to contribute to tutorials using that. For admin it had a good use case but in the end it wasn't so important.

Since most of the tutorials in the past few years are based on a research story, we don't seem to have encountered this issue very often. We should definitely re-open this if we find that it's a big issue for us.
