### ISSUE TITLE
Feeds bug and extension

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/training-material#5099]
1. The site renders fine for me on Firefox but has not rendered all day for me on Safari
https://training.galaxyproject.org/training-material/feeds/index.html
<img width="935" alt="Screenshot 2024-06-28 at 18 11 25" src="https://github.com/galaxyproject/training-material/assets/44605769/46398605-83a5-497e-8200-2ff44ae60b9b">

2. Can we distinguish types of resource? i.e. can the frames distinguish (events, news, resources)?

**Comment by hexylena** [comment]
huh, I can't test safari. do you have any console errors? maybe safari won't render xml this way.

im not sure what you mean about the second. there are separate news events and resources feeds, as well as a digest which includes items from all three

**Comment by nomadscientist** [comment]
Ahhhhhhhh that second one was user error then, that's perfect

**Comment by nomadscientist** [comment]
Maybe Safari is defunct and that should just be the answer

**Comment by hexylena** [comment]
safari is unfortunately 10% of our user base, we need to find a better solution sadly
