### ISSUE TITLE
Homepage not updated?

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/training-material#518]
The homepage at https://galaxyproject.github.io/training-material/ still contains the link `Contributors list` pointing to https://github.com/galaxyproject/training-material/blob/master/CONTRIBUTORS.md instead of https://github.com/galaxyproject/training-material/blob/master/CONTRIBUTORS.yaml .
Not sure why, serving the site locally has the correct link.

**Comment by willdurand** [comment]
It is missing here actually:

https://github.com/galaxyproject/training-material/blob/7ba06edef09c9e6d3dcd94f0d86c415edfe08593/_layouts/home.html#L98

**Comment by willdurand** [comment]
Question is: why it isn't failing the build 😛

**Comment by willdurand** [comment]
ah no! we both confuse the `CONTRIBUTING` and `CONTRIBUTORS` files it seems...

**Comment by nsoranzo** [comment]
Yeah, sorry, I've now updated the issue description.

**Comment by willdurand** [comment]
This is weird since the `gh-pages` branch has the right code: https://github.com/galaxyproject/training-material/blob/6c02b3556f5d7863f9f17f5a46b9333504936180/index.html#L251. GitHub aggressive caching maybe, we'll see on next deploy.

**Comment by nsoranzo** [comment]
Fixed with latest PR merge.
