### ISSUE TITLE
Suggested update to workflow for differential-isoform-expression

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/training-material#5208]
https://github.com/galaxyproject/training-material/blob/main/topics/transcriptomics/tutorials/differential-isoform-expression/tutorial.md

Hi all -- The workflow in this tutorial doesn't play well with the tutorial data. It requires that the student has a list of the element identifiers for the control samples as a distinct input text list, and that list isn't included in the workflow datasets, plus I think it would be better as a derived filter list, the same as the hands-on.

**What I changed:** Since the workflow already includes simple inputs for the factor level naming, those can be reused in the regular expression filtering of element identifiers (for the collection splitting step) with the addition of just two tools and tiny related changes. All of those mirror the hands-on tools/steps. 

![MODIFIED-FOR-GTN_differential-isoform-expression](https://github.com/user-attachments/assets/f312dc73-7e92-4447-9b06-f8a423e32b0d)

I've created a sample modified version of the workflow with those adjustments.
* Input data https://usegalaxy.eu/u/jenj/h/gtn-differential-isoform-expression
* Workflow output https://usegalaxy.eu/u/jenj/h/genome-wide-alternative-splicing-analysis-human-modified-for-gtn
* Workflow https://usegalaxy.eu/u/jenj/w/genome-wide-alternative-splicing-analysis-human

While this tutorial is labeled as advanced, it assumes quite a bit of knowledge about Galaxy and workflow editing to get it to work. I think we should update it unless there is some other use of it where the proposed changes would conflict (?).

Overall -- we could consider using group tags to filter, instead of the whole "filter list identifiers by the way the fastq files are named". It makes the workflow very specific to the tutorial, and not as reusable. Scientist are more likely to have files without custom naming, or even SRR identifiers. Maybe upload the control + treat collections, give them group tags, merge together for some of the processing, then split for other processing. I can help if we want to do this.

Thoughts? ping @pavanvidem @gallardoalba @lldelisle

**Comment by lldelisle** [comment]
Thanks Jen, I will have a look when I will update the tutorial in 10 days.

**Comment by jennaj** [comment]
Great, thank you, this is **such** an impressive tutorial! Seems to be getting more attention in general Q&A, too, so polishing a bit would be excellent. :)

**Comment by lldelisle** [comment]
Solved in #5282
