### ISSUE TITLE
News widget does not render on Safari

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/training-material#5284]
![image](https://github.com/user-attachments/assets/b6181784-1473-440d-a4b7-2fd9a409f48d)
This does not render on Safari.
Cam Hyde found that:
"Safari does not have built-in support to render RSS feeds directly within iframes, and when an RSS feed is loaded in Safari, it prompts the user to find an app to read the RSS feed instead."

Is there a workaround?

**Comment by hexylena** [comment]
There's been a workaround since you reported this issue to me at GCC and I fixed it. @neoformit  you should use the .w.html links, as per: https://training.galaxyproject.org/training-material/feeds/

> Simply replace .xml with .w.html in the URL and it’ll produce a feed preview that can be embedded in an iframe easily. (.w.xml is also available but does not work for Safari users, ~10% of our traffic.)

**Comment by neoformit** [comment]
Awesome news, thanks @hexylena

**Comment by hexylena** [comment]
just checked it out, looks fantastic! Only comment is those two widgets you're using show the *same* data in different structures (as it is published / monthly round ups with news being up to 31 days old when it's finally visible.) You could probably pick just one of those if you wanted that space back for a different widget? :)

**Comment by neoformit** [comment]
Good point Helena - I'll leave that up to Wendi to decide!
