### ISSUE TITLE
Create a dedicated section within GTN or a special tag

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/training-material#5361]
We will be developing new tutorials and re-using existing ones for BRC-analytics.org project. What would be the best way to make BRC-specific materials visible within GTN:
- learning path
- a new section
- ...

**Comment by hexylena** [comment]
If you're re-using existing materials, and adding new materials to existing topics then I think Learning Pathways would be the best option. You get the topic-page like experience.

We also have 'synthetic topics' e.g. the https://training.galaxyproject.org/training-material/topics/gmod/ which pull tutorials from other topics but this is 1) unstructured, and 2) requires tagging all of those tutorials. For the gmod case this makes sense as that technology is used throughout the original tutorials. For your case it would require re-tagging existing tutorials as 'BRC' just to include them in your topic, which feels sub-optimal.

So, learning paths are my recommendation!
