### ISSUE TITLE
Tool in *Regression in Machine Learning* references a removed option

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/training-material#5431]
In [Create Data Processing Pipeline](https://training.galaxyproject.org/training-material/topics/statistics/tutorials/regression_machinelearning/tutorial.html#create-data-processing-pipeline) you are instructed to run **Pipeline builder (Galaxy version 1.0.11.0)** and select **“Output parameters for searchCV?”:** `Yes`. However, it appears this option was removed prior to 1.0.11.0. Of the versions installed on usegalaxy.org, the newest version with that option is [1.0.8.4](https://usegalaxy.org/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fsklearn_build_pipeline%2Fsklearn_build_pipeline%2F1.0.8.4).

**Comment by scottcain** [comment]
I ran this tutorial using the newer version Pipeline build (1.0.11.0) with this tutorial (so without the output parameters for searchCV option). The following step (Hyperparameter search) worked as expected (ie, 75 estimators was shown to be best)
