### ISSUE TITLE
DEXSeq step error in Ref-based RNA-seq

### ISSUE THREAD

**Issue by mfernandes61** [galaxyproject/training-material#544]
Hi,
I'm getting an error with the procedure towards the end that uses DEXSeq.
It has occurred on my GVL instance and on the usegalaxy public server
It is possible that I have made a mistake when entering factors but I have tried several times and got
the same result (Output below)

Any insights/answers?
Thanks,
Mark

Dataset generation errors

Dataset 9: DEXSeq result file on data 8, data 5, and others

Tool execution generated the following error message:
Fatal error: An undefined error occured, please check your input carefully and contact your administrator.
Loading required package: BiocParallel
Loading required package: methods
Loading required package: Biobase
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, cbind, colnames, do.call,
    duplicated, eval, evalq, Filter, Find, get, grep, grepl, intersect,
    is.unsorted, lapply, lengths, Map, mapply, match, mget, order,
    paste, pmax, pmax.int, pmin, pmin.int, Position, rank, rbind,
    Reduce, rownames, sapply, setdiff, sort, table, tapply, union,
    unique, unsplit, which, which.max, which.min

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: SummarizedExperiment
Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: S4Vectors

Attaching package: ‘S4Vectors’

The following objects are masked from ‘package:base’:

    colMeans, colSums, expand.grid, rowMeans, rowSums

Loading required package: IRanges
Loading required package: GenomeInfoDb

Attaching package: ‘SummarizedExperiment’

The following objects are masked from ‘package:IRanges’:

    acbind, arbind

Loading required package: DESeq2
Loading required package: AnnotationDbi
Loading required package: RColorBrewer
Warning messages:
1: multiple methods tables found for ‘arbind’ 
2: multiple methods tables found for ‘acbind’ 
3: replacing previous import ‘IRanges::arbind’ by ‘SummarizedExperiment::arbind’ when loading ‘DESeq2’ 
4: replacing previous import ‘IRanges::acbind’ by ‘SummarizedExperiment::acbind’ when loading ‘DESeq2’ 
5: replacing previous import ‘IRanges::arbind’ by ‘SummarizedExperiment::arbind’ when loading ‘DEXSeq’ 
6: replacing previous import ‘IRanges::acbind’ by ‘SummarizedExperiment::acbind’ when loading ‘DEXSeq’ 
Error in DEXSeqDataSetFromHTSeq(countFiles, sampleData = sampleTable,  : 
  Count files do not correspond to the flattened annotation file
The tool produced the following additional output:
[1] "en_US.UTF-8"
                  condition Sequencing
dataset_338.dat   2_treated       1_SE
dataset_339.dat   2_treated       2_PE
dataset_340.dat   2_treated       2_PE
dataset_335.dat 1_untreated       1_SE
dataset_336.dat 1_untreated       2_PE
dataset_337.dat 1_untreated       2_PE
dataset_341.dat 1_untreated       1_SE
~sample + exon + Sequencing:exon + condition:exon
~sample + exon + Sequencing:exon
[1] "condition"
[1] "/mnt/galaxy/files/000/dataset_338.dat"
[2] "/mnt/galaxy/files/000/dataset_339.dat"
[3] "/mnt/galaxy/files/000/dataset_340.dat"
[4] "/mnt/galaxy/files/000/dataset_335.dat"
[5] "/mnt/galaxy/files/000/dataset_336.dat"
[6] "/mnt/galaxy/files/000/dataset_337.dat"
[7] "/mnt/galaxy/files/000/dataset_341.dat"
[1] "./html_out"
[1] 2
[1] "/mnt/galaxy/tmp/job_working_directory/000/287/working"

**Comment by bgruening** [comment]
@mfernandes61 I think the error message is this here: `Count files do not correspond to the flattened annotation file`. Which indicates that your GTF file does not correspond to the cout files.

**Comment by mfernandes61** [comment]
@bgruening Thanks Bjorn - have double-checked and still get error using the Zenodo dexseq.gtf file :-(
Would like to get past this as we've been using these materials on small groups of learners and has been going quite well so far (Introduction, QC, Mapping Ref-RNAseq materials)

**Comment by bgruening** [comment]
@mfernandes61 ah! Wait, are you using the pure GTF files from Zenodo? Have you done the `Use the DEXSeq-Count to prepare the Drosophila annotations` step before?

**Comment by mfernandes61** [comment]
Was following the text (So a new history plus the files from Zenodo):
dexseq.gtf: the results of running DEXSeq-count in ‘Prepare annotation’ mode
Seven count files generated in ‘Count reads’ mode
 Hands-on:
Create a new history
Import the seven count files and the dexseq.gtf from Zenodo
dexseq.gtf
GSM461176_untreat_single.dexseq.counts
GSM461177_untreat_paired.dexseq.counts
GSM461178_untreat_paired.dexseq.counts
GSM461179_treat_single.dexseq.counts
GSM461180_treat_paired.dexseq.counts
GSM461181_treat_paired.dexseq.counts
GSM461182_untreat_single.dexseq.counts
DEXSeq : Run DEXSeq with
“Condition” as first factor with “treated” and “untreated” as levels and selection of count files corresponding to both levels
“Sequencing” as second factor with “PE” and “SE” as levels and selection of count files corresponding to both levels

**Comment by polkhe** [comment]
Hi,

I was getting the same error while using the precomputed dexseq.gtf.
But it worked when I switched to .gtf created during previous steps

**Comment by erasche** [comment]
@bebatut plans to extract a short tutorial with the DEXSeq parts at some point.

**Comment by hexylena** [comment]
Closing due to age, can re-open as needed :)
