### ISSUE TITLE
re-integrate the `Tutorials using public Galaxy at usegalaxy.org` tutorials

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/training-material#545]
@nekrut can we re-integrate the `Tutorials using public Galaxy at usegalaxy.org` into other sections. The `annotation` which training can be run with which Galaxy instance should happen as Metadata.

**Comment by bebatut** [comment]
@nekrut what do you think about re-integrating the tutorials of usegalaxy in other sections?

**Comment by bgruening** [comment]
In will work on this today.

**Comment by bebatut** [comment]
Thanks to @bgruening. It was done in #608
