### ISSUE TITLE
Link problem in Analyses of metagenomics data - The global picture

### ISSUE THREAD

**Issue by mfernandes61** [galaxyproject/training-material#547]
On section on initial import of data (Pampa soil: SRR531818
Anguil soil: SRR651839) the link to Zenodo for data links back to tutorial (https://galaxyproject.github.io/training-material/topics/metagenomics/tutorials/general-tutorial/tutorial.html) rather than to the intended (I presume) https://zenodo.org/record/815875#.WcjZorL5hpg

Hope that this is helpful,
Mark

**Comment by shiltemann** [comment]
thanks for reporting this @mfernandes61! :)
