### ISSUE TITLE
update tutorials using HISAT2 to new version

### ISSUE THREAD

**Issue by mblue9** [galaxyproject/training-material#552]
Creating this issue to flag that, as HISAT2 has been updated, the current screenshots and text in some GTN tutorials no longer match the newest version of the tool, so will need to be updated at some stage e.g. these tuts

- https://galaxyproject.github.io/training-material/topics/transcriptomics/tutorials/ref-based/tutorial.html
- https://galaxyproject.github.io/training-material/topics/transcriptomics/tutorials/de-novo/tutorial.html
- https://galaxyproject.github.io/training-material/topics/transcriptomics/tutorials/srna/tutorial.html

Happy to help update if you like when I get a chance.

**Comment by bgruening** [comment]
I guess this is a good example why we should avoid including screenshots of tools. Any opinions about this?
Thanks @mblue9 for tracking the issue.

**Comment by bernt-matthias** [comment]
I just stumbled over the same issue. Removing the screenshots would not be sufficient, since also parameter names or the available parameters change. I would suggest to keep the screenshots, but to include the version of the used tools in the tolls.yml file (and maybe in the tutorial text?).

**Comment by bgruening** [comment]
The revision will be included as soon as we auto generate the tools.yml file from the workflow files. But I still think the parameter names are way more stable then images.

**Comment by mblue9** [comment]
It's easier for maintainability to remove the images but I think it's easier for users if there are images in the tutorials (I've had a user asking if the material could have _more_ screenshots). I have no idea if this is possible but the ideal solution imho would be if the tutorials could be automatically run (Selenium-style?) to test that they work and auto-generate the screenshots.

**Comment by bernt-matthias** [comment]
on the other hand there are the tours

**Comment by bebatut** [comment]
I have the feeling that if the parameters are clearly described (full name of the parameters, clear value, parameters in the same order as they appear in the Galaxy interface) the screenshot are not really needed (some time bad quality and more difficult to update):

![screen shot 2017-09-28 at 09 50 34](https://user-images.githubusercontent.com/1842467/30955024-865881ee-a432-11e7-9db7-1f306358eb60.png)

At least, we can also add comment about the parameters directly and it is easier to update and less issue also with the name of the input 😄 
We could think about a good way to describe the parameters (other issue?) that we try to have in all the tutorials, except the first steps in the introductions (where I can understand screenshots are better to familiarize yourself with the interface)

**Comment by shiltemann** [comment]
some parameter settings are described *only* in the screenshots, which is not good for accessibility either. There should always be a text description as well imho. Problem with screenshots is they need to be updated not only when the tool changes, but also when the UI changes, which makes it harder to track when a tutorial needs updating. Except for things like the 101 where we explicitly explain the UI I would be in favour of discouraging screenshots as well. If the textual descriptions are confusing to users we should think about how to improve/unify them.

**Comment by mblue9** [comment]
oh yes I totally forgot about the tours!! ☺️ If there are the tours and the parameters are clearly described in the text then screenshots would be less important I think. Do you think tagging the tool parameters in the text would help - make easier to update and to check what needs updating/has already been updated? Something like what Anna suggested previously here https://github.com/galaxyproject/training-material/issues/214

**Comment by bgruening** [comment]
> Do you think tagging the tool parameters in the text would help

Yes! :)

We should add it to the guidelines then, that we discourage to add many screenshots. Make it something like a soft-rule. What does @nekrut thinks about it?

**Comment by bgruening** [comment]
@mblue9 what about Star. Should we remove all figures and include Star as mapper?

**Comment by mblue9** [comment]
@bgruening I have never tried Star (the large memory requirement put me off) but I've heard it's good. Happy to use it if you and others think it'd be better here.
