### ISSUE TITLE
Plugin IO does not work in Telegraf

### ISSUE THREAD

**Issue by Nota30** [galaxyproject/training-material#5601]
The `io` plugin does not work in telegraf. I assume it's been renamed to `diskio`.
I ran this following the tutorial however it threw an error and I renamed it to diskio and it worked.

Link: https://training.galaxyproject.org/training-material/topics/admin/tutorials/monitoring/tutorial.html#hands-on-dependencies
---- 
![ansible](https://github.com/user-attachments/assets/0c63c27c-d58a-41db-8e34-fefdfa3cb375)

**Comment by hexylena** [comment]
Ahh you're right, thank you for catching this! I guess they renamed it a while back.

**Comment by Nota30** [comment]
I could make a PR for this
