### ISSUE TITLE
Use GitHub Pages + Travis for testing your own fork

### ISSUE THREAD

**Issue by blankclemens** [galaxyproject/training-material#567]
Right now I can think of two ways of testing own contributions: Using Jekyll locally or setting up the GitHub Pages and Travis for your own fork.

I highly prefer the second method and am wondering if there are reasons to not promote this more, e.g. I imagine providing the information for a proper setup in the how-to-contribute tutorials could be quite beneficial.

I'm doing this quick and dirty by myself (leaving questions like the proper link addresses open), so I'd like to see a how-to from someone with clear understanding of the underlying structure, who could consider possible issues with this approach (e.g. I heard of  conflicts with google indexing).

**Comment by bgruening** [comment]
One reason against the second method is that google will index this page as well and it confused people that are searching for tutorials. We already had someone that were confused by Wills fork.

**Comment by nsoranzo** [comment]
Agree with @bgruening.

**Comment by bebatut** [comment]
I think this issue is now solved with #634: check #636

**Comment by bgruening** [comment]
Yeah!
