### ISSUE TITLE
[meta] What branch protections to set up for this repository

### ISSUE THREAD

**Issue by martenson** [galaxyproject/training-material#569]
We have these options for every branch of this repo. 
![screenshot 2017-10-11 11 13 58](https://user-images.githubusercontent.com/1814954/31449887-12d9a3ee-ae76-11e7-93d1-b59db8ff2de7.png)

However status checks will always fail for new pages, since they check urls that have not been created yet. Might be remedied by https://github.com/galaxyproject/training-material/pull/557 in the future.

Also master will stay as 'protected' which means nobody can force push - i.e. only non-destructive changes can occur and admins can always easily revert them.

**Comment by bebatut** [comment]
I would like to check the first two options: it will force PR to submit sth to master and that every PR is reviewed. @shiltemann @bgruening What do you think?

**Comment by bgruening** [comment]
I'm fine with the second option for sure.

**Comment by shiltemann** [comment]
I agree @bebatut

**Comment by martenson** [comment]
@bebatut @bgruening @shiltemann that submenu has a submenu so make your picks there also

(and if you chose to "Restrict who can dismiss pull request reviews" I need a list of users to put there:)
![screenshot 2017-12-01 09 55 52](https://user-images.githubusercontent.com/1814954/33488197-e6d1daa2-d67d-11e7-932e-d9eb52523114.png)

**Comment by bebatut** [comment]
The first one maybe. @shiltemann @bgruening ?

**Comment by shiltemann** [comment]
yeah sounds good to me

**Comment by martenson** [comment]
you got it

**Comment by martenson** [comment]
![screenshot 2017-12-01 11 31 20](https://user-images.githubusercontent.com/1814954/33492486-2bdbf42c-d68b-11e7-9210-73ac5b936651.png)

**Comment by bebatut** [comment]
Thanks @martenson
