### ISSUE TITLE
RNASeq: de novo transcriptome assembly with Trinity

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/training-material#59]
For the #58 hackathon, I propose to work on some training material for de novo transcriptome assembly with Trinity.
The Trinity wrappers are up to date in IUC, and I have a (not yet public) workflow using them to do assembly+abundance estimation+differential expression.
Any help is welcome of course!

**Comment by r1corre** [comment]
I would be pleased to join this initiative !!

**Comment by abretaud** [comment]
Hum I'd like to assign this issue to myself, but it seems like I don't have permissions to do so, maybe one of you can do it for me?

**Comment by bgruening** [comment]
@abretaud added you.

**Comment by abretaud** [comment]
Great, thanks!

**Comment by bebatut** [comment]
@abretaud do you still plan to develop such tutorial?

**Comment by bebatut** [comment]
@abretaud do you still plan to develop such tutorial?

**Comment by abretaud** [comment]
oh, hadn't noticed you pinged me

**Comment by abretaud** [comment]
I still have this tutorial somewhere in my todo list, but I'd like first to finish the Maker one
So... no idea when I'll find time to make it. Feel free to close for now if you prefer, I'll reopen/make a pr when things will get real

**Comment by erasche** [comment]
Super cool that you started this!
