### ISSUE TITLE
Headlines rendering iOS

### ISSUE THREAD

**Issue by joachimwolff** [galaxyproject/training-material#595]
On iOS the headlines are rendered too small. See attached image.
![76e739d2-26f9-4ad3-aded-0bfc95280726](https://user-images.githubusercontent.com/13435136/32730028-0c66d0e8-c886-11e7-99bc-8712cd3bc2b4.jpeg)

**Comment by bebatut** [comment]
@willdurand do you know how we could fix that?

**Comment by willdurand** [comment]
@joachimwolff could you still reproduce it? if so, on which page and which device?

**Comment by willdurand** [comment]
Cannot reproduce locally on the simulator 😢 

FWIW: it is the "Genome Annotation" hands-on on iPad Pro 10.5" (not up-to-date). This is weird since I am unable to reproduce on any browsers so far, keep investigating though.
