### ISSUE TITLE
Paper about the Galaxy Training Material

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#596]
Hi all,

We are writing a paper about the Galaxy Training material initiative and its infrastructure. You can find the draft here: https://docs.google.com/document/d/1m3yp7yq-Nr7nIBOql5EWriMkcYzlcQABhHyrWoR0W9U/edit?usp=sharing
If you feel you should be an author of this paper, you can add yourself between Saskia and Galaxy Training Network (while following the alphabetical order). Otherwise, we assume you are part of Galaxy Training Network.
We will close this issue in one week and submit the paper.

Saskia and Bérénice

ping @abretaud @aisanjiangw @annasyme @bagnacan @bernt-matthias @dannon @delphine-l @dpryan79 @dyusuf @erasche @fidelram @fmareuil @friedue @guerler @hmenager @hrhotz @jennydg @jfallmann @jgoecks @jj-umn @jmchilton @joachimwolff @lecorguille @loraine-gueguen @malloryfreeberg @manabuishii @martenson @moheydarian @mwolfien  @odoppelt @kilpert @pajanne @polkhe @pvanheus @pratikdjagtap @slegras @slugger70 @stortebecker @tealiie @thomasmanke @torhou @valentinmarcon @vdda @vivekbhr @willdurand @wm75 @yhoogstrate @yvanlebras

**Comment by bebatut** [comment]
ping @valentinmarcon @vdda @vivekbhr @willdurand @wm75 @yhoogstrate @yvanlebras

**Comment by fidelram** [comment]
Any guidelines on what sort of contribution you consider is required to participate on the paper?

**Comment by AisanjiangW** [comment]
Hello,
I have been contributing to tutorials by revising or reporting mistakes to
revise them when I found any mistakes in a tutorials.


Thank You,
Aisanjiang Wubuli
*_______________________*
MSc, Molecular Diagnostics and Biotechnology
University of Camerino, Italy
B.Sc, Biological Technology
Shandong University, P. R. China
Email: *uyturk2010@gmail.com <Uyturk2010@gmail.com>*
Skype: uyturk2010

**Comment by bebatut** [comment]
Any kind of contributions: work on the infrastructure, development or improvement of content, etc.
The question is more if you identify yourself with this project and this paper :smile:

**Comment by vivekbhr** [comment]
Although I did contribute to the training material, It's difficult for me to assess whether the contribution warrants authorship. I'd rather leave this decision to the lead authors.

**Comment by bebatut** [comment]
It is been a week: I am closing this issue. We will submit the article to bioarxiv today

**Comment by bebatut** [comment]
Hi all,

To give you some updates, the paper has been accepted by Cell Systems :tada:
Hopefully it will be online soon. In the mean time, it is still on BioRXiv: https://www.biorxiv.org/content/early/2018/04/05/225680

**Comment by thomasmanke** [comment]
Congratulations everyone - a nice reward for great efforts!

**Comment by bebatut** [comment]
Hi all,

The paper is online since this morning: https://www.cell.com/cell-systems/fulltext/S2405-4712(18)30230-8

Thanks to all of you for this effort!

**Comment by nsoranzo** [comment]
Hooray! Thanks @bebatut and all!
No open access though?

**Comment by bgruening** [comment]
> No open access though?

It should, that is a mistake, the editor is contacted.

**Comment by martenson** [comment]
the DOI does not seem to work yet: https://doi.org/10.1016/j.cels.2018.05.012

**Comment by bgruening** [comment]
@martenson try this one: https://doi.org/10.1016/j.cell.2018.05.012

**Comment by bgruening** [comment]
This is a shareable link with open-access: https://authors.elsevier.com/a/1XI288YyDfU-ra

**Comment by martenson** [comment]
@bgruening yours works, but the broken one I shared is listed on the cell page 
<img width="282" alt="screenshot 2018-06-27 13 47 40" src="https://user-images.githubusercontent.com/1814954/41998881-b249c66e-7a10-11e8-8855-a45016fa2c53.png">

**Comment by nsoranzo** [comment]
Actually the one @bgruening shared redirects to another paper.

**Comment by nsoranzo** [comment]
@martenson The original DOI works now.
