### ISSUE TITLE
best location for a mapping-by-sequencing tutorial

### ISSUE THREAD

**Issue by wm75** [galaxyproject/training-material#599]
Hi,
I just started work on some new training material covering mapping-by-sequencing type of analyses with our MiModD tool suite as a replacement for the old CloudMap tools on Galaxy main and I would like to have opinions where to put this.

MiModD, like the old CloudMap, is for identifying causative mutations behind phenotypes of interest in model organisms. It is for people who have isolated phenotypic mutants and have crossed these mutants to a mapping strain containing lots of marker SNPs. MiModD reidentifies these markers in WGS data from recombinant progeny, performs linkage analyses that show which markers are associated or not with the original phenotype and identifies candidate mutations in the corresponding genomic regions.
With that I think it would fit in the "Variant Analysis" topic quite well. OTOH, the tutorial will be specifically about using the tool on Galaxy main (we already have quite an extensive general tutorial section in the MiModD documentation at http://mimodd.readthedocs.io, which we do not want to duplicate) so you could argue that it also fits in the "Tutorials using public Galaxy at usegalaxy.org" section.

Thanks for your feedback,
Wolfgang

**Comment by bgruening** [comment]
Hi @wm75! Nice to see you here! "Tutorials using public Galaxy at usegalaxy.org" will go away, probably this month and we will group the tutorials into other sections. Tutorials should not depend on a specific Galaxy instance to I would encourage you to use "Variant Analysis".

**Comment by shiltemann** [comment]
Hi @wm75 that sounds like a great tutorial! we are trying to move tutorials out of this `usegalaxy.org` topic, and instead just annotate all trainings with a list of public instances supporting, so please use `variant analysis` topic, this sounds like a good fit :)

**Comment by wm75** [comment]
Thanks for your feedback about where to put the tutorial. I'm about half-way done with it by now. Most importantly, I've created training datasets to work with.
I've read that preferably you would make these available via zenodo links, but I've no experience with zenodo at all. Is material there organized in categories/topics/anything and, if so, is there a recommended place to put training material, or do I just upload the data, get a link and that's it?

**Comment by shiltemann** [comment]
Hi @wm75 awesome! :) Yes,it's basically just upload and get a link. :) Zenodo has communities, and there is one for the [Galaxy training network](https://zenodo.org/communities/galaxy-training/?page=1&size=20). When you upload your data they will ask you if you want to add it to any communities.

**Comment by bebatut** [comment]
This tutorial has been added so I will close this issue
