### ISSUE TITLE
pdf files for tutorials should show hidden content

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/training-material#600]
It would be really nice if the pdf files for tutorials would show the answers to the questions which are currently hidden.

**Comment by bebatut** [comment]
@willdurand any idea how to do that?

**Comment by willdurand** [comment]
What is used for pdf generation? Maybe a simple "print" CSS style would be enough.

**Comment by bebatut** [comment]
We are using headless CHROME
