### ISSUE TITLE
consensusXML is not correctly detected

### ISSUE THREAD

**Issue by Stortebecker** [galaxyproject/training-material#603]
@blankclemens The output of OpenMS IDMapper is not correctly assigned to `consensusXML`, but to `idXML`. I think this happened with some other tool as well, but I cannot find it now. Auto-detection of `consensusXML` files does not work, either.

**Comment by blankclemens** [comment]
But in general it works, just the filetype detection is wrong?

Thanks for detecting, but I guess it would fit better there: https://github.com/galaxyproteomics/tools-galaxyp ;)

**Comment by Stortebecker** [comment]
Issues are not enabled in https://github.com/galaxyproteomics/tools-galaxyp

And yes, the file is correct, only the filetype detection does not work.

**Comment by blankclemens** [comment]
Wait what? You already createt issues there? https://github.com/galaxyproteomics/tools-galaxyp/issues/209 (:

Regarding that in general it works, I'd suggest waiting for 2.3 to see what needs to be done.

**Comment by Stortebecker** [comment]
> Wait, what? You already createt issues there: galaxyproteomics/tools-galaxyp#209 (:

It's late...

> Regarding that in general it works, I'd suggest waiting for 2.3 to see what needs to be done.

ok

**Comment by erasche** [comment]
Seems like the issue was moved to the right place
