### ISSUE TITLE
follow up on https://github.com/galaxyproject/training-material/pull/623

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/training-material#624]
https://github.com/galaxyproject/training-material/pull/623

Better formatting, probably with its own tag and css?

**Comment by bebatut** [comment]
The quoting of URL as in #623 is breaking the boxes:

![screen shot 2017-12-03 at 11 50 21](https://user-images.githubusercontent.com/1842467/33524610-61e206a6-d820-11e7-9250-36240a0ad56f.png)

**Comment by bebatut** [comment]
@bgruening do you think it needs its own tag and css? or the current way is ok?

**Comment by erasche** [comment]
I think this is solved
