### ISSUE TITLE
Need maintainers for each topic

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#63]
Hi,

We need one or two maintainers for each topic. 

A maintainer acts as editors. She is responsible for making sure issues and change requests are looked at. She has the final say over what is included in the training material related to the topic. But, she is not responsible for writing training material content or deciding what lessons ought to exist, both coming from the community.

Are you interested? Do not be shy, everyone can do that :)
Please, answer this issue with your name, your email and the topic(s) you want to maintain

I will keep a track of all propositions (even if there is more than 2 persons for a topic):
- Admin-corner
  - Hans-Rudolf: hrh@fmi.ch, hrhotz@gmail.com
- NGS-QC
  - Markus Wolfien: markus.wolfien@gmail.com
- NGS-mapping
- ChIP-Seq
  - Friederike Dündar: frd2007@med.cornell.edu
- Dev-Corner
  - Gildas Le Corguillé
- Exome-Seq
- Genome-Annotation
- Galaxy Introduction
- MethylC-Seq
- RNA-Seq
  - Friederike Dündar: frd2007@med.cornell.edu

Thanks a lot,

Bérénice

**Comment by hrhotz** [comment]
I am happy to look after the 'Admin-corner'
Hans-Rudolf
(hrh@fmi.ch, hrhotz@gmail.com)

**Comment by bebatut** [comment]
Thanks :)
I added you

**Comment by friedue** [comment]
I can do ChIP-seq (and RNA-seq if needed)

**Comment by mwolfien** [comment]
For me it would be a pleasure to maintain the NGS-QC section =)
Markus Wolfien
(markus.wolfien@gmail.com)

**Comment by bgruening** [comment]
Thanks Markus! I added you! I guess we will the maintainers tm to the readme file of each training.

**Comment by yvanlebras** [comment]
Hi everyone, what about adding a RAD-seq section topic ? If you think this is of interest, I can be a maintainer.

**Comment by lecorguille** [comment]
I will do stuff around the dev-corner

**Comment by bebatut** [comment]
Hi Yvan. Feel free to add it this topic. I add you as possible maintainer.

**Comment by bebatut** [comment]
@lecorguille I added you as possible maintainer

**Comment by abretaud** [comment]
I will start working on bgruening/training-material/issues/59 = RNASeq assembly

**Comment by jibe-b** [comment]
I started filling the AdminCorner/Database_schema slide with content from the tutorial.

**Comment by bebatut** [comment]
The conversation was restarted in #489
