### ISSUE TITLE
reflect the new on-the-fly PR deployment in docs/training

### ISSUE THREAD

**Issue by martenson** [galaxyproject/training-material#636]
Can be seen in action in https://github.com/galaxyproject/training-material/pull/635

Many thanks to @willdurand for making this happen!

**Comment by bebatut** [comment]
Can I close this issue?

**Comment by martenson** [comment]
@bebatut I think the feature is still not documented (which is what this issue is for), but feel free to close if you think it is not needed.

**Comment by bebatut** [comment]
Documentation is a good point! I will it open then and hopefully someone will document it 😄

**Comment by hexylena** [comment]
We are not using this due to heroku restrictions on who can do the deployment, so I will close it until we find a solution that works.
