### ISSUE TITLE
Fill the introduction slide deck about Administration of Galaxy Servers

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#64]
Hi, 

The [introduction slide decks about Administration of Galaxy Servers](https://github.com/bgruening/training-material/blob/master/Admin-Corner/slides/index.html) needs to be filled.

Thanks

Bérénice

**Comment by oinizan** [comment]
Maybe I could work on this ...
Olivier

**Comment by bgruening** [comment]
@oinizan sounds good! :)

**Comment by ValentinMarcon** [comment]
I join this issue too

**Comment by bebatut** [comment]
There is now introduction slides for admin: http://galaxyproject.github.io/training-material/topics/admin/slides/
I close this issue

**Comment by hrhotz** [comment]
Thank You!
