### ISSUE TITLE
Fill the hands-on tutorial and the slides on "Moving from MySQL to PostgreSQL"

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#65]
Hi, 

For "Moving from MySQL to PostgreSQL", the [tutorial](https://github.com/bgruening/training-material/blob/master/Admin-Corner/tutorials/mysql_to_postgresql.md) and the [associated slides](https://github.com/bgruening/training-material/blob/master/Admin-Corner/slides/mysql_to_postgresql.html) need to be filled with content and hand-on.

It can be nice to take inspiration from:
- ["Moving from MySQL to PostgreSQL"](https://docs.google.com/presentation/d/1N3BDNQT3s7eQEO3BO89TQbTYwKp92fxHDRWQwC-T1kA/edit#sli)
- ["Moving from MySQL to PostgreSQL"](https://wiki.galaxyproject.org/Community/Log/2015/MySQL2PostgreSQL)

Thanks,

Bérénice

**Comment by bebatut** [comment]
I do not see anymore a tutorial for that. Can I merge this issue? @bgruening @martenson

**Comment by hrhotz** [comment]
There was never a tutorial planed for this (or at least I never had the intention to do so). The slides are just linked from the database tutorial as extra (or background) information.
