### ISSUE TITLE
implement google analytics?

### ISSUE THREAD

**Issue by martenson** [galaxyproject/training-material#656]
Galaxy uses google analytics to gather stats and insights from some of the websites. Is the training community interested in these stats for training-materials?

**Comment by bebatut** [comment]
What are the statistics? What should we do to get them?

**Comment by martenson** [comment]
@bebatut the stats are currently not being gathered for training pages. We would need to add a tracking code to the site to enable it.

The stats cover many things like user numbers, sessions, browsing flow, country/city of visitors, site loading speeds etc.

**Comment by bebatut** [comment]
@martenson any idea how to do that?

**Comment by martenson** [comment]
@bebatut The short and fast way is to just include the javascript tracking code for google analytics on every page. The long and slow way is to use something self-hosted like https://matomo.org/ (used to be piwik).
