### ISSUE TITLE
Data on Zenodo

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#672]
Some tutorials does not have a link to data on Zenodo in the `metadata` file:
- Introduction: 
   - [x] Galaxy 101
   - [x] Introduction to Genomics and Galaxy
   - [x] Extracting Workflows from Histories"
   - [x] Multisample Analysis
   - [x] Options for using Galaxy
   - [ ] IGV Introduction
   - [ ] Visualization
   - [ ] Getting data into Galaxy
   - [ ] Collections
   - [ ] Understanding Galaxy history system
   - [ ] Using dataset collection
   - [ ] NGS data logistics
- Proteomics
   - [ ] Protein FASTA Database Handling
   - [ ] Label-free versus Labelled - How to Choose Your Quantitation Method
   - [ ] Detection and quantitation of N-termini (degradomics) via N-TAILS
   - [x] Peptide and Protein Quantification via Stable Isotope Labelling (SIL)
- Sequence analysis
   - [x] Quality Control
   - [x] Mapping
   - [x] RAD-Seq Reference-based data analysis
   - [x] RAD-Seq de-novo data analysis
   - [x] RAD-Seq to construct genetic maps
- Genome annotation
   - [x] Genome Annotation
   - [x] Genome Annotation with Prokka
- Transcriptomics
   - [ ] Reference-based RNAseq data analysis (long)
- Variant analysis
   - [ ] Variant calling: Diploid case
   - [x] Calling variants in non-diploid systems
   - [ ] Calling variants in diploid systems
   - [ ] Calling very rare variants
 
  We should probably put them there

**Comment by bgruening** [comment]
@nekrut @jennaj do you have someone that can do this. Its a little bit about giving credits as you can put authors next to the data.

**Comment by andrewjpage** [comment]
Zenodo links added for:

Sequence analysis
 Quality Control
  Mapping
  Genome Annotation
  RAD-Seq Reference-based data analysis
  RAD-Seq de-novo data analysis
  RAD-Seq to construct genetic maps
  Genome annotation with Prokka

Variant analysis
 Calling variants in non-diploid systems

**Comment by bgruening** [comment]
> * Protein FASTA Database Handling
> * Label-free versus Labelled - How to Choose Your Quantitation Method
> * Detection and quantitation of N-termini (degradomics) via N-TAILS

Do not need a zenodo link afaik.

**Comment by bebatut** [comment]
All the enabled tutorials needing input data have the datasets on Zenodo.
If not, feel free to reopen this issue
