### ISSUE TITLE
Remove direct link to data library

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#674]
In some tutorials, there is links or path to data on the data library (mainly on Main). But as the tutorials can be run on other instances, we should remove them.

Tutorials with links to data library:
- Introduction
  - [x] [galaxy-intro-collections](https://github.com/galaxyproject/training-material/blob/master/topics/introduction/tutorials/galaxy-intro-collections/tutorial.md)
- Variant analysis
  - [x] [ diploid-variant-calling](https://github.com/galaxyproject/training-material/blob/master/topics/variant-analysis/tutorials/diploid-variant-calling/tutorial.md)
  - [x] [non-dip](https://github.com/galaxyproject/training-material/blob/master/topics/variant-analysis/tutorials/non-dip/tutorial.md)

**Comment by erasche** [comment]
This is now fixed it looks like

**Comment by erasche** [comment]
Never mind :(

**Comment by gallardoalba** [comment]
I think that it can be closed too @hexylena @bebatut, as the links to the data library in the collection training were removed here https://github.com/galaxyproject/training-material/pull/2722

**Comment by hexylena** [comment]
Awesome, thanks for checking this @gallardoalba !

**Comment by wm75** [comment]
FYI, there's also #2728 which allows for providing a likely location of DL data, while mentioning that that path might not exist.

Improvements welcome.
