### ISSUE TITLE
Remove screenshots of the tool parameters

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#675]
There is some tutorials in which the parameters for the tools are shown with screenshots.
For accessibility reason and also to simplify the updates (usually coming with new versions of the tools), we would like to replace them by a text description of the parameters, something like:

![screen shot 2018-01-29 at 17 21 24](https://user-images.githubusercontent.com/1842467/35521007-e9e82736-0518-11e8-88cf-ce2d4ecabe0d.png)

Tutorials for which there is screenshots of tool parameters:
- Chip-seq
   - [x] [tal1-binding-site-identification](http://galaxyproject.github.io/training-material/topics/chip-seq/tutorials/tal1-binding-site-identification/tutorial.html) (1 screenshot left)
- Transcriptomics
   - [x] [de-novo](http://galaxyproject.github.io/training-material/topics/transcriptomics/tutorials/de-novo/tutorial.html)
   - [x] [srna](http://galaxyproject.github.io/training-material/topics/transcriptomics/tutorials/srna/tutorial.html)
   - [x] [rna-seq-viz-with-cummerbund](http://galaxyproject.github.io/training-material/topics/transcriptomics/tutorials/rna-seq-viz-with-cummerbund/tutorial.html)
   - [x] [rb-rnaseq](http://galaxyproject.github.io/training-material/topics/transcriptomics/tutorials/rb-rnaseq/tutorial.html)
- Variant-analysis
   - [x] [non-dip](http://galaxyproject.github.io/training-material/topics/variant-analysis/tutorials/non-dip/tutorial.html)
   - [x] [dip](http://galaxyproject.github.io/training-material/topics/variant-analysis/tutorials/dip/tutorial.html)
   - [x] [dunovo](http://galaxyproject.github.io/training-material/topics/variant-analysis/tutorials/dunovo/tutorial.html)

**Comment by nsoranzo** [comment]
I'd like to clarify that this does not apply to the tutorials in the `introduction` topic, where we want to show first-time users what their screen should look like.

**Comment by bebatut** [comment]
Sure!

**Comment by bebatut** [comment]
As discussed during the Contribution fest in Norwich, here are 3 possible ways we could standardize the description of tool parameters:

1. "Current" description
   
   ![screen shot 2018-05-22 at 13 02 41](https://user-images.githubusercontent.com/1842467/40358865-07f46126-5dc1-11e8-9328-27e09d8b0d3f.png)

   ```
   > 2. **RNA STAR** {% icon tool %}: Run **RNA STAR** with
   >    - "Single-end or paired-end reads" to `Paired-end (as individual datasets)`
   >    - "RNA-Seq FASTQ/FASTA file, forward reads" to the generated `trimmed reads pair 1` files (multiple datasets)
   >    - "RNA-Seq FASTQ/FASTA file, reverse reads" to the generated `trimmed reads pair 2` files (multiple datasets)
   >    - "Custom or built-in reference genome" to `Use a built-in index`
   >    - "Reference genome with or without an annotation" to `use genome reference without builtin gene-model`
   >    - "Select reference genome" to `Drosophila Melanogaster (dm6)`
   >    - "Gene model (gff3,gtf) file for splice junctions" to the imported `Drosophila_melanogaster.BDGP6.87.gtf`
   >    - "Length of the genomic sequence around annotated junctions" to `36`
   ```

2. Replacing "to" by ":"
  
   ![screen shot 2018-05-22 at 13 15 29](https://user-images.githubusercontent.com/1842467/40359245-4c1f71aa-5dc2-11e8-8a4d-e89b7133f646.png)

   ```
   > 2. **RNA STAR** {% icon tool %}: Run **RNA STAR** with
   >    - "Single-end or paired-end reads": `Paired-end (as individual datasets)`
   >    - "RNA-Seq FASTQ/FASTA file, forward reads": the generated `trimmed reads pair 1` files (multiple datasets)
   >    - "RNA-Seq FASTQ/FASTA file, reverse reads": the generated `trimmed reads pair 2` files (multiple datasets)
   >    - "Custom or built-in reference genome": `Use a built-in index`
   >    - "Reference genome with or without an annotation": `use genome reference without builtin gene-model`
   >    - "Select reference genome": `Drosophila Melanogaster (dm6)`
   >    - "Gene model (gff3,gtf) file for splice junctions": the imported `Drosophila_melanogaster.BDGP6.87.gtf`
   >    - "Length of the genomic sequence around annotated junctions": `36`
   ```

2. With parameter name in italic and with ":"

   ![screen shot 2018-05-22 at 13 02 47](https://user-images.githubusercontent.com/1842467/40358927-42a033a4-5dc1-11e8-8999-ea4246238695.png)

   ```
   > 2. **RNA STAR** {% icon tool %}: Run **RNA STAR** with
   >    - "*Single-end or paired-end reads*": `Paired-end (as individual datasets)`
   >    - "*RNA-Seq FASTQ/FASTA file, forward reads*": the generated `trimmed reads pair 1` files (multiple datasets)
   >    - "*RNA-Seq FASTQ/FASTA file, reverse reads*": the generated `trimmed reads pair 2` files (multiple datasets)
   >    - "*Custom or built-in reference genome*": `Use a built-in index`
   >    - "*Reference genome with or without an annotation*": `use genome reference without builtin gene-model`
   >    - "*Select reference genome*": `Drosophila Melanogaster (dm6)`
   >    - "*Gene model (gff3,gtf) file for splice junctions*": the imported `Drosophila_melanogaster.BDGP6.87.gtf`
   >    - "*Length of the genomic sequence around annotated junctions*": `36`
   ```

3. With parameter name in italic outside quote and with ":"
  
   ![screen shot 2018-05-22 at 13 18 11](https://user-images.githubusercontent.com/1842467/40359350-b79bc55a-5dc2-11e8-820f-902fc3329e60.png)

   ```
   > 2. **RNA STAR** {% icon tool %}: Run **RNA STAR** with
   >    - *Single-end or paired-end reads*: `Paired-end (as individual datasets)`
   >    - *RNA-Seq FASTQ/FASTA file, forward reads*: the generated `trimmed reads pair 1` files (multiple datasets)
   >    - *RNA-Seq FASTQ/FASTA file, reverse reads*: the generated `trimmed reads pair 2` files (multiple datasets)
   >    - *Custom or built-in reference genome*: `Use a built-in index`
   >    - *Reference genome with or without an annotation*: `use genome reference without builtin gene-model`
   >    - *Select reference genome*: `Drosophila Melanogaster (dm6)`
   >    - *Gene model (gff3,gtf) file for splice junctions*: the imported `Drosophila_melanogaster.BDGP6.87.gtf`
   >    - *Length of the genomic sequence around annotated junctions*: `36`
   ```


3. With parameter name in bold

   ![screen shot 2018-05-22 at 13 02 58](https://user-images.githubusercontent.com/1842467/40358995-734f5d18-5dc1-11e8-9d03-1f1896ad0fd8.png)

   ```
   > 2. **RNA STAR** {% icon tool %}: Run **RNA STAR** with
   >    - **Single-end or paired-end reads** to `Paired-end (as individual datasets)`
   >    - **RNA-Seq FASTQ/FASTA file, forward reads** to the generated `trimmed reads pair 1` files (multiple datasets)
   >    - **RNA-Seq FASTQ/FASTA file, reverse reads** to the generated `trimmed reads pair 2` files (multiple datasets)
   >    - **Custom or built-in reference genome** to `Use a built-in index`
   >    - **Reference genome with or without an annotation** to `use genome reference without builtin gene-model`
   >    - **Select reference genome** to `Drosophila Melanogaster (dm6)`
   >    - **Gene model (gff3,gtf) file for splice junctions** to the imported `Drosophila_melanogaster.BDGP6.87.gtf`
   >    - **Length of the genomic sequence around annotated junctions** to `36`
   ```

If we decide on a standard, we could remove the screenshots and document it as a good practice.

Any thought? @nekrut, @nsoranzo, @mblue9, @tnabtaf, @shiltemann, @bgruening

**Comment by nsoranzo** [comment]
My preferred option is 2. Replacing "to" by ":".

In 5. there's too much bold for my liking.

**Comment by mblue9** [comment]
I definitely prefer the colon and agree the bold is too much (same for italics I think). The quotes I don't have a strong opinion on but lean towards removing them.

**Comment by tnabtaf** [comment]
I've been using option 5 for ~10 years - **bold** for interface elements they need to update, *italics* for verbs *(set, click, change)*, and `fixed-width` for typed or selected options.  I actually want this stuff to stand out and I think bold, italics, and fixed-width achieve that nicely.

That said, whatever the majority wants is fine by me.

**Comment by njall** [comment]
With icons?

> 2. **RNA STAR** {% icon tool %}: Run **RNA STAR** with
>   :pencil2:  **Single-end or paired-end reads** to `Paired-end (as individual datasets)`
>   :pencil2: **RNA-Seq FASTQ/FASTA file, forward reads** to the generated `trimmed reads pair 1` files (multiple datasets)
>   :pencil2: **RNA-Seq FASTQ/FASTA file, reverse reads** to the generated `trimmed reads pair 2` files (multiple datasets)
> :white_check_mark: **Check-me checkbox** set to `true`
> 🖱 **My dropdown list** choose `the best possible option`

**Comment by shiltemann** [comment]
As a follow-up to @njall's idea, using fontawsome icons it could looks somthing like this:
 
![image](https://user-images.githubusercontent.com/2563865/40474163-93e21768-5f3e-11e8-8f2b-51161fa5472e.png)

but maybe makes it overly complicated to write the markdown?:

```
 2. **RNA STAR** {% icon tool %}: Map your reads on the reference genome with
>    - {% icon param-text %} "Some text field": `my value`
>    - {% icon param-file %} "Some input file": `my file`
>    - {% icon param-files %} "Multiple files or collection input": `my files`
>    - {% icon param-check %} "Some Checkbox": `yes`
>    - {% icon param-select %} "Some select parameter": `my choice`
```

I prefer 3 or 4 of the other options, definitely a fan of the colon, rest do not feel super strongly about (except I agree, emphasizing everything in bold is really emphasizing nothing)

**Comment by bgruening** [comment]
I like the icons, especially the  one-file, multiple-file distinction, this will help a lot in the future.
:+1: for @shiltemann :)

**Comment by hexylena** [comment]
solved
