### ISSUE TITLE
Maintaining a galaxyproject/galaxy Meta-Issue for Training Priorities?

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/training-material#679]
I've gotten the feedback a few times that the Galaxy development team focuses too much on developers and not enough on "users" (I try to avoid that word - I prefer researchers). Without weighing in on that specifically, I do know we could always do a better job soliciting feedback, filtering through it, and prioritizing it. This community already does serve as a proxy - not the only one - but an important one for researchers using the UI. I had an idea how that might be formalized a bit.

I was imaging it would be awesome if this community could maintain a prioritized meta-issue on galaxyproject/galaxy with links to more specific Galaxy issues for core platform issues that are important for the analyses here broadly and tutorials here specifically. It would be great if that meta-issue could include more training-specific context for each ranked and linked out issue such as how improvements to Galaxy would translate to superior training material.

For instance:

 - "In tutorial X, we tell the researcher to manually click through N different things when they should all be selectable at once. It would shorten the tutorial."
 - "In tutorial X, we have a section where describe this workaround for feature Y not working."
 - "In tutorial X, we avoid the use of collections because it they wouldn't work with step N."
 - "In slides X, the screenshot for step N is confusing because ..."

Nearly every issue on galaxyproject/galaxy is important, but there are almost 1000 open ones. Having this community provide a ranked list would be useful I think. It would allow developers to see right away the problem and be confident a useful, user-facing piece of documentation and a useful analysis type could be improved as a result of that. As a developer it is great to know there is a user story that would be improved with a PR and it is great to know what that story is. It would also be useful in reproducing the problem - since developers - even new developers - could walk the tutorial for instance.

In the past I've maintained these testing roadmap issues (https://github.com/galaxyproject/galaxy/issues/1419, https://github.com/galaxyproject/galaxy/issues/3245) for instance that were meant to sort of link out and organize my plans for Galaxy testing. There are some other similar issues that might even be better models - the IEs one (https://github.com/galaxyproject/galaxy/issues/372) or maybe the Galaxy overall Roadmap (https://github.com/galaxyproject/galaxy/issues/1928).

Maybe a few times a year the community could get together to re-prioritize and extend the meta issue also? It would be great if it could represent something of a consensus for training priorities.

I can't promise anyone besides me would take a look at it and I can't even promise to do anything with the issues beyond look through them and sort of re-weight my own priorities with the new additional information. But if you all have any interest in maintaining the issue - I can bring it up at the internal team meeting this week and try to raise some awareness internally. Also this is just my random thought - if this is not a good idea but there is some variant on this you all prefer - keep the issue here, use tags, etc... it is up to you. Any new feedback is appreciated though none is expected.

Thanks for your time!

**Comment by erasche** [comment]
Was already planning to bring something like this up. Glad to hear it coming from y'all's side as well. Would love to have all the UI/UX issues collated and if it will garner some developer attention, even better!

**Comment by mblue9** [comment]
@jmchilton I think this is a REALLY EXCELLENT IDEA!!!!!! Thanks a lot for initiating!!

**Comment by shiltemann** [comment]
I have moved this topic to a [github discussion](https://github.com/galaxyproject/training-material/discussions/2198) for gathering feedback from instructors for training priorities in Galaxy

**Comment by hexylena** [comment]
We have also implemented this idea with:

- https://github.com/orgs/galaxyproject/projects/7
  - @jennaj you closed this? I've reopened it but please let me know why :) 
- regularly discussing issues during CoFests
