### ISSUE TITLE
Fill the hands-on tutorial and the slides for "Setting up a Galaxy instance"

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#68]
Hi, 

The [tutorial for setting up a Galaxy instance](https://github.com/bgruening/training-material/blob/master/Admin-Corner/tutorials/setting_up_galaxy_instance.md) and the [associated slides](https://github.com/bgruening/training-material/blob/master/Admin-Corner/slides/setting_up_galaxy_instance.html) need to be filled with content and hand-on.
It can be nice to use the content of [10rules_for_GaaS](https://github.com/bgruening/training-material/blob/master/staging/10rules_for_GaaS.20160626.pptx)

Thanks,

Bérénice

**Comment by oinizan** [comment]
Maybe I could work on this ...
Olivier

**Comment by stevekm** [comment]
Is this for just regular Galaxy setup or does it also include Docker setup & usage?

**Comment by bgruening** [comment]
Both, I will put in some initial slides for Docker setup & usage tomorrow.

**Comment by stevekm** [comment]
OK I will put together the short workflow I've got so far; its not too much but maybe it will be useful.

**Comment by ValentinMarcon** [comment]
I join this issue too

**Comment by hrhotz** [comment]
please go ahead....I have to leave soon

**Comment by bebatut** [comment]
I think we have now a tutorial for that: [Deployment and Platform options](http://galaxyproject.github.io/training-material/topics/admin/tutorials/deployment-platforms-options/slides.html#1). I will close this issue
If I am mistaking, feel free to reopen the issue
