### ISSUE TITLE
Problem with metagenomics training docker image.

### ISSUE THREAD

**Issue by shiltemann** [galaxyproject/training-material#685]
(reported via email)

We are doing the Galaxy training 'Metagenomics' and experienced the following problem running `Merge.files` under Mothur:

```
Failed to activate conda environment! Error was: CondaEnvironmentError: Cannot activate
environment  bash. User does not have write access for conda symlinks. 
Fatal error: Exit code 1 ()
```

​The docker image used was:
```
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
quay.io/galaxy/metagenomics-training   latest              7b93c757c645        3 weeks ago         9.16GB
```
​
any ideas @bgruening?

**Comment by bgruening** [comment]
@shiltemann the other tools are working? Or nothing is working :(

**Comment by shiltemann** [comment]
@bgruening just tested locally, this appears to happen with other (non-mothur) tools as well :/

**Comment by bedroesb** [comment]
is working now, so I guess this can be closed @shiltemann

**Comment by hexylena** [comment]
Thanks @bedroesb
