### ISSUE TITLE
Missing step in "From peaks to genes" tutorial

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#686]
*reported via Twitter*

In ["From peaks to genes" tutorial](http://galaxyproject.github.io/training-material/topics/introduction/tutorials/galaxy-intro-peaks2genes/tutorial.html), in the [sophisticated approach](http://galaxyproject.github.io/training-material/topics/introduction/tutorials/galaxy-intro-peaks2genes/tutorial.html#part-2-more-sophisticated-approach) I think there is a step lacking in tutorial  which is step 12 in my analysis (https://t.co/aYFze52yWk), without it , intersect would not work with me , please check if I am correct.

Best regards

**Comment by nsoranzo** [comment]
By looking at the history, the person is importing the file directly from GEO instead of "the edited peak file (after the replace steps)" as advised in Part2 - Preparation, so they need the replace step which is done in Part 1.
