### ISSUE TITLE
Fill the hands-on tutorial and the slides for "Docker for Galaxy"

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#69]
Hi, 

The [tutorial on "Docker for Galaxy"](https://github.com/bgruening/training-material/blob/master/Admin-Corner/tutorials/setting_up_galaxy_instance.md) and the [associated slides](https://github.com/bgruening/training-material/blob/master/Admin-Corner/slides/setting_up_galaxy_instance.html) need to be filled with content and hand-on.

We can take inspiration from [Bjoern's slides](http://galaxy.slides.com/bgruening/the-galaxy-docker-project#/)

Thanks,

Bérénice

**Comment by bgruening** [comment]
I will work on this and port over my slides.

**Comment by bebatut** [comment]
We have now a slide deck for that: http://galaxyproject.github.io/training-material/topics/admin/tutorials/galaxy-docker/slides.html#1
Can I close this issue? @bgruening
