### ISSUE TITLE
Chip-seq tutorial-the Estrogen receptor

### ISSUE THREAD

**Issue by LeilyR** [galaxyproject/training-material#693]
In step4 of the tutorial 'Effective genome size” to hg19 ' needs to be updated to hg18
Also, in step 5 '“Effective genome size” to H. sapiens (2,451,960,000)' the number needs to be updated to 2.7e9.

**Comment by bgruening** [comment]
Thanks a lot @LeilyR!

**Comment by bebatut** [comment]
I fixed the second issue in #810
For the first one, we have the problem that hg18 can not be selected in bamCoverage. @bgruening any idea?

**Comment by dpryan79** [comment]
We really need to just use a more recent dataset for that tutorial. Maybe we have some public data from DEEP that we can use now, it'd certainly look nicer. As is we could update the files to GRCh38, but the would still look a lot worse than what people would actually produce these days.

**Comment by bgruening** [comment]
@LeilyR; @bebatut fixed this. Let me know if this works for you.
