### ISSUE TITLE
bwameth is not available as a tool?

### ISSUE THREAD

**Issue by efraimculfa** [galaxyproject/training-material#719]
I can't find bwameth under Mapping. I fed "bwameth" into the search tools box but it wouldn't come up.
What basic step am I missing again? Or is this really a bug?

**Comment by dpryan79** [comment]
Is it installed on the instance you're using?

**Comment by efraimculfa** [comment]
Oh I thought I was supposed to have it by default. Do I need to install the tool to Galaxy?

**Comment by dpryan79** [comment]
Yes, bwameth isn't installed by default (not much is) unless you're using a docker container for a specific training. If you happen to have run `docker run -d -p 8080:80 quay.io/galaxy/epigenetics-training` then it should be installed (if not, that's a bug that needs to get fixed).

**Comment by efraimculfa** [comment]
Please forgive me if my questions are embarrassingly basic but where do I run that command? Not an a random command prompt I assume?

**Comment by bgruening** [comment]
@efraimculfa you can also use this tool on one of the public Galaxy instances, for example https://usegalaxy.eu

**Comment by dpryan79** [comment]
I strongly encourage you to use usegalaxy.eu and make your life easier. We use that instance for training, so everything is already there :)

**Comment by efraimculfa** [comment]
thank you guys! I have googled as to how I could install a tool into galaxy and it already looks complicated.
