### ISSUE TITLE
Fill the introduction slide deck about Development in Galaxy

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#74]
Hi,

The [introduction slide decks Development in Galaxy](https://github.com/bgruening/training-material/blob/master/Dev-Corner/slides/index.html) needs to be filled.
I think it could be nice to give an introduction about Galaxy and what is inside Galaxy. I started by adding a [big picture of "Galaxy universe"](https://raw.githubusercontent.com/bgruening/galaxy-universe/master/images/main_scheme.png).

Thanks

Bérénice

**Comment by lecorguille** [comment]
It's needed to be refactoring and completing but there are some kind of hands-on embedded in the [slides](http://bgruening.github.io/training-material/Dev-Corner/slides/tool_integration.html#/2/8)

**Comment by bebatut** [comment]
To keep an up-to-date list, I open an issue to collect tutorials needing love #807
I close this issue to limit redundancy
