### ISSUE TITLE
HiCExplorer tour

### ISSUE THREAD

**Issue by joachimwolff** [galaxyproject/training-material#744]
One more issue I could not solve on my own:
- Double input again for large matrix import and for additional bigwig files as it was with the fastq files. Can you changes this here too @polkhe? Thanks a lot.

**Comment by bebatut** [comment]
@joachimwolff has this issue been fixed with #743 ? Can I close the issue?

**Comment by joachimwolff** [comment]
#743 changed some minor text issues but not that one.

**Comment by bebatut** [comment]
Do you think you can fix that?

**Comment by joachimwolff** [comment]
I don't think so. I don't have knowledge in creating / editing tours, therefore I pinged @polkhe.

----------------------------------------
Joachim Wolff
M.Sc. Computer Science
Bioinformatics Lab
Department of Computer Science
Albert-Ludwigs-University Freiburg
Georges-Koehler-Allee 079
D-79110 Freiburg

http://www.bioinf.uni-freiburg.de

**Comment by polkhe** [comment]
I will take care of it, sorry for the delay
