### ISSUE TITLE
Fill the hands-on tutorial and the slides on "Tool development and integration into Galaxy"

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#75]
Hi,

For "Tool development and integration into Galaxy", the [tutorial](https://github.com/bgruening/training-material/blob/master/Dev-Corner/tutorials/tool_integration.md) and the [associated slides](https://github.com/bgruening/training-material/blob/master/Dev-Corner/slides/tool_integration.html) need to be filled with content and hand-on.

As said in #50, it can be nice to take inspiration from:
- [Gildas' slides](https://www.dropbox.com/s/afoftkt2k103tdx/galaxy4bioinformatics-integration-partI-1.13.pdf?dl=0)
- [Some slides I made for a workshop](http://bebatut-slides.github.io/galaxy_workshop_05_16)
- [Planemo's tutorial](http://planemo.readthedocs.io/en/latest/writing.html)

We can also split the tutorial in two parts like Planeno's one.

@lecorguille You said you plan to work on this during the contribution fest. Do not you?

Bérénice

**Comment by bebatut** [comment]
@lecorguille plans to work on this. 
I will first add some material I have

**Comment by lecorguille** [comment]
I guess that the link to Panemo tutorial fill the need!
Should we close this issue?

**Comment by bgruening** [comment]
Good catch!
