### ISSUE TITLE
Fill the hands-on tutorial and the slides on "Data source integration"

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#76]
Hi,

For "Data source integration", the [tutorial](https://github.com/bgruening/training-material/blob/master/Dev-Corner/tutorials/data_source_integration.md) and the [associated slides](https://github.com/bgruening/training-material/blob/master/Dev-Corner/slides/data_source_integration.html) need to be filled with content and hand-on.

Thanks,

Bérénice

**Comment by gmauro** [comment]
Hi, I am interested in this topic. Maybe I could work on this ...

**Comment by bgruening** [comment]
@gmauro !!! A few resources and example code can be found here: https://wiki.galaxyproject.org/Admin/Internals/DataSources

**Comment by bebatut** [comment]
To keep an up-to-date list, I open an issue to collect tutorials needing love #807
I close this issue to limit redundancy
