### ISSUE TITLE
Resource has placeholder metadata

### ISSUE THREAD

**Issue by njall** [galaxyproject/training-material#769]
https://github.com/galaxyproject/training-material/blob/6bab7a23393670fc3e55c868b478f3ff200064ae/topics/introduction/metadata.yaml#L178

**Comment by bebatut** [comment]
What do you mean there @njall ?

**Comment by njall** [comment]
Maybe not the best link there. I was referring to how the values for Questions, Objectives, & Key points are all placeholder text (e.g. This is the first take home message).

https://github.com/galaxyproject/training-material/blob/6bab7a23393670fc3e55c868b478f3ff200064ae/topics/introduction/metadata.yaml#L187

**Comment by bebatut** [comment]
Good point! Thanks! I will clean them
