### ISSUE TITLE
Fill the hands-on tutorial and the slides on "Visualizations in Galaxy"

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#77]
Hi,

For "Visualizations in Galaxy", the [tutorial](https://github.com/galaxyproject/training-material/blob/master/Dev-Corner/tutorials/visualizations.md) and the [associated slides](https://github.com/galaxyproject/training-material/blob/master/Dev-Corner/slides/visualizations.html) need to be filled with content and hand-on.

Documentation about Galaxy visualizations can be used as base:
- https://wiki.galaxyproject.org/VisualizationsRegistry
- https://wiki.galaxyproject.org/VisualizationsRegistry/Cookbook
- https://wiki.galaxyproject.org/VisualizationsRegistry/Code
- https://wiki.galaxyproject.org/DataProviders
- https://wiki.galaxyproject.org/DataProviders/Cookbook
- https://wiki.galaxyproject.org/Develop/Visualizations

Thanks,

Bérénice

**Comment by lecorguille** [comment]
@shiltemann @yhoogstrate Maybe we should close this issue 👍
