### ISSUE TITLE
Build the Docker image for dev-corner

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#78]
Hi,

The Docker image for Dev-corner need to be build to be available.

Thanks

Bérénice

**Comment by gmauro** [comment]
I have started to add tools to the Docker image for Dev-corner, see #116

**Comment by jmchilton** [comment]
Is there any way we can make this planemo-machine Docker image? I'd be willing to make changes to it to make this happen. It is probably more used and documented, it has some tests (and will be getting more), and has corresponding virtualbox images, etc...

**Comment by bgruening** [comment]
Sure, we just need to link this out in the training material. I don't think we need to host the code here, especially not if it is more complex that creating a flavor.

**Comment by martenson** [comment]
Yes please, connect these with the planemo-machine. http://planemo.readthedocs.io/en/latest/appliance.html

**Comment by jmchilton** [comment]
I'll try to tackle this @martenson. I want to do another revision on planemo-machine with more automated testing (it is WIP on my end). Once I am confident we have a good machine for GCC 2017  - I'll run through the examples here and update things.
