### ISSUE TITLE
Fill the hands-on tutorial and the slides for "Galaxy introduction" and add a Galaxy tour

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#80]
Hi, 

The [tutorial on "Galaxy Introduction"](https://github.com/bgruening/training-material/blob/master/Introduction/tutorials/Introduction.md) and the [associated slides](https://github.com/bgruening/training-material/blob/master/Introduction/slides/introduction.html) need to be filled with content and hand-on.

I thought to combine in this tutorial:
- [Previous course "From Peaks to Genes"](https://github.com/bgruening/training-material/blob/master/Introduction/tmp/Introduction.md)
- [Galaxy 101-1: The first thing you should try](https://github.com/bgruening/training-material/blob/master/Introduction/tmp/Galaxy101-1.md)

We also need to add a [Galaxy tour](https://github.com/galaxyproject/galaxy-tours) for this tutorial.

Thanks,

Bérénice

**Comment by nsoranzo** [comment]
The first 4 links are broken, they should be:
- https://github.com/bgruening/training-material/blob/master/Introduction/tutorials/Introduction.md
- https://bgruening.github.io/training-material/Introduction/slides/
- https://github.com/bgruening/training-material/blob/master/Introduction/tmp/Introduction.md
- https://github.com/bgruening/training-material/blob/master/Introduction/tmp/Galaxy101-1.md

**Comment by bebatut** [comment]
Thanks! I thought that relative link from the root directory were working :(

**Comment by bgruening** [comment]
Reminds me of: https://github.com/bgruening/training-material/pull/23 ... I will work on this next week :)

**Comment by nsoranzo** [comment]
Links 3 and 4 are still not working

**Comment by bebatut** [comment]
@nsoranzo I was too fast...
@bgruening It is also in my TODO list. I thought to split it also to open some easy "newcomer friendly" issues

**Comment by shiltemann** [comment]
I'd be happy to work on this (can't assign myself but feel free to do so)

**Comment by bgruening** [comment]
I added you as collaborator.

**Comment by shiltemann** [comment]
great, thanks! (it seems to be taking github a while to realise this, will assign myself once it does ;))

**Comment by bebatut** [comment]
I think we have quite a lot of intro tutorials now :smile: http://galaxyproject.github.io/training-material/topics/introduction/
