### ISSUE TITLE
Fill the hands-on tutorial and the slides for "Getting to know workflows" and add a Galaxy tour

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#81]
Hi, 

The [tutorial on "Getting to know workflows"](https://github.com/bgruening/training-material/blob/master/Introduction/tutorials/workflows.md) and the [associated slides](https://github.com/bgruening/training-material/blob/master/Introduction/slides/workflows.html) need to be filled with content and hand-on.

We can take inspiration from ["Galaxy 101-2: Getting to know workflows"](https://github.com/bgruening/training-material/blob/master/Introduction/tmp/Galaxy101-2.md).

We also need to add a [Galaxy tour](https://github.com/galaxyproject/galaxy-tours) for this tutorial.

Thanks,

Bérénice

**Comment by shiltemann** [comment]
this part was the continuation of the Galaxy101 tutorial, I have combined the two in the new tutorial, so this can probably be closed

**Comment by bebatut** [comment]
I close this issue: we have now tutorial for that http://galaxyproject.github.io/training-material/topics/introduction/tutorials/galaxy-intro-history-to-workflow/tutorial.html
