### ISSUE TITLE
Fill the introduction slide deck about NGS-QC

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#84]
Hi, 

I started to fill the introduction slide deck about [NGS-QC](https://github.com/bgruening/training-material/blob/master/NGS-QC/slides/index.html). The first part still needs to be filled.

Thanks

Bérénice

**Comment by yvanlebras** [comment]
Hi,

This issue is related to #85 ?

Thanks,

Yvan

**Comment by bebatut** [comment]
Hi,

It is related. But here it is more a slide deck to introduce people to main concept of QC. In #85, it is a tutorial with hands-on (a markdown file and an associated slide deck).
Check in [`CONTRIBUTING.md`](https://github.com/bgruening/training-material/blob/master/CONTRIBUTING.md#how-the-training-material-is-structured) to have more details about what you would like to have. I hope it will answer your questions

**Comment by mwolfien** [comment]
I would be fine to do this introduction part =) Are you currently on this @yvanlebras ?

**Comment by yvanlebras** [comment]
Hi @mwolfien It's not something I can treat before last week because I want to go deeper on the rad-seq training.... If you want to work on it, din't hesitate! Maybe I can review the results of this section if this can be of interest. ....

**Comment by mwolfien** [comment]
Sure, I will start right after dinner =P

**Comment by bebatut** [comment]
We have slides for that now: http://galaxyproject.github.io/training-material/topics/sequence-analysis/tutorials/quality-control/slides.html#1
