### ISSUE TITLE
MSGFPlusAdapter Problem in Peptide and Protein ID using OpenMS tools

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/training-material#847]
The MSGFPlusAdapter step in the tutorial gives me (using the provided mzML files): 

in the stderr:
```
Fatal error: Exit code 9 ()
java.lang.NullPointerException
	at edu.ucsd.msjava.msutil.Spectrum.getCharge(Spectrum.java:124)
	at edu.ucsd.msjava.msutil.SpecKey.getSpecKeyList(SpecKey.java:91)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:220)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:105)
	at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:56)
```

in the stdout:
```
Fatal error: Running MS-GF+ returned an error code '255'. Does the MS-GF+ executable (.jar file) exist?
```

Apparently Spectrum.java:124 tries to get the charge of a precursor (and some spectra seem to have no precursor).

**Comment by bernt-matthias** [comment]
see also 
https://github.com/OpenMS/OpenMS/issues/3576
https://github.com/MSGFPlus/msgfplus/issues/39

**Comment by bernt-matthias** [comment]
The first replies in the upstream issues indicate that there is a problem in the mzML file.

**Comment by hexylena** [comment]
Is this still an issue @bernt-matthias?

**Comment by bernt-matthias** [comment]
I think this can be closed.
