### ISSUE TITLE
Fill the introduction slide deck about NGS-Mapping

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#86]
Hi, 

[The introduction slide deck on NGS-Mapping](https://github.com/bgruening/training-material/blob/master/NGS-mapping/slides/index.html) needs to be filled

Thanks

Bérénice

**Comment by friedue** [comment]
Whoever is going to follow up on this topic: feel free to use parts of the [course](http://chagall.med.cornell.edu/RNASEQcourse/Intro2RNAseq.pdf) I compiled, particularily chapters 2 and 3 contain lots of details about general NGS topics such as file formats.

**Comment by bebatut** [comment]
I have now slides for that: http://galaxyproject.github.io/training-material/topics/sequence-analysis/tutorials/quality-control/slides.html#1
