### ISSUE TITLE
requesting push access to training material 

### ISSUE THREAD

**Issue by nvk747** [galaxyproject/training-material#884]
@bebatu 

can you give me push access to training-material for adding a new png image for HISAT2 in the de-novo transcriptomics tutorial?

**Comment by bebatut** [comment]
@nvk747 You can contribute by forking the repository and then opening Pull Request to propose your changes.

Please follow one of the following tutorials to learn how to do that:

- [Contributing with GitHub via its interface](http://galaxyproject.github.io/training-material/topics/contributing/tutorials/github-interface-contribution/tutorial.html)
- [Contributing with GitHub via command-line](http://galaxyproject.github.io/training-material/topics/contributing/tutorials/github-command-line-contribution/tutorial.html)
