### ISSUE TITLE
Master Review Ticket: Variant Analysis, Exome sequencing data analysis

### ISSUE THREAD

**Issue by destinymullens** [galaxyproject/training-material#892]
# Topic: Variant Analysis, Title: Exome sequencing data analysis
**[Tutorial Link](http://galaxyproject.github.io/training-material/topics/variant-analysis/tutorials/exome-seq/tutorial.html)** 
**Component:** Hands-on
**Contribution:** Language simplification & grammar, Methods & Materials

## Testing at Galaxy EU

**[Test history](https://usegalaxy.eu/u/destiny_mullens/h/variant-analysis-tutorial)** 

**Issues Found**

Tutorial Agenda Item#2: Variant Calling
Hands-on: Annotating Variants 
Step 3: Annotate your variants with some functional information
- Details: Unable to use downloaded genome from SnpEff or when using locally installed genome (native index) Genome hg19. 
 - SnpEff tool version not mentioned in tutorial: **ADD** 
 - EU has what looks like older tool version: SnpEff Variant effect and annotation (Galaxy Version 4.3r.1)
 - Most current version in MTS: 4.3+T.galaxy1 
- [MTS Link](https://toolshed.g2.bx.psu.edu/view/iuc/snpeff/85ca751407c3)
 - Open issues for tool v4.3+T.galaxy1: [#1787](https://github.com/galaxyproject/tools-iuc/pull/1787) 

## Testing at Galaxy Main

**[Test history](https://usegalaxy.org/u/dmcneece/h/exome-sequencing-data-analysis)** 

**Issues Found**

Tutorial Agenda Item# 1 Data-preprocessing:
Hands-on: Data pre-processing
Step 3 Import the reference genome: 
- Details: Reference genome in tutorial not in shared library. Downloaded genome from from EU and imported to ensure it was the correct file. File is [here](https://usegalaxy.eu/library/list#folders/Fdf740ff7e86f2efb/datasets/4146325a2c166c73).

- Tutorial Agenda Item# 3 Post-processing:
Hands-on: Post-processing
Step 1 Use the tool GEMINI load in Gemini to create a database out of our combined VCF file and the PED file
- Details: Error when attempting to run Gemini load during the tutorial
- [Error Message Link](https://usegalaxy.org/datasets/error?dataset_id=bbd44e69cb8906b5950b80df74596b05&__identifer=kjk5yh8ohg)

> Fatal error: Exit code 1 ()
> 
> CADD scores are not being loaded because the annotation file could not be found.
> `Run gemini update --dataonly --extra cadd_score` to install the annotation file.
> 
> 
> GERP per bp is not being loaded because the annotation file could not be found.
>     Run `gemini update --dataonly --extra gerp_bp` to install the annotation file.
> 
> Gemini cannot open this annotation file: /galaxy/main/deps/gemini/0.18.1/iuc/package_gemini_0_18_1/49de32b47548/gemini_data/hg19.gwas.bed.gz. 
> Have you installed the annotation files?  If so, have they been moved or deleted? Exiting...
> 
> For more details:
> 	http://gemini.readthedocs.org/en/latest/content/#installation.html\#installing-annotation-files
> 
> WARNING:galaxy.datatypes.binary:<galaxy.datatypes.binary.GeminiSQLite object at 0x2b46c9d68390>, set_meta Exception: no such table: version

## Testing at Galaxy AU
**[Test History](https://usegalaxy.org.au/u/destinymullens/h/exome-sequencing-data-analysis)** 

**Issues Found**

Tutorial Agenda Item# 1 Data-preprocessing:
Hands-on: Data pre-processing
Step 3 Import the reference genome: 
- Details: Reference genome in tutorial not in shared library. Downloaded genome from from EU and imported to ensure it was the correct file. File is [here](https://usegalaxy.eu/library/list#folders/Fdf740ff7e86f2efb/datasets/4146325a2c166c73).

Tutorial Agenda Item# 2 Variant Calling:
Hands-on: Generating FreeBayes calls
Step 3 Run FreeBayes
- Details: Able to select options and run FreeBayes but returns with error.
[Error Message Link](https://usegalaxy.org.au/datasets/error?dataset_id=274b9e003aea989c&__identifer=b28ravb7r1d)
> Fatal error: Exit code 93()
> index file /cvmfs/data.galaxyproject.org/byhand/hg19/seq/hg19.fa.fai not found, generating...
> could not open index file /cvmfs/data.galaxyproject.org/byhand/hg19/seq/hg19.fa.fai for writing!
> index file /cvmfs/data.galaxyproject.org/byhand/hg19/seq/hg19.fa.fai not found, generating...

**Comment by wm75** [comment]
@bgruening @bebatut just working through the exome-seq tutorial in preparation of a course tomorrow and found one additional issue:
The dbSNP file at https://zenodo.org/record/60520/files/dbSNP_138.hg19.vcf does not seem to have **any** SNP ids. Could it be that the wrong file got uploaded to zenodo? To me it looks as if it contains the variants called from the RS024M-MOTHER sample.

Additional question: which variant am I supposed to identify as the disease-causing mutation (the tutorial doesn't seem to reveal it and it looks as if I'm too stupid to succeed on my own :disappointed: ).

**Comment by erasche** [comment]
Hey @wm75 can you check if this is still an issue?

**Comment by wm75** [comment]
These issues are all about the previous version of the tutorial and have been addressed in its rewrite.
