### ISSUE TITLE
Master Review Ticket: Transcriptomics, De-novo transcriptome reconstruction with RNA-Seq

### ISSUE THREAD

**Issue by nvk747** [galaxyproject/training-material#902]
**Topic:** Transcriptomics, Title: De-novo transcriptome reconstruction with RNA-Seq
**Tutorial Link:** http://galaxyproject.github.io/training-material/topics/transcriptomics/tutorials/de-novo/tutorial.html
Contribution: Language simplification & grammar, Methods & Materials

Component one or more of:
1) Hands-on: currently presented with an older version of tools listed below (check To-do). 
2) Input dataset works with NEW/er tool versions, so no changes required.
3) workflows, galaxy tour need to be changed as with the latest tool options
**4) Docker instance not available**

----

Testing at Galaxy Main: 
Test history:  https://usegalaxy.org/u/nvk/h/testing-denovo-transcriptomics  

----

Testing at Galaxy EU
Test history placeholder_testing_history_usegalaxy.eu

----
To-do :        
Hands-on tutorial text options need to be updated with the latest tool options for all dependencies in this tutorial. The text need to be modified presenting latest tool options. 
1. Upgrade Trimmomatic flexible read trimming tool for Illumina NGS data version 0.32.3 to 0.36.5                
              (link to latest version: https://toolshed.g2.bx.psu.edu/view/pjbriggs/trimmomatic/dfa082f84068)               

2. Upgrade HISAT2 A fast and sensitive alignment program Tool version 2.0.3 to 2.1.0 
                 (link to latest version: https://toolshed.g2.bx.psu.edu/view/iuc/hisat2/6ab42baa56e9)
3. Upgrade StringTie transcript assembly and quantification version 1.2.3 to 1.3.3.2 
                (link to latest version: https://toolshed.g2.bx.psu.edu/view/iuc/stringtie/eafd5dc95228)
4. featureCounts Measure gene expression in RNA-Seq experiments from SAM or BAM files version 
    1.4.6.p5 to 1.6.0.6.  
                (link to latest version: https://toolshed.g2.bx.psu.edu/view/iuc/featurecounts/8ce1e2c7ee72)
5. DESeq2 Determines differentially expressed features from count tables version 2.11.38 to 2.11.40.2
		(link to latest version: https://toolshed.g2.bx.psu.edu/view/iuc/deseq2/9a616afdbda5)

**Comment by jfallmann** [comment]
Small fix here:
https://github.com/galaxyproject/training-material/pull/1334

**Comment by erasche** [comment]
@abretaud is this now ok?

**Comment by abretaud** [comment]
No idea, I can have a look, but that one is not the same as #1351 (we should make some clarification in the title if/when #1351 gets finished)

**Comment by abretaud** [comment]
Tools/tutorial were updated in #1001, so closing
