### ISSUE TITLE
Tutorials with no tools end up with no "Galaxy instances" tagged

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/training-material#904]
Some ideas, am sure there are others. However we resolve is Ok with me.

 - Check and if a tuto has no tools, annotate it as available "Any server" or something similar

or 

- Add a new metadata feature where the minimum Galaxy version can be noted and display that somewhere on tuto overview

Example

<img width="1126" alt="screen shot 2018-07-01 at 2 02 32 pm" src="https://user-images.githubusercontent.com/8999735/42138802-184955ea-7d38-11e8-8e32-e8c900474cb4.png">

**Comment by erasche** [comment]
:+1: for minimum galaxy version. We definitely need that for the rule builder tutorial.

**Comment by bebatut** [comment]
any idea how we could ping that? should we add sth in the metadata to mention no tool but Galaxy version?

**Comment by jennaj** [comment]
or add min version to all? 

or all going forward, plus go back to existing as have time? 

so.. optional or required?

required is a lot of work, can't think of way to automate. thoughts?

intermediate functions even in totus *with* tools may be newish. many public servers are conservative & wait to upgrade, a year not uncommon, sometimes bit more (except for security or point updates)

collections/rules methods good example where version really matters, all that is new when considered in full 

Thx for considering suggestion :)

**Comment by erasche** [comment]
optional sounds good, required would be tougher
