### ISSUE TITLE
Fill the introduction slide deck about RNA-seq

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#93]
Hi,

The [introduction slide deck on RNA-Seq](https://github.com/bgruening/training-material/blob/master/RNA-Seq/slides/index.html) needs to be filled.

We can take inspiration from:
- [Previous slide deck](https://github.com/bgruening/training-material/blob/master/RNA-Seq/tmp/RNAseq_introduction.pdf)

Thanks

Bérénice

**Comment by mwolfien** [comment]
I will start to fill the deck.

**Comment by bebatut** [comment]
Thanks

**Comment by bebatut** [comment]
We have slides for that now: http://galaxyproject.github.io/training-material/topics/transcriptomics/slides/#1
