### ISSUE TITLE
GTN CoFest: 17th of August

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#939]
![cofests](https://user-images.githubusercontent.com/1842467/42893705-61ab9eca-8ab5-11e8-8d98-769e4e6b7569.png)

We are starting a series of regular online CoFests, every 3 months on the 3rd Friday, for a day of the collaborative work on the training material.

The first one will be on the **17th of August**.

We plan to focus on metagenomics training; but anyone who would like to contribute on any other topics is very welcome to join.

We will coordinate via the [GTN Gitter channel](https://gitter.im/Galaxy-Training-Network/Lobby) and GitHub issues here.

If you want to join to help or to talk and learn about the project, let us know here or on the Gitter channel.

---
*@bebatut and @shiltemann will be online between 9am and 6pm (CEST) but people from other time zones should feel welcome to continue even before/after. We will keep an eye on Gitter and GitHub*

**Comment by AnnaSyme** [comment]
Great, I will plan to join in, thanks!

**Comment by bebatut** [comment]
The CoFest is on Friday!
---

It will be part of the [OBF CoFest](https://www.open-bio.org/wiki/CoFest_2018_August).

We plan to **start at 9am (CEST)**, **end around 6pm (CEST)** and have call meetings (using [Hangout](https://hangouts.google.com/hangouts/_/calendar/Z2FsYXh5dW5pZnJlaWJ1cmdAZ21haWwuY29t.55dck65etnslp0av1tmk0hgre2?authuser=1)) at **10am (CEST) and 4pm (CEST)**. People from other time zones should feel welcome to continue even before/after.

We will coordinate via [Hangout](https://hangouts.google.com/hangouts/_/calendar/Z2FsYXh5dW5pZnJlaWJ1cmdAZ21haWwuY29t.55dck65etnslp0av1tmk0hgre2?authuser=1) (on the whole day) and the [GTN Gitter channel](https://gitter.im/Galaxy-Training-Network/Lobby).
*We will be happy to see you. So drop us an "Hello" on Gitter or Hangout*😄

During the day, we also would like to have a call meeting with the GTN discuss the recent changes and future directions. More details can be found in this issue #954

**Comment by bebatut** [comment]
Some contribution ideas
----

- Metagenomics
    - Test and update the current tutorials
        - Mothur: update the workflow
        - General tutorial
    - Add new tutorials
        - [Tutorial to learn how to create new tutorial](http://galaxyproject.github.io/training-material/topics/contributing/tutorials/create-new-tutorial/tutorial.html)
        - Some ideas of new tutorials
            - Assembly workflows ([one with MetaSPAdes](), [one with MEGAHIT]())
                - Need to find some meaningful input data (for example, …)
                - Write the tutorial using the planemo skeleton
            - Shotgun metagenomics
                - [Workflow](https://usegalaxy.eu/u/berenice/w/asaim-shotgun-workflow)
                - Open Pull Request: #514
            - Strain profiling
            - Metagenomics visualization
    - Add tests for workflows following the example in #761
- General contributions
    - Test and take over any tutorial
        - Test the tutorial on a running Galaxy instance (usegalaxy.org, usegalaxy.eu, usegalaxy.org.au) and report any possible error as an issue
        - Simplify the english of the sentences (to make it more accessible)
        - Improve the content (particularly the context of the analysis, the direction for the tutorial)
        - Add questions (inside the boxes) to make people think (about the results they got, about the relation to the original question, etc)
        - Improve the learning objectives, questions and key points in the metadata
        - Extract workflow
        - Add input data to Zenodo
        - Add `data-library.yaml` file
        - Add tests for workflows
    - Some tutorials asking for love #807
    - Fix or take over some Issues
        - Newcomer friendly labelled issues: https://github.com/galaxyproject/training-material/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Anewcomer-friendly
        - CoFest labelled issues: https://github.com/galaxyproject/training-material/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3ACoFest
    - Review of open Pull Requests: https://github.com/galaxyproject/training-material/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

**Comment by bebatut** [comment]
Reviewer Tracking Details
----

To avoid overlapping review let's use this issue during the CoFest.

Please post here as a comment the tutorial you are working on including the following information:

- **Topic** (top level, example "Introduction to Galaxy")
- **Tutorial** (name, example "From peaks to genes")
- **Component** one or more of:
  - **Slides**
  - **Hands-on**
  - **Input dataset**
  - **Workflows**
  - **Galaxy tour**
  - **Galaxy instances**
- **Contribution** one or more of:
  - **Language** technical writing: simplification, syntax, style, spelling, pronoun/verbage
  - **Scientific** clarify and enhance scientific content: descriptions, references, manuals, other tutorials/public community resources
  - **M&M** "Materials and Methods": test the tutorial on one or more of the public servers and/or the Docker available for the tutorial suite, export the workflow, etc
      If you need more quota space on a server to retain the test history during review, let us know. Tag/save these during review. Once completed or you want to pass this one (are done with your current contribution), we can copy these into an admin account and update the history/workflow share link in the issue ticket.

**Comment by Slugger70** [comment]
Hi @bebatut and @shiltemann, I'm going to add in our FROGS tutorial and set it to enabled=false as per Saskia's instructions. :)

Topic: Metagenomics
Tutorial: 16S Metagenomics analysis with FROGS 
Component one or more of:
Slides: No
Hands-on: Yes
Input dataset: Yes
Workflows: Maybe
Galaxy tour: Maybe
Galaxy instances: Unsure but most likely usegalaxy.org.au

**Comment by bebatut** [comment]
Thanks to everyone that contributed to the CoFest last Friday.
The next one will be the 15th of November. You can vote for a topic (or non topic) there: goo.gl/forms/d6ZZVjsWuFlEvLiL2
