### ISSUE TITLE
Metadata of a tutorial in the same Markdown file as the tutorial

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#947]
As discussed during BOF at GCC/BOSC 2018 (see #941), it would be nice to have metadata of a tutorial in the same Markdown file as the tutorial to simplify the contribution.

**Comment by bebatut** [comment]
We discussed it with @erasche and came to the conclusion that we could first move some of the metadata specific to the tutorials or slides to the top metadata of the tutorial: `questions`, `objectives`, `time_estimation`, `key_points`, `zenodo_link`

Hopefully, the others metadata will not be touched too often and could stay in the `metadata.yaml` at least for now

@shiltemann what do you think?

**Comment by shiltemann** [comment]
I think this makes a lot of sense :+1:

**Comment by bebatut** [comment]
We will need to update the TeSS scrapper (https://github.com/ElixirTeSS/TeSS_scrapers/blob/master/app/scrapers/galaxy_scraper.rb)
