### ISSUE TITLE
Fill the hands-on tutorial and the slides for MethylC Seq tutorial and add a Galaxy tour

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#96]
Hi, 

The [tutorial](https://github.com/bgruening/training-material/blob/master/MethylC-Seq/tutorials/methylc_seq.md) and the [associated slides](https://github.com/bgruening/training-material/blob/master/MethylC-Seq/tutorials/methylc_seq.html) on MethylC-seq needs to be filled.

We can take inspiration from [the previous tutorial](https://github.com/bgruening/training-material/blob/master/MethylC-Seq/tmp/Methylation-Seq.md).

We also need to add a Galaxy tour

Thanks,

Bérénice

**Comment by yvanlebras** [comment]
Hi @bebatut, can you refresh my memory, I don't remember on which platform/tool is based interactive tour functionality. @bgruening already gave me the info and I can't remember... This can help me finish the RADseq interactive tour with better content & maybe try to help for other interactive tours as for MethylC seq....

**Comment by bgruening** [comment]
@yvanlebras it is based on http://bootstraptour.com!

**Comment by yvanlebras** [comment]
Yes!!! I remember now ;) Thank you very much!!!! 

----- Mail original -----

> De: "Björn Grüning" <notifications@github.com>
> À: "bgruening/training-material" <training-material@noreply.github.com>
> Cc: "Yvan Le Bras" <yvan.le_bras@irisa.fr>, "Mention"
> <mention@noreply.github.com>
> Envoyé: Samedi 26 Novembre 2016 22:26:14
> Objet: Re: [bgruening/training-material] Fill the hands-on tutorial and the
> slides for MethylC Seq tutorial and add a Galaxy tour (#96)

> @yvanlebras it is based on http://bootstraptour.com !

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub , or mute the thread .

-- 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
Yvan Le Bras, PhD @Yvan2935 <°))))>< 
Projet 65 Millions d'observateurs https://65mo.wordpress.com/ 
Bureau 34, Station de Biologie marine BP 225, 29182 Concarneau CEDEX --- MNHN EGB/CESCO UMR 7204 43 rue Buffon 75005 PARIS 
tél.: +33 (0) 6.10.43.96.51 
yvan.le_bras@irisa.fr / yvan.le-bras@mnhn.fr

**Comment by bebatut** [comment]
The tutorial is available there http://galaxyproject.github.io/training-material/topics/epigenetics/tutorials/methylation-seq/tutorial.html
