### ISSUE TITLE
Links are broken in a few documents

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/training-material#97]
We have some initial travis testing if all liks are working on our training material. Unfortunately, we have a few links that are broken. Good that we have testing now and here is a list of broken links that needs to be fixed: https://travis-ci.org/bgruening/training-material/builds/165055318

Let me know if you want to work on this :)
Bjoern

**Comment by bgruening** [comment]
If this issue is fixed we can merge https://github.com/bgruening/training-material/pull/23

**Comment by Stortebecker** [comment]
I do not really get how to read the travis output. Which of those links are broken?

**Comment by bgruening** [comment]
The red ones, e.g. https://travis-ci.org/bgruening/training-material/builds/165055318#L1140

and this ones: https://travis-ci.org/bgruening/training-material/builds/165055318#L872

**Comment by shiltemann** [comment]
@Stortebecker are you working on this? if not I will, think this is nice to have as soon as possible ..do we want to replace links within repo (e.g. https://github.com/bgruening/training-material/blob/master/Galaxy_Introduction/Galaxy_Introduction.md) with relative links so it is easier to move out of your account and into galaxyproject in the long term @bgruening ?

**Comment by bgruening** [comment]
Relative links are always preferable! But if this is too complicated for beginners I'm fine with leaving it for the moment and get this under travis testing. It will break as soon as we move it over to galaxyproject and we could fix it then.

**Comment by Stortebecker** [comment]
@shiltemann Yes, I fixed the links. Some in the travis testing were actually working, so I did not change all of them. One that I cannot fix is the link to Data Sources, as I cannot find the content it is supposed to link to.

**Comment by shiltemann** [comment]
@bgruening  fair enough :) 

@Stortebecker awesome, think the Data Sources files got renamed to data-source-integration maybe?

**Comment by Stortebecker** [comment]
@shiltemann Ok, done.

**Comment by Stortebecker** [comment]
Am I right that a relative link would look like this?
https://github.com/bgruening/training-material/tree/master/ChIP-Seq 
--> ./tree/master/ChIP-Seq

**Comment by shiltemann** [comment]
you can leave out the `tree/master` bit, it will automatically look in current branch, just relative links like you would do on your local filesystem, so depending on where the file itself is it could be `../ChiP-Seq` or `subdir/ChiP-Seq` etc

**Comment by shiltemann** [comment]
easiest is to just push changes to your fork and test by clicking on them there, if it works there it will work here too :)

**Comment by bgruening** [comment]
There are new links broken at the moment and it would be nice to fix this either early during the hackathon or before. We should also rework the link checking part I think for your testing.

**Comment by bebatut** [comment]
I think we fixed this issue with Travis and systematic testing of the links in the tutorials and the slides with htmlproofer
