### ISSUE TITLE
Training more prominently on usegalaxy.* welcome pages

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#979]
@bgruening during last GTN meeting (#954) wants to know if there are any way we can put training more prominently on usegalaxy.* welcome pages

Strategy:
- Highlight a training of the month in the news and tweet it
- Put a link in the masthead
- Post tool/workflow webhook

**Comment by bebatut** [comment]
As discussed during last GTN meeting (#954 and #979), we plan to highlight a training per month. What about starting this month (on the 15)? Which tutorial should we highlight?

**Comment by yvanlebras** [comment]
Several criteria IMO:
- a "golden standard" one in term of content (full of explanations and materials) ? RNAseq ?
- one who is trained / the more used by a GTN trainer or other this month?
- the more recent one?
- ...

**Comment by bebatut** [comment]
We could ask someone different every month (can be a user, a contributor) to select one tutorial and explain in few sentences why they select this tutorial.
What do you think about this idea?

**Comment by MoHeydarian** [comment]
I very much support the GTN highlighting a tutorial a month. It would provide additional exposure to GTN and highlight the work of individual contributions. 

@tnabtaf and I were planning on including a GTN highlight in each monthly Galaxy newsletter. We could start next month with this recurring GTN highlight. We should get a calendar in place so contributors can know when to expect a highlight or even volunteer their tutorial to be in the spotlight.

**Comment by bgruening** [comment]
What about the `peak to genes`. I think this one fulfills @yvanlebras requirements and it kind of makes sense to start with an introduction.

**Comment by yvanlebras** [comment]
My favourite one! I always trained people using Galaxy through this wonderfull "simple" example... and this terrible question: "Which chromosome contained the highest number of target genes ?"

**Comment by mblue9** [comment]
👍 for peaks to genes (esp. as I'll be teaching that one on October 1st and it would be cool if it's the "tutorial of the month" 😄 )

**Comment by tnabtaf** [comment]
Hi All, as long as there is a slide deck on usegalaxy.org landing page, it's relatively easy to highlight a tutorial.  I need to update that one anyway.  Unless I hear otherwise, I'll highlight peaks to genes early next week.

**Comment by bebatut** [comment]
The serie "Tutorial of month" has started: https://galaxyproject.org/blog/2018-09-totm/ 
Thanks @mblue9!

**Comment by bebatut** [comment]
The question now is how to select the next tutorial of the month and by who.

Maybe we could display the current tutorial of the month on the main page and a form to vote on their own favorite

**Comment by mblue9** [comment]
>The question now is how to select the next tutorial of the month and by who.

>Maybe we could display the current tutorial of the month on the main page and a form to vote on their own favorite. What do you think about that?

I like that suggestion of allowing people to vote for what tutorials they like, that would be useful information to know regardless of whether it's for tutorial of the month I think.

A couple of thoughts I have though are, if there are multiple people voting for the top tutorial which person would be named as the contributor of the tutorial of the month or would it just say this is the top voted tutorial? And would people need to vote every month (not a big deal I guess)? I am also currently only familiar with some of the tutorials so I think I would be biased towards voting for those :) Could you maybe also look at who's running workshops (during that month?) e.g. here: https://galaxyproject.org/events/ and pick one of those people to highlight a tutorial?

**Comment by hexylena** [comment]
I think this is now solved with our gtn-in-galaxy webhook that ensure the GTN is linked from the masthead of every galaxy >=20.09?

The tutorial of the month is maybe supplanted by the gxytraining twitter account tweeting updates?
