### ISSUE TITLE
Tags and curriculum

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#986]
It is already possible to add tags to the tutorials (#677) that are displayed on the topic pages.

As raised by @Slugger70 during the last GTN meeting (#954), we could expand their use and having 'genre' tags on tutorials, e.g. saying some tutorials are human tutorial/virus tutorial.
They could be used to develop 'curriculum' pages (for example aggregating all the microbial stuff if you're microbial and only care about microbial stuff).

What do you think about that?

**Comment by erasche** [comment]
Tags and learning paths are now there!
