### ISSUE TITLE
"Next tutorial"

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/training-material#987]
As we currently have the requirements (the tutorials to follow before), we could have some recommended tutorials to follow after the current tutorial. 

This could be internal tutorials but also links to other resources, defined in the metadata information. They would be displayed at the end of the tutorial.

Using that we could then develop and highlight some curriculum with "learning workflows" of several tutorials

What do you think about that?

**Comment by erasche** [comment]
Fixed in #1149
