### ISSUE TITLE
Docker Setup-Tutorials.sh Error

### ISSUE THREAD

**Issue by jraysajulga** [galaxyproject/training-material#991]
Hello! I'm having trouble building the docker image for the topics. I've tried it for both [proteomics](https://github.com/galaxyproject/training-material/blob/master/topics/proteomics/docker/Dockerfile) and [metagenomics](https://github.com/galaxyproject/training-material/blob/master/topics/metagenomics/docker/Dockerfile). 

Seems to be an error with the setup-tutorial.sh file:
```
Installing tutorial: /tutorials/database-handling
 - Installing tools
/setup-tutorials.sh: 27: /setup-tutorials.sh: shed-tools: not found
The command '/bin/sh -c /setup-tutorials.sh' returned a non-zero code: 127
```
It results from this prescribed docker build command:
```
docker build -t metagenomics-training -f topics/metagenomics/docker/Dockerfile .
```

Thoughts? Is it an issue with my settings? Am I jumping the gun on this Docker testing?

**Comment by bebatut** [comment]
@jraysajulga can you check if you still have the issue? 
@bedroesb did a great job on the Docker image recently

**Comment by jraysajulga** [comment]
Sure. It works now! Thank you @bedroesb and @bebatut. I might learn a thing or two from this setup.

**Comment by bebatut** [comment]
Great if it works now 😄  Thanks for reporting it
I close the issue, we can still reopen it if needed.
